package com.ailab.chemistry.domain.equipment;

public enum EquipmentErrorCode {
    INVALID_PROFILE,
    MISSING_CAPABILITY,
    VALUE_OUTSIDE_OPERATING_RANGE,
    INSUFFICIENT_RESOLUTION,
    MISSING_ACCURACY_OR_UNCERTAINTY,
    MISSING_CALIBRATION,
    EXPIRED_CALIBRATION,
    UNSUITABLE_CONDITION,
    PROFILE_UNAVAILABLE
}
