'use client';

import { AlertTriangle, Cable } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useTranslations } from 'next-intl';
import { adminPlatformApi } from '@/entities/admin/api/platform-admin.api';
import type { JsonObject } from '@/shared/api/contracts/platform';
import { hasEquipmentRenderer, renderEquipmentCanvas } from '@/entities/equipment/ui/EquipmentRendererRegistry';
import { EQUIPMENT_RENDER_BOUNDS, resolvePortScreenPosition } from '@/entities/equipment/lib/equipmentRenderBounds';
import { FormSection } from '@/widgets/admin/editor';
import type { EquipmentDraft, EquipmentPort } from './equipmentEditor.types';

const control='w-full rounded-lg border border-white/10 bg-[#111827] px-3 py-2 text-sm';
const object=(value:unknown):JsonObject=>value&&typeof value==='object'&&!Array.isArray(value)?value as JsonObject:{};
const rows=(value:unknown):JsonObject[]=>Array.isArray(value)?value as JsonObject[]:[];
const point=(port:{position:{x:number;y:number}})=>resolvePortScreenPosition(port.position);
const portType=(port:{type?:unknown;medium?:unknown})=>String(port.type??port.medium??'').toLowerCase();

function PreviewObject({rendererKey,ports,showPorts,selectedPort,onPort,fill,color,label}:{rendererKey:string;ports:Array<EquipmentPort|JsonObject>;showPorts:boolean;selectedPort:string;onPort?:(id:string)=>void;fill:number;color:string;label:string}){
  return <div className="relative h-56 w-56"><div className="pointer-events-none absolute inset-0 grid place-items-center">{renderEquipmentCanvas(rendererKey,{type:rendererKey,width:190,height:190,size:190,liquidLevel:fill/100,liquidColor:color,temperature:24.5})}</div>{showPorts&&ports.map((raw,index)=>{const port=object(raw),position=point({position:{x:Number(object(port.position).x??.5),y:Number(object(port.position).y??.5)}}),id=String(port.id??index),selected=selectedPort===id;return <button key={id} type="button" title={`${String(port.name??id)} · ${String(port.direction??'')} · ${String(port.type??port.medium??'')}`} onClick={()=>onPort?.(id)} style={{left:`${position.x*100}%`,top:`${position.y*100}%`}} className={`absolute z-20 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white ${selected?'bg-amber-400 ring-4 ring-amber-300/30':'bg-violet-500 opacity-50 hover:opacity-100'}`}/>})}<span className="absolute bottom-0 left-1/2 -translate-x-1/2 rounded bg-black/70 px-2 py-1 text-[10px] text-white">{label}</span></div>;
}

export function EquipmentSandboxPreview({draft}:{draft:EquipmentDraft}){
  const t=useTranslations('admin.equipmentEditor');
  const [theme,setTheme]=useState<'dark'|'light'>('dark'),[grid,setGrid]=useState(true),[showPorts,setShowPorts]=useState(false),[showBounds,setShowBounds]=useState(false);
  const [scale,setScale]=useState(1),[rotation,setRotation]=useState(0),[fill,setFill]=useState(0),[materials,setMaterials]=useState<JsonObject[]>([]),[materialId,setMaterialId]=useState('');
  const [equipment,setEquipment]=useState<JsonObject[]>([]),[peerId,setPeerId]=useState(''),[fromPort,setFromPort]=useState(''),[toPort,setToPort]=useState('');
  useEffect(()=>{let active=true;void Promise.all([adminPlatformApi.materials.list({status:'PUBLISHED',size:100,sort:'updatedAt,desc'}),adminPlatformApi.equipment.list({status:'PUBLISHED',size:100,sort:'updatedAt,desc'})]).then(([materialResult,equipmentResult])=>{if(!active)return;setMaterials(materialResult.items??materialResult.content??[]);setEquipment(equipmentResult.items??equipmentResult.content??[]);}).catch(()=>undefined);return()=>{active=false};},[]);
  const selectedMaterial=materials.find(item=>String(item.id??item.code)===materialId),appearance=object(selectedMaterial?.appearance),previewColor=String(appearance.color??'#22d3ee');
  const peer=equipment.find(item=>String(item.id??item.code)===peerId),peerPorts=rows(peer?.ports),peerRenderer=String(peer?.rendererKey??'beaker');
  const source=draft.ports.find(port=>port.id===fromPort),target=peerPorts.find(port=>String(port.id)===toPort);
  const compatible=Boolean(source&&target&&(!portType(source)||!portType(target)||portType(source)===portType(target)));
  const connectionLine=useMemo(()=>{if(!source||!target)return null;const a=point(source),b=point({position:{x:Number(object(target.position).x??.5),y:Number(object(target.position).y??.5)}});return{x1:40+a.x*220,y1:32+a.y*220,x2:360+b.x*220,y2:32+b.y*220};},[source,target]);
  const supported=hasEquipmentRenderer(draft.rendererKey);
  return <FormSection title={t('sandboxPreview')} description={t('sandboxPreviewHelp')}>
    <div className="grid gap-5 xl:grid-cols-[250px_minmax(0,1fr)]"><aside className="space-y-4 rounded-xl border border-white/[.07] bg-black/15 p-4"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setTheme('light')} className={`rounded-lg border px-3 py-2 text-sm ${theme==='light'?'border-violet-400 bg-violet-500/10':'border-white/10'}`}>{t('light')}</button><button type="button" onClick={()=>setTheme('dark')} className={`rounded-lg border px-3 py-2 text-sm ${theme==='dark'?'border-violet-400 bg-violet-500/10':'border-white/10'}`}>{t('dark')}</button></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={grid} onChange={event=>setGrid(event.target.checked)}/>{t('grid')}</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={showPorts} onChange={event=>setShowPorts(event.target.checked)}/>{t('showPorts')}</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={showBounds} onChange={event=>setShowBounds(event.target.checked)}/>{t('showBounds')}</label>{draft.category==='CONTAINER'&&<><label className="block text-xs text-slate-400">{t('previewContents')}<select className={`mt-2 ${control}`} value={materialId} onChange={event=>setMaterialId(event.target.value)}><option value="">Preview fluid</option>{materials.map(item=><option key={String(item.id??item.code)} value={String(item.id??item.code)}>{String(item.name??item.code??item.id)}</option>)}</select></label><label className="block text-xs text-slate-400">Amount · {fill}%<input className="mt-2 w-full accent-violet-500" type="range" min="0" max="100" step="25" value={fill} onChange={event=>setFill(Number(event.target.value))}/></label></>}<label className="block text-xs text-slate-400">{t('scale')} · {scale.toFixed(2)}<input className="mt-2 w-full accent-violet-500" type="range" min="0.5" max="1.5" step="0.05" value={scale} onChange={event=>setScale(Number(event.target.value))}/></label><label className="block text-xs text-slate-400">{t('rotation')} · {rotation}°<input className="mt-2 w-full accent-violet-500" type="range" min="-180" max="180" value={rotation} onChange={event=>setRotation(Number(event.target.value))}/></label></aside>
      <div className={`relative grid min-h-[540px] place-items-center overflow-hidden rounded-xl border ${theme==='dark'?'border-white/10 bg-[#080d16]':'border-slate-300 bg-slate-100'} ${grid?'bg-[linear-gradient(rgba(148,163,184,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(148,163,184,.12)_1px,transparent_1px)] bg-[size:24px_24px]':''}`}><div className={`relative h-80 w-80 ${showBounds?'border border-dashed border-amber-400':''}`} style={{transform:`scale(${scale}) rotate(${rotation}deg)`}}><div className="pointer-events-none absolute grid place-items-center" style={{left:`${EQUIPMENT_RENDER_BOUNDS.left*100}%`,top:`${EQUIPMENT_RENDER_BOUNDS.top*100}%`,width:`${EQUIPMENT_RENDER_BOUNDS.width*100}%`,height:`${EQUIPMENT_RENDER_BOUNDS.height*100}%`}}>{renderEquipmentCanvas(draft.rendererKey,{type:draft.rendererKey,width:256,height:256,size:256,liquidLevel:fill/100,liquidColor:previewColor,volumeMl:Number(draft.limits.capacityMl??250)*fill/100,capacityMl:Number(draft.limits.capacityMl??250),temperature:24.5})}</div>{showPorts&&draft.ports.map((port,index)=>{const position=point(port);return <span key={`${port.id}-${index}`} title={`${port.name||port.id} · ${port.direction}`} style={{left:`${position.x*100}%`,top:`${position.y*100}%`}} className="absolute h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white bg-violet-500 shadow-[0_0_12px_rgba(139,92,246,.8)]"/>;})}</div>{!supported&&<div className="absolute bottom-4 flex items-center gap-2 rounded-lg border border-amber-400/30 bg-amber-950/80 px-3 py-2 text-xs text-amber-200"><AlertTriangle size={14}/>{t('rendererUnavailable',{key:draft.rendererKey})}</div>}</div></div>
    <section className="mt-5 rounded-xl border border-cyan-400/20 bg-cyan-500/[.04] p-4"><div className="flex items-center gap-2"><Cable size={16} className="text-cyan-300"/><h3 className="text-sm font-semibold">Cross-equipment connection preview</h3></div><p className="mt-1 text-xs text-slate-500">Choose a published peer and one port on each object. Port markers stay hidden in the main preview until requested.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs text-slate-400">Peer equipment<select className={`mt-1 ${control}`} value={peerId} onChange={event=>{setPeerId(event.target.value);setToPort('');}}><option value="">Select peer</option>{equipment.map(item=><option key={String(item.id??item.code)} value={String(item.id??item.code)}>{String(item.name??item.code??item.id)}</option>)}</select></label><label className="text-xs text-slate-400">Draft port<select className={`mt-1 ${control}`} value={fromPort} onChange={event=>setFromPort(event.target.value)}><option value="">Select port</option>{draft.ports.map(port=><option key={port.id} value={port.id}>{port.name||port.id} · {port.type}</option>)}</select></label><label className="text-xs text-slate-400">Peer port<select className={`mt-1 ${control}`} value={toPort} disabled={!peer} onChange={event=>setToPort(event.target.value)}><option value="">Select port</option>{peerPorts.map(port=><option key={String(port.id)} value={String(port.id)}>{String(port.name??port.id)} · {String(port.type??port.medium??'')}</option>)}</select></label></div>{peer&&<div className="relative mx-auto mt-4 h-72 max-w-[620px] overflow-hidden rounded-xl border border-white/10 bg-[#080d16]"><svg className="pointer-events-none absolute inset-0 h-full w-full">{connectionLine&&<line {...connectionLine} stroke={compatible?'#22d3ee':'#fb7185'} strokeWidth="4" strokeDasharray="8 5"/>}</svg><div className="absolute left-5 top-4"><PreviewObject rendererKey={draft.rendererKey} ports={draft.ports} showPorts selectedPort={fromPort} onPort={setFromPort} fill={fill} color={previewColor} label={draft.code||'Draft equipment'}/></div><div className="absolute right-5 top-4"><PreviewObject rendererKey={peerRenderer} ports={peerPorts} showPorts selectedPort={toPort} onPort={setToPort} fill={0} color="#22d3ee" label={String(peer.name??peer.code??peer.id)}/></div>{source&&target&&<span className={`absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full px-3 py-1 text-xs ${compatible?'bg-emerald-500/15 text-emerald-200':'bg-rose-500/15 text-rose-200'}`}>{compatible?'Compatible connection':'Incompatible port media'}</span>}</div>}</section>
    <p className="mt-4 text-xs text-slate-500">{selectedMaterial?'Published material preview':'Preview fluid · no published material selected'} · {t('temporaryPreview')}</p>
  </FormSection>;
}
