'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { AlertCircle, CheckCircle2, Eye, ImageIcon, Loader2, Palette, Plus, Save, Trash2 } from 'lucide-react';
import AdminPageHeader from './AdminPageHeader';
import { adminPlatformApi } from '@/entities/admin/api/platform-admin.api';
import type { JsonObject } from '@/shared/api/contracts/platform';
import { errorMessage } from '@/shared/utils/errorMessage';
import { catalogCache } from '@/shared/lib/catalogCache';
import { sanitizeSvgMarkup } from '@/shared/lib/sanitizeSvg';
import { canonicalRendererId, listEquipmentRenderers } from '@/entities/equipment/ui/EquipmentRendererRegistry';

type Kind = 'equipment'|'scenario'|'material'|'safety'|'element'|'substance'|'reaction';
type Row = { substance: string; coefficient: number };
type Step = { instruction: string; equipment: string; material: string };
type Port = { id: string; type: string; direction: string; connector: string };

const meta: Record<Kind, { title: string; description: string; back: string }> = {
  equipment: { title: 'New equipment', description: 'Create equipment, its capacity, renderer and connection points.', back: '/admin/equipment' },
  scenario: { title: 'New scenario', description: 'Build a learning experiment from real catalog equipment and materials.', back: '/admin/scenarios' },
  material: { title: 'New material', description: 'Add a material, phase, properties and hazard level.', back: '/admin/materials' },
  safety: { title: 'New Safety Rule', description: 'Define the risk condition and safety-gate response.', back: '/admin/safety' },
  element: { title: 'New Chemical Element', description: 'Element card with symbol, atomic number and translations.', back: '/admin/science/chemistry' },
  substance: { title: 'New Substance', description: 'Formula, phase and physical properties.', back: '/admin/science/chemistry' },
  reaction: { title: 'New Reaction', description: 'Reactants, products, conditions and thermal effect.', back: '/admin/science/chemistry' },
};

const slug = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9а-яё]+/gi, '-').replace(/(^-|-$)/g, '');
const number = (value: string, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="grid gap-1.5 text-sm text-[#c1cada]"><span>{label}</span>{children}</label>;
const input = 'w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none transition focus:border-violet-400 [&>option]:bg-[#0b101a] [&>option]:text-white';

export default function AdminCatalogCreateForm({ kind }: { kind: Kind }) {
  const router = useRouter(); const { locale = 'ru' } = useParams<{ locale?: string }>(); const details = meta[kind];
  const [code, setCode] = useState(kind === 'element' ? 'Xx' : `new-${kind}`); const [name, setName] = useState('');
  const [ru, setRu] = useState(''); const [en, setEn] = useState(''); const [uz, setUz] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [category, setCategory] = useState('CONTAINER'); const [rendererKey, setRendererKey] = useState('beaker'); const [capacity, setCapacity] = useState('250'); const [maxTemp, setMaxTemp] = useState('773.15');
  const [ports, setPorts] = useState<Port[]>([{ id: 'TOP_OPENING', type: 'FLUID', direction: 'INPUT', connector: 'open-mouth' }]);
  const [difficulty, setDifficulty] = useState('BEGINNER'); const [trackId, setTrackId] = useState('chemistry-basics'); const [order, setOrder] = useState('1'); const [description, setDescription] = useState(''); const [steps, setSteps] = useState<Step[]>([{ instruction: '', equipment: '', material: '' }]);
  const [materialType, setMaterialType] = useState('SOLUTION'); const [phase, setPhase] = useState('LIQUID'); const [color, setColor] = useState('transparent'); const [density, setDensity] = useState(''); const [molarMass, setMolarMass] = useState(''); const [hazard, setHazard] = useState('NONE');
  const [condition, setCondition] = useState(''); const [effect, setEffect] = useState(''); const [severity, setSeverity] = useState('LOW');
  const [atomicNumber, setAtomicNumber] = useState('1'); const [atomicMass, setAtomicMass] = useState(''); const [group, setGroup] = useState('1'); const [period, setPeriod] = useState('1'); const [formula, setFormula] = useState('');
  const [reactants, setReactants] = useState<Row[]>([{ substance: '', coefficient: 1 }]); const [products, setProducts] = useState<Row[]>([{ substance: '', coefficient: 1 }]); const [temperature, setTemperature] = useState('298.15'); const [enthalpy, setEnthalpy] = useState('');
  const [editorTab, setEditorTab] = useState<'details' | 'names' | 'appearance'>('details');
  const [lightSvg, setLightSvg] = useState(''); const [darkSvg, setDarkSvg] = useState('');
  const [catalogs, setCatalogs] = useState<{ equipment: Array<{ id: string; code?: string; name: string }>; materials: Array<{ id: string; name: string; formula: string }> }>({ equipment: [], materials: [] });
  const [catalogError, setCatalogError] = useState<string | null>(null);
  useEffect(() => {
    if (kind !== 'scenario') return;
    Promise.all([catalogCache.getEquipment(), catalogCache.getMaterials()])
      .then(([equipment, materials]) => setCatalogs({
        equipment: equipment.map((entry) => ({ id: entry.profileId, code: entry.profileId, name: entry.displayName })),
        materials: materials.map((entry) => ({ id: entry.materialId, name: entry.name, formula: entry.formula })),
      }))
      .catch((reason) => setCatalogError(errorMessage(reason, 'Catalogs could not be loaded.')));
  }, [kind]);
  const safeLightSvg = useMemo(() => sanitizeSvgMarkup(lightSvg), [lightSvg]);
  const safeDarkSvg = useMemo(() => sanitizeSvgMarkup(darkSvg), [darkSvg]);
  const readSvgFile = (file: File | undefined, setter: (value: string) => void) => {
    if (!file) return;
    if (file.type !== 'image/svg+xml' && !file.name.toLowerCase().endsWith('.svg')) { setError('Select a valid SVG file.'); return; }
    const reader = new FileReader();
    reader.onload = () => { const safe = sanitizeSvgMarkup(String(reader.result ?? '')); if (!safe) setError('This SVG is invalid or contains unsupported content.'); else setter(safe); };
    reader.readAsText(file);
  };

  const translations = () => ({ ru, en, uz });
  const create = async () => {
    setError(null); setNotice(null);
    const cleanCode = (kind === 'element' ? code.trim() : slug(code || name));
    if (!cleanCode) { setError('Enter a record code.'); return; }
    if (!ru && !name) { setError('Add at least one localized name.'); return; }
    let payload: JsonObject;
    const visuals = (safeLightSvg || safeDarkSvg) ? { visuals: { lightSvg: safeLightSvg || undefined, darkSvg: safeDarkSvg || undefined } } : {};
    if (kind === 'equipment') payload = { code: cleanCode, name: name || en || ru, category, rendererKey, limits: { capacityMl: number(capacity, 250), maxTempK: number(maxTemp, 773.15) }, ports: ports.filter(port => port.id && port.connector), translations: translations(), ...visuals };
    else if (kind === 'scenario') payload = { code: cleanCode, subject: 'CHEMISTRY', trackId, difficulty, order: number(order, 1), scenario: { title: name || ru, description }, steps: steps.filter(step => step.instruction).map((step, index) => ({ order: index + 1, instruction: step.instruction, ...(step.equipment ? { targetEquipment: step.equipment } : {}), ...(step.material ? { targetMaterial: step.material } : {}) })), translations: translations() };
    else if (kind === 'material') payload = { code: cleanCode, name: name || en || ru, type: materialType, phase, appearance: { color, state: phase.toLowerCase() }, properties: { ...(density ? { density: number(density) } : {}), ...(molarMass ? { molarMass: number(molarMass) } : {}) }, safety: { hazard, severity }, translations: translations(), ...visuals };
    else if (kind === 'safety') payload = { code: cleanCode, category, severity, condition, effect, translations: translations() };
    else if (kind === 'element') payload = { symbol: cleanCode, name: name || en || ru, atomicNumber: number(atomicNumber, 1), properties: { group: number(group, 1), period: number(period, 1), ...(atomicMass ? { atomicMass: number(atomicMass) } : {}) }, translations: translations() };
    else if (kind === 'substance') payload = { code: cleanCode, name: name || en || ru, formula, phase, appearance: { color, state: phase.toLowerCase() }, properties: { ...(density ? { density: number(density) } : {}), ...(molarMass ? { molarMass: number(molarMass) } : {}) }, hazards: [], translations: translations(), ...visuals };
    else payload = { code: cleanCode, reactants: reactants.filter(row => row.substance).map(row => ({ substance: row.substance, coefficient: row.coefficient })), products: products.filter(row => row.substance).map(row => ({ substance: row.substance, coefficient: row.coefficient })), conditions: { temperatureK: number(temperature, 298.15), state: 'AQUEOUS' }, energy: enthalpy ? { enthalpyJoule: number(enthalpy) } : {}, translations: translations() };
    try {
      setBusy(true);
      const api = kind === 'equipment' ? adminPlatformApi.equipment : kind === 'scenario' ? adminPlatformApi.scenarios : kind === 'material' ? adminPlatformApi.materials : kind === 'safety' ? adminPlatformApi.safetyRules : kind === 'element' ? adminPlatformApi.chemistry.elements : kind === 'substance' ? adminPlatformApi.chemistry.substances : adminPlatformApi.chemistry.reactions;
      const created = await api.create(payload);
      setNotice(`Draft “${String(created.code ?? cleanCode)}” created.`);
      window.setTimeout(() => router.push(`/${locale}${details.back}`), 650);
    } catch (reason) { setError(errorMessage(reason, 'Draft could not be created')); } finally { setBusy(false); }
  };
  const update = <T,>(rows: T[], index: number, patch: Partial<T>, setRows: (value: T[]) => void) => setRows(rows.map((row, current) => current === index ? { ...row, ...patch } : row));
  const localeFields = <section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-3"><Field label="Russian name *"><input value={ru} onChange={event => setRu(event.target.value)} className={input} placeholder="Glass beaker in Russian"/></Field><Field label="English name"><input value={en} onChange={event => setEn(event.target.value)} className={input} placeholder="Glass beaker"/></Field><Field label="Uzbek name"><input value={uz} onChange={event => setUz(event.target.value)} className={input} placeholder="Shisha stakan"/></Field></section>;
  const appearanceEditor = <section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_260px]"><Field label="Light SVG"><input type="file" accept="image/svg+xml,.svg" onChange={event=>readSvgFile(event.target.files?.[0],setLightSvg)} className={input}/><textarea value={lightSvg} onChange={event => setLightSvg(event.target.value)} className={`${input} min-h-36 font-mono text-xs`} placeholder="Upload a file or paste SVG markup"/></Field><Field label="Dark SVG"><input type="file" accept="image/svg+xml,.svg" onChange={event=>readSvgFile(event.target.files?.[0],setDarkSvg)} className={input}/><textarea value={darkSvg} onChange={event => setDarkSvg(event.target.value)} className={`${input} min-h-36 font-mono text-xs`} placeholder="Upload a file or paste SVG markup"/></Field><div><p className="mb-2 text-sm text-[#c1cada]">Sanitized preview</p><div className="grid min-h-44 place-items-center rounded-xl border border-white/10 bg-white p-4" dangerouslySetInnerHTML={{ __html: safeLightSvg || '<span class=\"text-slate-400 text-sm\">Light SVG preview</span>' }} /><div className="mt-3 grid min-h-44 place-items-center rounded-xl border border-white/10 bg-slate-950 p-4" dangerouslySetInnerHTML={{ __html: safeDarkSvg || '<span class=\"text-slate-400 text-sm\">Dark SVG preview</span>' }} /></div></section>;
  const rowEditor = (rows: Row[], setRows: (value: Row[]) => void, label: string) => <section className="rounded-2xl border border-white/[.07] bg-[#0b101a] p-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold text-white">{label}</h2><button type="button" onClick={() => setRows([...rows, { substance: '', coefficient: 1 }])} className="flex items-center gap-1 text-sm text-violet-300"><Plus size={15}/>Add</button></div><div className="space-y-2">{rows.map((row, index) => <div key={index} className="grid grid-cols-[minmax(0,1fr)_100px_36px] gap-2"><input value={row.substance} onChange={event => update(rows, index, { substance: event.target.value }, setRows)} className={input} placeholder="Substance code, for example HCl"/><input type="number" min="1" value={row.coefficient} onChange={event => update(rows, index, { coefficient: number(event.target.value, 1) }, setRows)} className={input}/><button type="button" onClick={() => setRows(rows.filter((_, current) => current !== index))} className="grid place-items-center rounded-xl border border-red-500/20 text-red-300"><Trash2 size={15}/></button></div>)}</div></section>;

  return <div className="space-y-6 pb-12"><AdminPageHeader title={details.title} description={details.description}/>{notice && <div className="flex gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-300"><CheckCircle2 size={16}/>{notice}</div>}{error && <div className="flex gap-2 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300"><AlertCircle size={16}/>{error}</div>}<form onSubmit={event => { event.preventDefault(); void create(); }} className="space-y-5">{(kind === 'equipment' || kind === 'material' || kind === 'substance') && <nav className="flex gap-2" aria-label="Editor sections">{([{ id: 'details', label: 'Details', icon: Eye }, { id: 'names', label: 'Names', icon: Palette }, { id: 'appearance', label: 'SVG appearance', icon: ImageIcon }] as const).map(tab => <button key={tab.id} type="button" onClick={() => setEditorTab(tab.id)} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${editorTab === tab.id ? 'bg-violet-600 text-white' : 'border border-white/10 text-[#c1cada]'}`}><tab.icon size={15}/>{tab.label}</button>)}</nav>}{editorTab !== 'names' && editorTab !== 'appearance' && <><section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-2"><Field label={kind === 'element' ? 'Symbol *' : 'Code *'}><input value={code} onChange={event => setCode(event.target.value)} className={input} placeholder={kind === 'element' ? 'Na' : 'beaker-250'}/></Field><Field label="Primary name"><input value={name} onChange={event => setName(event.target.value)} className={input} placeholder="Internal English name or label"/></Field></section></>}{editorTab === 'names' && localeFields}{editorTab === 'appearance' && (kind === 'equipment' || kind === 'material' || kind === 'substance') && appearanceEditor}
    {kind === 'equipment' && <><section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-4"><Field label="Category"><select value={category} onChange={event => setCategory(event.target.value)} className={input}>{['CONTAINER','HEATING','MEASURING','TRANSFER','SUPPORT','SENSOR'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Renderer"><select value={rendererKey} onChange={event => setRendererKey(canonicalRendererId(event.target.value))} className={input}>{listEquipmentRenderers().map(renderer => <option key={renderer.key} value={renderer.key}>{renderer.label}</option>)}</select></Field><Field label="Capacity, mL"><input type="number" min="1" value={capacity} onChange={event => setCapacity(event.target.value)} className={input}/></Field><Field label="Maximum temperature, K"><input type="number" min="1" value={maxTemp} onChange={event => setMaxTemp(event.target.value)} className={input}/></Field></section><section className="rounded-2xl border border-white/[.07] bg-[#0b101a] p-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold text-white">Equipment ports</h2><button type="button" onClick={() => setPorts([...ports, { id: '', type: 'FLUID', direction: 'INPUT', connector: '' }])} className="flex items-center gap-1 text-sm text-violet-300"><Plus size={15}/>Add port</button></div><div className="space-y-2">{ports.map((port, index) => <div key={index} className="grid gap-2 md:grid-cols-[1fr_150px_160px_1fr_36px]"><input value={port.id} onChange={event => update(ports, index, { id: event.target.value }, setPorts)} className={input} placeholder="TOP_OPENING"/><select value={port.type} onChange={event => update(ports, index, { type: event.target.value }, setPorts)} className={input}>{['FLUID','THERMAL','ELECTRICAL'].map(value => <option key={value}>{value}</option>)}</select><select value={port.direction} onChange={event => update(ports, index, { direction: event.target.value }, setPorts)} className={input}>{['INPUT','OUTPUT','BIDIRECTIONAL'].map(value => <option key={value}>{value}</option>)}</select><input value={port.connector} onChange={event => update(ports, index, { connector: event.target.value }, setPorts)} className={input} placeholder="open-mouth"/><button type="button" onClick={() => setPorts(ports.filter((_, current) => current !== index))} className="grid place-items-center rounded-xl border border-red-500/20 text-red-300"><Trash2 size={15}/></button></div>)}</div></section></>}
    {kind === 'scenario' && <><section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-3"><Field label="Track"><input value={trackId} onChange={event => setTrackId(event.target.value)} className={input}/></Field><Field label="Difficulty"><select value={difficulty} onChange={event => setDifficulty(event.target.value)} className={input}>{['BEGINNER','INTERMEDIATE','ADVANCED'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Order"><input type="number" min="1" value={order} onChange={event => setOrder(event.target.value)} className={input}/></Field></section><Field label="Experiment description"><textarea value={description} onChange={event => setDescription(event.target.value)} className={`${input} min-h-24`} placeholder="What should the learner do?"/></Field>{catalogError&&<div role="alert" className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-sm text-amber-200">{catalogError}</div>}<section className="rounded-2xl border border-white/[.07] bg-[#0b101a] p-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold text-white">Scenario steps</h2><button type="button" onClick={() => setSteps([...steps, { instruction: '', equipment: '', material: '' }])} className="flex items-center gap-1 text-sm text-violet-300"><Plus size={15}/>Add step</button></div><div className="space-y-3">{steps.map((step, index) => <div key={index} className="grid gap-2 rounded-xl border border-white/[.06] p-3 md:grid-cols-[minmax(0,1fr)_210px_210px_36px]"><input value={step.instruction} onChange={event => update(steps, index, { instruction: event.target.value }, setSteps)} className={input} placeholder={`Instruction ${index + 1}`}/><select aria-label={`Equipment for step ${index + 1}`} value={step.equipment} onChange={event => update(steps, index, { equipment: event.target.value }, setSteps)} className={input}><option value="">Any equipment</option>{catalogs.equipment.map(entry=><option key={entry.id} value={entry.code ?? entry.id}>{entry.name ?? entry.code ?? entry.id}</option>)}</select><select aria-label={`Material for step ${index + 1}`} value={step.material} onChange={event => update(steps, index, { material: event.target.value }, setSteps)} className={input}><option value="">Any material</option>{catalogs.materials.map(entry=><option key={entry.id} value={entry.id}>{entry.name ?? entry.formula ?? entry.id}</option>)}</select><button type="button" aria-label={`Remove step ${index + 1}`} onClick={() => setSteps(steps.filter((_, current) => current !== index))} className="grid place-items-center rounded-xl border border-red-500/20 text-red-300"><Trash2 size={15}/></button></div>)}</div></section></>}
    {(kind === 'material' || kind === 'substance') && <section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-4"><Field label={kind === 'material' ? 'Type' : 'Formula'}>{kind === 'material' ? <select value={materialType} onChange={event => setMaterialType(event.target.value)} className={input}>{['SOLUTION','LIQUID','SOLID','GAS','METAL'].map(value => <option key={value}>{value}</option>)}</select> : <input value={formula} onChange={event => setFormula(event.target.value)} className={input} placeholder="H₂O"/>}</Field><Field label="Phase"><select value={phase} onChange={event => setPhase(event.target.value)} className={input}>{['SOLID','LIQUID','GAS','AQUEOUS'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Density"><input type="number" step="any" value={density} onChange={event => setDensity(event.target.value)} className={input}/></Field><Field label="Molar mass"><input type="number" step="any" value={molarMass} onChange={event => setMolarMass(event.target.value)} className={input}/></Field><Field label="Color"><input value={color} onChange={event => setColor(event.target.value)} className={input}/></Field>{kind === 'material' && <Field label="Hazard"><select value={hazard} onChange={event => setHazard(event.target.value)} className={input}>{['NONE','IRRITANT','CORROSIVE','TOXIC','FLAMMABLE'].map(value => <option key={value}>{value}</option>)}</select></Field>}</section>}
    {kind === 'safety' && <section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-3"><Field label="Category"><input value={category} onChange={event => setCategory(event.target.value)} className={input} placeholder="EXOTHERMIC_MIXING"/></Field><Field label="Severity"><select value={severity} onChange={event => setSeverity(event.target.value)} className={input}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Effect"><input value={effect} onChange={event => setEffect(event.target.value)} className={input} placeholder="THERMAL_EXPLOSION_HAZARD"/></Field><Field label="Condition"><textarea value={condition} onChange={event => setCondition(event.target.value)} className={`${input} min-h-24 md:col-span-3`} placeholder="materialA == '...' && materialB == '...'"/></Field></section>}
    {kind === 'element' && <section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-4"><Field label="Atomic number"><input type="number" min="1" value={atomicNumber} onChange={event => setAtomicNumber(event.target.value)} className={input}/></Field><Field label="Group"><input type="number" min="1" value={group} onChange={event => setGroup(event.target.value)} className={input}/></Field><Field label="Period"><input type="number" min="1" value={period} onChange={event => setPeriod(event.target.value)} className={input}/></Field><Field label="Atomic mass"><input type="number" step="any" value={atomicMass} onChange={event => setAtomicMass(event.target.value)} className={input}/></Field></section>}
    {kind === 'reaction' && <><div className="grid gap-5 xl:grid-cols-2">{rowEditor(reactants, setReactants, 'Reactants')}{rowEditor(products, setProducts, 'Products')}</div><section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-2"><Field label="Temperature, K"><input type="number" step="any" value={temperature} onChange={event => setTemperature(event.target.value)} className={input}/></Field><Field label="Enthalpy, J"><input type="number" step="any" value={enthalpy} onChange={event => setEnthalpy(event.target.value)} className={input}/></Field></section></>}
    <div className="flex justify-end"><button disabled={busy} className="flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? <Loader2 className="animate-spin" size={16}/> : <Save size={16}/>}Create draft</button></div>
  </form></div>;
}
