'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, History, Loader2, RotateCcw, Save } from 'lucide-react';
import AdminPageHeader from './AdminPageHeader';
import { adminPlatformApi } from '@/entities/admin/api/platform-admin.api';
import type { JsonObject } from '@/shared/api/contracts/platform';
import { errorMessage } from '@/shared/utils/errorMessage';

const object = (value:unknown):JsonObject => value && typeof value==='object' && !Array.isArray(value) ? value as JsonObject : {};
const array = (value:unknown):JsonObject[] => Array.isArray(value) ? value.filter(v=>v&&typeof v==='object') as JsonObject[] : [];
const fieldClass='mt-1 w-full rounded-lg border border-white/10 bg-[#070b13] px-3 py-2 text-sm text-white outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-500/20';

export default function AdminSettingsForm(){
  const [document,setDocument]=useState<JsonObject>({}),[values,setValues]=useState<JsonObject>({}),[groups,setGroups]=useState<JsonObject[]>([]),[subjects,setSubjects]=useState<JsonObject[]>([]),[versions,setVersions]=useState<JsonObject[]>([]);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [tab,setTab]=useState('general');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [settings,schema,subjectData,history]=await Promise.all([adminPlatformApi.settings.get(),adminPlatformApi.settings.schema(),adminPlatformApi.settings.subjects(),adminPlatformApi.settings.history({size:20})]);setDocument(settings);setValues(object(settings.settings));setGroups(array(schema.groups));setSubjects(array(subjectData.items));setVersions(history.items||history.content||[]);}catch(e){setError(errorMessage(e,'Unable to load settings'));}finally{setLoading(false);}},[]);
  useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>clearTimeout(id);},[load]);
  const update=(group:string,key:string,value:unknown)=>setValues(current=>({...current,[group]:{...object(current[group]),[key]:value}}));
  const save=async()=>{setSaving(true);setError('');try{await adminPlatformApi.settings.patch(values);setNotice('Settings saved and recorded in the audit log.');await load();}catch(e){setError(errorMessage(e,'Settings were not saved'));}finally{setSaving(false);}};
  const restore=async(version:unknown)=>{if(!confirm(`Restore settings version ${String(version)}?`))return;try{await adminPlatformApi.settings.restore(String(version),{reason:'Restored from Admin Settings UI'});setNotice(`Version ${String(version)} restored.`);await load();}catch(e){setError(errorMessage(e,'Version could not be restored'));}};
  const control=(group:string,field:JsonObject)=>{const key=String(field.key),type=String(field.type),value=object(values[group])[key],allowed=Array.isArray(field.allowed)?field.allowed:[];if(type==='BOOLEAN')return <button role="switch" aria-checked={Boolean(value)} onClick={()=>update(group,key,!Boolean(value))} className={`relative h-7 w-12 rounded-full ${value?'bg-violet-600':'bg-slate-700'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${value?'left-6':'left-1'}`}/></button>;if(allowed.length)return <select className={fieldClass} value={String(value??'')} onChange={e=>update(group,key,e.target.value)}>{allowed.map(v=><option key={String(v)}>{String(v)}</option>)}</select>;if(type==='ARRAY_STRING')return <input className={fieldClass} value={Array.isArray(value)?value.join(', '):''} onChange={e=>update(group,key,e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} placeholder="Comma-separated values"/>;return <input className={fieldClass} type={type==='INTEGER'?'number':key.toLowerCase().includes('email')?'email':'text'} min={field.min as number|undefined} max={field.max as number|undefined} value={String(value??'')} onChange={e=>update(group,key,type==='INTEGER'?Number(e.target.value):e.target.value)}/>;};
  const tabs = ['general','localization','learning','laboratory','simulation','ai','sharing','subjects','history']; const visibleGroups = useMemo(() => groups.filter(group => { const key = `${String(group.key)} ${String(group.title)}`.toLowerCase(); if (tab === 'general') return !['local','learning','laboratory','simulation','ai','sharing'].some(part => key.includes(part)); if (tab === 'localization') return key.includes('local'); if (tab === 'learning') return key.includes('learn'); if (tab === 'laboratory') return key.includes('lab'); if (tab === 'simulation') return key.includes('sim'); if (tab === 'ai') return key.includes('ai'); if (tab === 'sharing') return key.includes('shar'); return false; }), [groups, tab]);
  return <div className="space-y-6 pb-12"><AdminPageHeader title="Platform Settings" description="Schema-driven configuration, subjects and version history from the backend." counters={[{label:'Version',value:String(document.version??'—')},{label:'Subjects',value:subjects.length},{label:'History',value:versions.length}]} actions={<button disabled={saving} onClick={()=>void save()} className="flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold disabled:opacity-50">{saving?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>}Save changes</button>}/>
    <div aria-live="polite">{notice&&<div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-300">{notice}</div>}{error&&<div className="flex items-center gap-2 rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300"><AlertCircle size={17}/>{error}<button className="ml-auto underline" onClick={()=>void load()}>Retry</button></div>}</div>
    <nav className="flex gap-1 overflow-x-auto border-b border-white/[.08]" aria-label="Settings sections">{tabs.map(item=><button key={item} type="button" onClick={()=>setTab(item)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-semibold capitalize ${tab===item?'border-violet-400 text-white':'border-transparent text-slate-400'}`}>{item}</button>)}</nav>
    {loading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-violet-400"/></div>:<div className="grid gap-6 xl:grid-cols-[minmax(0,1.7fr)_minmax(310px,1fr)]"><section className="grid content-start gap-4 md:grid-cols-2">{(tab === 'subjects' || tab === 'history' ? [] : visibleGroups).map(group=><fieldset key={String(group.key)} className="rounded-2xl border border-white/[.07] bg-[#0b101a] p-5"><legend className="px-1 font-semibold text-white">{String(group.title||group.key)}</legend><div className="mt-2 space-y-4">{array(group.fields).map(field=><label key={String(field.key)} className="flex items-center justify-between gap-4 text-sm text-slate-300"><span className="capitalize">{String(field.key).replace(/([A-Z])/g,' $1')}</span><span className={String(field.type)==='BOOLEAN'?'':'min-w-[55%]'}>{control(String(group.key),field)}</span></label>)}</div></fieldset>)}{(tab==='ai'||tab==='sharing')&&<div className="rounded-2xl border border-amber-400/20 bg-amber-500/[.05] p-5 text-sm text-amber-200"><strong>Waiting for backend support</strong><p className="mt-2 text-xs leading-5 text-amber-100/70">This settings boundary is ready, but no persistence schema was returned by the backend.</p></div>}</section><div className="space-y-6">{(tab==='subjects'||tab==='general')&&<section className="rounded-2xl border border-white/[.07] bg-[#0b101a] p-5"><h2 className="font-semibold">Science subjects</h2><div className="mt-4 space-y-2">{subjects.length===0&&<p className="text-sm text-slate-500">No subjects returned.</p>}{subjects.map(subject=><button key={String(subject.id)} onClick={async()=>{await adminPlatformApi.settings.patchSubject(String(subject.id),{enabled:!Boolean(subject.enabled)});await load();}} className="flex w-full items-center justify-between rounded-xl border border-white/[.06] bg-white/[.02] p-3 text-left"><span className="text-sm">{String(subject.name||subject.code)}</span><span className={subject.enabled?'text-emerald-300':'text-slate-500'}>{subject.enabled?'Enabled':'Disabled'}</span></button>)}</div></section>}{(tab==='history'||tab==='general')&&<section className="rounded-2xl border border-white/[.07] bg-[#0b101a] p-5"><h2 className="flex items-center gap-2 font-semibold"><History size={16}/>Version history</h2><div className="mt-4 max-h-80 space-y-2 overflow-y-auto">{versions.map((entry,index)=><div key={String(entry.version??index)} className="flex items-center justify-between rounded-xl bg-white/[.025] p-3"><div><strong className="text-sm">v{String(entry.version)}</strong><p className="text-xs text-slate-500">{entry.createdAt?new Date(String(entry.createdAt)).toLocaleString('en-GB',{timeZone:'Asia/Tashkent'}):'—'}</p></div><button onClick={()=>void restore(entry.version)} className="grid h-8 w-8 place-items-center rounded-lg border border-white/10 text-amber-300" aria-label={`Restore version ${String(entry.version)}`}><RotateCcw size={14}/></button></div>)}</div></section>}</div></div>}
  </div>;
}
