'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { AlertCircle, CheckCircle2, ExternalLink, Eye, Loader2, Save, Search } from 'lucide-react';
import AdminPageHeader from './AdminPageHeader';
import { adminLearningApi } from '@/entities/learning/api/learning.api';
import { adminPlatformApi } from '@/entities/admin/api/platform-admin.api';
import type { JsonObject } from '@/shared/api/contracts/platform';
import { errorMessage } from '@/shared/utils/errorMessage';
import { LevelIntro, type LevelIntroDefinition } from '@/widgets/sandbox/LevelIntro';

type Locale = 'ru' | 'uz' | 'en';
type Copy = { title: string; summary: string; goal: string; objectives: string[]; stepTitle: string; instruction: string };
const control = 'w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none transition focus:border-violet-400 [&>option]:bg-[#0b101a] [&>option]:text-white';
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="grid gap-1.5 text-sm text-[#c1cada]"><span>{label}</span>{children}</label>;

export default function AdminLearningLevelCreateForm({ id }: { id?: string }) {
  const router = useRouter(); const { locale = 'ru' } = useParams<{ locale?: string }>();
  const [activeLocale, setActiveLocale] = useState<Locale>('en');
  const [copy, setCopy] = useState<Record<Locale, Copy>>({ ru: { title: '', summary: '', goal: '', objectives: [], stepTitle: '', instruction: '' }, uz: { title: '', summary: '', goal: '', objectives: [], stepTitle: '', instruction: '' }, en: { title: '', summary: '', goal: '', objectives: [], stepTitle: '', instruction: '' } });
  const [trackId, setTrackId] = useState('chemistry'); const [levelNumber, setLevelNumber] = useState('1'); const [order, setOrder] = useState('1'); const [difficulty, setDifficulty] = useState('BEGINNER'); const [minutes, setMinutes] = useState('10');
  const [scenarioId, setScenarioId] = useState(''); const [scenarioSearch, setScenarioSearch] = useState(''); const [scenarioLoading, setScenarioLoading] = useState(false); const [scenarios, setScenarios] = useState<JsonObject[]>([]);
  const [stepType, setStepType] = useState('CONTAINER_SETUP'); const [factType, setFactType] = useState('CONTAINER_PRESENT'); const [guideKind, setGuideKind] = useState('TAB'); const [guideTarget, setGuideTarget] = useState('equipment'); const [guideText, setGuideText] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  useEffect(() => { let active = true; setScenarioLoading(true); const timer = window.setTimeout(() => { void adminPlatformApi.scenarios.list({ status: 'PUBLISHED', search: scenarioSearch.trim() || undefined, size: 30, sort: 'updatedAt,desc' }).then(response => { if (!active) return; const next = response.items ?? response.content ?? []; setScenarios(current => { const selected = current.find(item => String(item.id ?? item.code) === scenarioId); return selected && !next.some(item => String(item.id ?? item.code) === scenarioId) ? [selected, ...next] : next; }); }).catch(() => undefined).finally(() => active && setScenarioLoading(false)); }, 250); return () => { active = false; window.clearTimeout(timer); }; }, [scenarioId, scenarioSearch]);
  useEffect(() => { if (!id) return; let active = true; void adminLearningApi.level(id).then(record => { if (!active) return; setTrackId(String(record.trackId ?? 'chemistry')); setLevelNumber(String(record.levelNumber ?? 1)); setOrder(String(record.order ?? 1)); setDifficulty(String(record.difficulty ?? 'BEGINNER')); setMinutes(String(record.estimatedMinutes ?? 10)); setScenarioId(String(record.scenarioId ?? (record.scenario as JsonObject | undefined)?.id ?? '')); const translations = record.translations && typeof record.translations === 'object' ? record.translations as JsonObject : {}; setCopy(current => Object.fromEntries((['ru','uz','en'] as Locale[]).map(lang => { const value = translations[lang] && typeof translations[lang] === 'object' ? translations[lang] as JsonObject : {}; return [lang, { ...current[lang], title: String(value.title ?? ''), summary: String(value.summary ?? ''), goal: String(value.goal ?? ''), objectives: Array.isArray(value.learningObjectives) ? value.learningObjectives.map(String) : [] }]; })) as Record<Locale,Copy>); }).catch(reason => active && setError(errorMessage(reason,'Level could not be loaded'))); return () => { active = false; }; }, [id]);
  const updateCopy = (patch: Partial<Copy>) => setCopy(current => ({ ...current, [activeLocale]: { ...current[activeLocale], ...patch } }));
  const fallback = (lang: Locale, key: keyof Copy) => copy[lang][key];
  const create = async () => {
    if (!trackId.trim() || !scenarioId || (['ru', 'uz', 'en'] as Locale[]).some(lang => !copy[lang].title.trim())) { setError('Track, a published Scenario, and a title in every locale (RU, UZ, EN) are required.'); return; }
    setBusy(true); setError(null);
    try {
      const translations = Object.fromEntries((['ru', 'uz', 'en'] as Locale[]).map(lang => [lang, { title: fallback(lang, 'title'), summary: fallback(lang, 'summary'), goal: fallback(lang, 'goal'), learningObjectives: copy[lang].objectives }]));
      const created = id ? await adminLearningApi.patchLevel(id, { trackId: trackId.trim(), levelNumber: Number(levelNumber), order: Number(order), difficulty, estimatedMinutes: Number(minutes), ...(scenarioId ? { scenarioId } : {}), translations }) : await adminLearningApi.createLevel({ trackId: trackId.trim(), levelNumber: Number(levelNumber), order: Number(order), difficulty, estimatedMinutes: Number(minutes), ...(scenarioId ? { scenarioId } : {}), translations });
      if (id && copy.ru.instruction.trim()) {
        const stepTranslations = Object.fromEntries((['ru', 'uz', 'en'] as Locale[]).map(lang => [lang, { title: fallback(lang, 'stepTitle'), instruction: fallback(lang, 'instruction') }]));
        await adminLearningApi.saveSteps(String(created.id), { version: Number(created.version), steps: [{ id: 'step-1', order: 1, type: stepType, translations: stepTranslations, checkpoint: { factType, source: {}, target: {}, parameters: {} }, guideTargets: guideTarget.trim() ? [{ level: 1, kind: guideKind, id: guideTarget.trim(), catalogCode: guideKind === 'ITEM' ? guideTarget.trim() : null, placement: 'top', text: guideText.trim() || undefined, sequence: 1 }] : [] }] });
      }
      setNotice(id ? 'Level changes saved.' : `Level ${String(created.id)} created as a draft.`); if (!id) window.setTimeout(() => router.push(`/${locale}/admin/learning/levels/${String(created.id)}`), 650);
    } catch (reason) { setError(errorMessage(reason, 'Level could not be created')); } finally { setBusy(false); }
  };
  const current = copy[activeLocale];
  const selectedScenario = scenarios.find(item => String(item.id ?? item.code) === scenarioId); const scenarioResources = selectedScenario?.resources && typeof selectedScenario.resources === 'object' ? selectedScenario.resources as JsonObject : {};
  const previewLevel: LevelIntroDefinition = { id: Number(levelNumber) || 1, scenarioId: scenarioId || 'draft-scenario', title: { ru: copy.ru.title || 'Untitled level', uz: copy.uz.title || 'Untitled level', en: copy.en.title || 'Untitled level' }, objective: { ru: copy.ru.goal, uz: copy.uz.goal, en: copy.en.goal }, learningPoints: Array.from({ length: Math.max(copy.ru.objectives.length, copy.uz.objectives.length, copy.en.objectives.length) }, (_, index) => ({ ru: copy.ru.objectives[index] || '—', uz: copy.uz.objectives[index] || '—', en: copy.en.objectives[index] || '—' })), duration: { ru: `~${minutes} minutes`, uz: `~${minutes} minutes`, en: `~${minutes} minutes` }, allowedEquipment: Array.isArray(scenarioResources.equipmentIds) ? scenarioResources.equipmentIds.map(String) : [], allowedMaterials: Array.isArray(scenarioResources.materialIds) ? scenarioResources.materialIds.map(String) : [] };
  return <div className="space-y-6 pb-12"><AdminPageHeader title={id ? 'Edit learning level' : 'New learning level'} description="Configure curriculum metadata, localized objectives, and the linked Scenario." />
    {notice && <div className="flex gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-300"><CheckCircle2 size={16} />{notice}</div>}{error && <div className="flex gap-2 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300"><AlertCircle size={16} />{error}</div>}
    <form onSubmit={event => { event.preventDefault(); void create(); }} className="space-y-5">
      <section className="grid gap-4 rounded-2xl border border-white/[.07] bg-[#0b101a] p-5 md:grid-cols-3"><Field label="Track ID *"><input value={trackId} onChange={e => setTrackId(e.target.value)} className={control} /></Field><Field label="Level number"><input type="number" min="1" value={levelNumber} onChange={e => setLevelNumber(e.target.value)} className={control} /></Field><Field label="Order"><input type="number" min="1" value={order} onChange={e => setOrder(e.target.value)} className={control} /></Field><Field label="Difficulty"><select value={difficulty} onChange={e => setDifficulty(e.target.value)} className={control}>{['BEGINNER', 'INTERMEDIATE', 'ADVANCED'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Estimated minutes"><input type="number" min="1" value={minutes} onChange={e => setMinutes(e.target.value)} className={control} /></Field><div className="space-y-2 md:col-span-3"><span className="text-sm text-[#c1cada]">Published Scenario *</span><div className="grid gap-2 md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3 text-slate-500" size={15}/><input aria-label="Search published Scenarios" value={scenarioSearch} onChange={event=>setScenarioSearch(event.target.value)} className={`${control} pl-9`} placeholder="Search by name or code"/>{scenarioLoading&&<Loader2 className="absolute right-3 top-3 animate-spin text-violet-300" size={15}/>}</label><select aria-label="Selected Scenario" value={scenarioId} onChange={e => setScenarioId(e.target.value)} className={control}><option value="">Select a published Scenario</option>{scenarios.map(item => <option key={String(item.id ?? item.code)} value={String(item.id ?? item.code)}>{String(item.name ?? item.title ?? item.code ?? item.id)}</option>)}</select>{scenarioId&&<Link href={`/${locale}/admin/scenarios/${scenarioId}`} className="flex items-center justify-center gap-2 rounded-xl border border-violet-400/30 px-4 py-2 text-sm font-semibold text-violet-200">Open selected<ExternalLink size={14}/></Link>}</div><p className="text-xs text-slate-500">Results are searched on the server and limited to published Scenarios.</p></div></section>
      <section className="rounded-2xl border border-white/[.07] bg-[#0b101a] p-5"><div className="mb-5 flex gap-2" role="tablist">{(['ru', 'uz', 'en'] as Locale[]).map(lang => <button key={lang} type="button" role="tab" aria-selected={activeLocale === lang} onClick={() => setActiveLocale(lang)} className={`rounded-lg px-4 py-2 text-sm font-semibold uppercase ${activeLocale === lang ? 'bg-violet-600 text-white' : 'border border-white/10 text-[#9aa6ba]'}`}>{lang}</button>)}</div><div className="grid gap-4 md:grid-cols-2"><Field label="Title *"><input value={current.title} onChange={e => updateCopy({ title: e.target.value })} className={control} /></Field><Field label="Goal"><input value={current.goal} onChange={e => updateCopy({ goal: e.target.value })} className={control} /></Field><Field label="Summary"><textarea value={current.summary} onChange={e => updateCopy({ summary: e.target.value })} className={`${control} min-h-24 md:col-span-2`} /></Field><div className="md:col-span-2"><span className="text-sm text-[#c1cada]">Learning objectives</span><div className="mt-2 space-y-2">{current.objectives.map((objective,index)=><div key={index} className="flex gap-2"><input className={control} value={objective} onChange={e=>updateCopy({objectives:current.objectives.map((item,currentIndex)=>currentIndex===index?e.target.value:item)})}/><button type="button" onClick={()=>updateCopy({objectives:current.objectives.filter((_,currentIndex)=>currentIndex!==index)})} className="rounded-lg border border-rose-500/30 px-3 text-sm text-rose-200">Remove</button></div>)}<button type="button" onClick={()=>updateCopy({objectives:[...current.objectives,'']})} className="rounded-lg border border-violet-400/40 px-3 py-2 text-sm text-violet-200">Add objective</button></div></div></div></section>
      {id && <details className="rounded-2xl border border-amber-400/20 bg-amber-500/[.04] p-5"><summary className="cursor-pointer text-sm font-semibold text-amber-200">Advanced · Legacy learning fields</summary><p className="mt-2 text-xs text-amber-200/70">These fields belong to the legacy Learning runtime. New content should use a Scenario.</p><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Step type"><select value={stepType} onChange={e => setStepType(e.target.value)} className={control}>{['CONTAINER_SETUP', 'REAGENT_ADDITION', 'PORT_CONNECTION', 'HEATING', 'REACTION_RUN', 'MEASUREMENT'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Checkpoint fact"><input value={factType} onChange={e => setFactType(e.target.value)} className={control} /></Field><Field label="Guide kind"><select value={guideKind} onChange={e => setGuideKind(e.target.value)} className={control}>{['TAB', 'ITEM', 'PORT_PAIR', 'CANVAS_REGION'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Guide target"><input value={guideTarget} onChange={e => setGuideTarget(e.target.value)} className={control} placeholder="equipment or catalog code" /></Field><Field label="Guide / hint text"><textarea value={guideText} onChange={e => setGuideText(e.target.value)} className={`${control} min-h-20 md:col-span-2 lg:col-span-4`} /></Field></div></details>}
      <div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowPreview(true)} className="flex items-center gap-2 rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold"><Eye size={16}/>Learner preview</button><button disabled={busy} className="flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />}{id ? 'Save changes' : 'Create level'}</button></div>
    </form>
    {showPreview && <LevelIntro level={previewLevel} locale={activeLocale} onStart={()=>setShowPreview(false)}/>} 
  </div>;
}
