'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { adminBookApi } from '@/entities/book/api/book.api';
import { adminPlatformApi } from '@/entities/admin/api/platform-admin.api';
import { sanitizeSvgMarkup as sanitizeSvg } from '@/shared/lib/sanitizeSvg';
import { getApiBaseUrl } from '@/shared/api/client';
import type { JsonObject } from '@/shared/api/contracts/platform';
import type { Locale } from '@/shared/types/catalog';
import { RichTextEditor } from './book-studio/RichTextEditor';
import { BookBlockRenderer, hydrateBookPageBlocks, type BookBlockKind as Kind, type BookPageBlock as Block } from './book-studio/BookPageRenderer';
import { scenarioDraft } from './scenario/scenario.model';
import type { ScenarioDraft } from './scenario/scenario.types';
import { SandboxWorkspace } from '@/widgets/sandbox/SandboxWorkspace';

type Drag = { id:string; mode:'move'|'resize'; startX:number; startY:number; original:Block } | null;

const button = 'rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-sm text-slate-200 hover:border-violet-400 focus:outline-none focus:ring-2 focus:ring-violet-500';
const input = 'w-full rounded-lg border border-white/10 bg-[#080c14] px-3 py-2 text-sm text-white outline-none focus:border-violet-500';
const n = (value:unknown, fallback=0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const obj = (value:unknown):JsonObject => value && typeof value === 'object' && !Array.isArray(value) ? value as JsonObject : {};
const items = (value:unknown):JsonObject[] => Array.isArray(value) ? value.filter(v=>v && typeof v === 'object') as JsonObject[] : [];
const label = (value:JsonObject) => String(obj(value.translations).en || obj(value.translations).ru || value.title || value.name || value.slug || value.code || value.id || 'Untitled');

function hydrate(raw:unknown, locale:Locale='en'):Block[] {
  return hydrateBookPageBlocks(raw,locale);
}

export default function BookStudioCanvas() {
  const [books,setBooks]=useState<JsonObject[]>([]), [book,setBook]=useState<JsonObject|null>(null), [page,setPage]=useState<JsonObject|null>(null);
  const [blocks,setBlocks]=useState<Block[]>([]), [selected,setSelected]=useState(''), [scenarios,setScenarios]=useState<JsonObject[]>([]);
  const [history,setHistory]=useState<Block[][]>([]), [future,setFuture]=useState<Block[][]>([]), [preview,setPreview]=useState(false);
  const [contentLocale,setContentLocale]=useState<Locale>('en');
  const [interactiveDraft,setInteractiveDraft]=useState<ScenarioDraft|null>(null);
  const [busy,setBusy]=useState(false), [notice,setNotice]=useState(''), [error,setError]=useState('');
  const drag=useRef<Drag>(null), richTextStart=useRef<Block[]|null>(null), fileRef=useRef<HTMLInputElement>(null), svgRef=useRef<HTMLInputElement>(null);

  const chapters=useMemo(()=>items(book?.chapters),[book]);
  const pages=useMemo(()=>chapters.flatMap(ch=>items(ch.pages)),[chapters]);
  const active=blocks.find(b=>b.id===selected);
  const nextPage=pages[pages.findIndex(candidate=>candidate.id===page?.id)+1];
  const nextBlocks=useMemo(()=>hydrate(nextPage?.blocks,contentLocale),[contentLocale,nextPage]);

  const loadBook=useCallback(async(id:string)=>{ const detail=await adminBookApi.get(id); setBook(detail); const first=items(detail.chapters).flatMap(ch=>items(ch.pages))[0] || null; setPage(first); setBlocks(hydrate(first?.blocks,contentLocale)); setHistory([]); setFuture([]); },[contentLocale]);
  const load=useCallback(async()=>{ setBusy(true); setError(''); try { const [bookList,scenarioList]=await Promise.all([adminBookApi.list({size:100}),adminPlatformApi.scenarios.list({size:100,status:'PUBLISHED'})]); setBooks(bookList.items); setScenarios(scenarioList.items); if(bookList.items[0]) await loadBook(String(bookList.items[0].id)); } catch(e){setError(e instanceof Error?e.message:'Unable to load Book Studio');} finally{setBusy(false);} },[loadBook]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);

  const commit=(next:Block[])=>{setHistory(h=>[...h,blocks]);setFuture([]);setBlocks(next);};
  const patchBlock=(id:string,patch:Partial<Block>,record=true)=>{const next=blocks.map(b=>b.id===id?{...b,...patch}:b); record?commit(next):setBlocks(next);};
  const add=(kind:Kind)=>{const top=Math.max(0,...blocks.map(b=>b.z))+1; const created:Block={id:crypto.randomUUID(),kind,x:60,y:60,w:kind==='RICH_TEXT'?420:280,h:kind==='RICH_TEXT'?160:210,z:top,text:'New text',formula:'H_2O',scenarioId:String(scenarios[0]?.id||'')};commit([...blocks,created]);setSelected(created.id);};
  const undo=()=>{const previous=history.at(-1);if(!previous)return;setFuture(f=>[blocks,...f]);setBlocks(previous);setHistory(h=>h.slice(0,-1));};
  const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,blocks]);setBlocks(next);setFuture(f=>f.slice(1));};

  useEffect(()=>{const move=(event:PointerEvent)=>{const d=drag.current;if(!d)return;const dx=event.clientX-d.startX,dy=event.clientY-d.startY;if(d.mode==='move')patchBlock(d.id,{x:Math.max(0,d.original.x+dx),y:Math.max(0,d.original.y+dy)},false);else patchBlock(d.id,{w:Math.max(100,d.original.w+dx),h:Math.max(70,d.original.h+dy)},false);}; const up=()=>{const d=drag.current;if(!d)return;const previous=blocks.map(block=>block.id===d.id?d.original:block);setHistory(h=>[...h,previous]);setFuture([]);drag.current=null;};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};},[blocks]);

  useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();return;}if(!active)return;if(event.key==='Escape'){setSelected('');return;}if(event.key==='Delete'){commit(blocks.filter(b=>b.id!==active.id));setSelected('');return;}const delta=event.shiftKey?10:1;const movement:Record<string,Partial<Block>>={ArrowLeft:{x:active.x-delta},ArrowRight:{x:active.x+delta},ArrowUp:{y:active.y-delta},ArrowDown:{y:active.y+delta}};if(movement[event.key]){event.preventDefault();patchBlock(active.id,movement[event.key]);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});

  const selectPage=(next:JsonObject)=>{setPage(next);setBlocks(hydrate(next.blocks,contentLocale));setSelected('');setHistory([]);setFuture([]);};
  const save=async()=>{if(!book||!page)return;setBusy(true);setError('');try{await adminBookApi.saveBlocks(String(book.id),String(page.id),{version:n(page.version,1),blocks:[...blocks].sort((a,b)=>a.z-b.z).map(b=>({id:b.id,type:b.kind,translations:b.kind==='RICH_TEXT'?{...b.translations,[contentLocale]:{content:b.text||''}}:{},data:{src:b.src,assetId:b.assetId,svg:b.svg,latex:b.formula,scenarioId:b.scenarioId,layout:{x:b.x,y:b.y,width:b.w,height:b.h,zIndex:b.z}}}))});setNotice('Page saved');await loadBook(String(book.id));}catch(e){setError(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}};
  const upload=async(event:React.ChangeEvent<HTMLInputElement>,kind:'IMAGE'|'SVG')=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(kind==='SVG'){const safe=sanitizeSvg(await file.text());if(!safe){setError('Unsafe or invalid SVG');return;}const id=selected||blocks.find(b=>b.kind==='SVG')?.id;if(id)patchBlock(id,{svg:safe});else{const created:Block={id:crypto.randomUUID(),kind:'SVG',x:70,y:70,w:300,h:220,z:blocks.length+1,svg:safe};commit([...blocks,created]);setSelected(created.id);}return;}setBusy(true);const response=await adminPlatformApi.assets.uploadUrls({files:[{filename:file.name,contentType:file.type,sizeBytes:file.size,kind:'IMAGE'}]});const target=Array.isArray(response.uploads)?obj(response.uploads[0]):{};if(!target.uploadUrl||!target.assetId)throw new Error('Upload target was not created.');const uploadUrl=String(target.uploadUrl).startsWith('/')?`${getApiBaseUrl()}${target.uploadUrl}`:String(target.uploadUrl);const uploaded=await fetch(uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!uploaded.ok)throw new Error(`Image upload failed (${uploaded.status}).`);const completed=await adminPlatformApi.assets.complete(String(target.assetId),{});const src=String(completed.downloadUrl??target.downloadUrl??'');const assetId=String(target.assetId);const id=selected||blocks.find(b=>b.kind==='IMAGE')?.id;if(id)patchBlock(id,{src,assetId});else{const created:Block={id:crypto.randomUUID(),kind:'IMAGE',x:70,y:70,w:300,h:220,z:blocks.length+1,src,assetId};commit([...blocks,created]);setSelected(created.id);}}catch(reason){setError(reason instanceof Error?reason.message:'Image upload failed.');}finally{setBusy(false);}};
  const openInteractive=async(scenarioId:string)=>{setBusy(true);setError('');try{setInteractiveDraft(scenarioDraft(await adminPlatformApi.scenarios.get(scenarioId)));}catch(reason){setError(reason instanceof Error?reason.message:'Could not open interactive Scenario.');}finally{setBusy(false)}};

  const renderBlock=(b:Block)=> <BookBlockRenderer block={b} scenarioLabel={label(scenarios.find(s=>String(s.id)===b.scenarioId)||{})} onInteract={b.scenarioId?()=>void openInteractive(b.scenarioId!):undefined}/>;

  return <main className="min-h-full p-5 text-slate-100 lg:p-8">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 pb-5"><div><h1 className="text-2xl font-bold">Book Studio</h1><p className="mt-1 text-sm text-slate-400">Visual page composition backed by the real book API.</p></div><div className="flex gap-2"><button className={button} onClick={()=>setPreview(v=>!v)}>{preview?'Edit':'Two-page preview'}</button><button className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold disabled:opacity-50" disabled={busy||!page} onClick={save}>Save page</button></div></header>
    <div aria-live="polite" className="mt-3 min-h-6 text-sm"><span className="text-emerald-400">{notice}</span><span className="text-rose-400">{error}</span>{error&&<button className="ml-3 underline" onClick={()=>void load()}>Retry</button>}</div>
    <section className="mt-3 grid gap-4 xl:grid-cols-[220px_minmax(0,1fr)_280px]">
      <aside className="rounded-xl border border-white/10 bg-[#0c121e] p-4"><h2 className="font-semibold">Books</h2><div className="mt-3 space-y-2">{busy&&!books.length&&<div className="h-16 animate-pulse rounded-lg bg-white/5"/>}{books.map(item=><button key={String(item.id)} onClick={()=>void loadBook(String(item.id))} className={`w-full rounded-lg border p-3 text-left text-sm ${book?.id===item.id?'border-violet-500 bg-violet-500/15':'border-white/10'}`}>{label(item)}<small className="mt-1 block text-slate-500">{String(item.status||'DRAFT')}</small></button>)}</div></aside>
      <div className="min-w-0 rounded-xl border border-white/10 bg-[#0c121e] p-4">
        <div className="flex flex-wrap gap-2"><label className="flex items-center gap-2 text-xs text-slate-400">Content language<select className={input} value={contentLocale} onChange={event=>{const next=event.target.value as Locale;setContentLocale(next);if(page)setBlocks(hydrate(page.blocks,next));}}>{(['ru','uz','en'] as Locale[]).map(locale=><option key={locale}>{locale.toUpperCase()}</option>)}</select></label><button className={button} onClick={undo} disabled={!history.length}>Undo</button><button className={button} onClick={redo} disabled={!future.length}>Redo</button>{(['RICH_TEXT','IMAGE','SVG','FORMULA','INTERACTIVE_EXPERIMENT_LINK'] as Kind[]).map(k=><button key={k} className={button} onClick={()=>add(k)}>+ {k==='INTERACTIVE_EXPERIMENT_LINK'?'Experiment':k.replace('_',' ')}</button>)}<button className={button} onClick={()=>fileRef.current?.click()}>Upload image</button><button className={button} onClick={()=>svgRef.current?.click()}>Upload SVG</button><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e,'IMAGE')}/><input ref={svgRef} hidden type="file" accept="image/svg+xml" onChange={e=>void upload(e,'SVG')}/></div>
        <p className="my-3 text-xs text-slate-500">Drag blocks to move. Drag the lower-right handle to resize. Arrow keys nudge; Shift + arrow moves 10 px; Delete removes; Escape cancels.</p>
        <div className={`overflow-auto rounded-xl bg-[#202536] p-5 ${preview?'grid gap-2 md:grid-cols-2':''}`}>
          <div className="relative mx-auto h-[760px] w-[590px] overflow-hidden bg-[#fff9e9] text-slate-950 shadow-2xl" onPointerDown={()=>setSelected('')} aria-label="Book page canvas">
            {[...blocks].sort((a,b)=>a.z-b.z).map(b=><div key={b.id} role="button" tabIndex={0} aria-label={`${b.kind} block`} onPointerDown={e=>{e.stopPropagation();setSelected(b.id);drag.current={id:b.id,mode:'move',startX:e.clientX,startY:e.clientY,original:{...b}};}} className={`absolute overflow-hidden rounded p-2 ${selected===b.id?'outline outline-2 outline-violet-600':'hover:outline hover:outline-1 hover:outline-violet-300'}`} style={{left:b.x,top:b.y,width:b.w,height:b.h,zIndex:b.z}}>{renderBlock(b)}{selected===b.id&&<span aria-label="Resize block" onPointerDown={e=>{e.stopPropagation();drag.current={id:b.id,mode:'resize',startX:e.clientX,startY:e.clientY,original:{...b}};}} className="absolute bottom-0 right-0 h-5 w-5 cursor-se-resize rounded-tl bg-violet-600"/>}</div>)}
          </div>{preview&&<div className="relative mx-auto h-[760px] w-[590px] overflow-hidden bg-[#fff9e9] text-slate-950 shadow-2xl" aria-label="Next book page">{nextPage?nextBlocks.sort((a,b)=>a.z-b.z).map(block=><div key={block.id} className="absolute overflow-hidden rounded p-2" style={{left:block.x,top:block.y,width:block.w,height:block.h,zIndex:block.z}}>{renderBlock(block)}</div>):<div className="grid h-full place-items-center text-sm text-slate-400">End of book</div>}</div>}
        </div>
      </div>
      <aside className="space-y-4 rounded-xl border border-white/10 bg-[#0c121e] p-4"><div><h2 className="font-semibold">Chapters & pages</h2>{chapters.map((chapter,index)=><div key={String(chapter.id)} className="mt-3"><p className="text-xs font-semibold uppercase text-slate-500">{index+1}. {label(chapter)}</p>{items(chapter.pages).map(p=><button key={String(p.id)} onClick={()=>selectPage(p)} className={`mt-1 w-full rounded-lg px-3 py-2 text-left text-sm ${page?.id===p.id?'bg-violet-600':'bg-white/[.04]'}`}>{label(p)}</button>)}</div>)}</div>
        <div className="border-t border-white/10 pt-4"><h2 className="font-semibold">Selected block</h2>{!active?<p className="mt-2 text-sm text-slate-500">Select a block on the page.</p>:<div className="mt-3 space-y-3"><label className="block text-xs text-slate-400">Layer (z-index)<input className={input} type="number" value={active.z} onChange={e=>patchBlock(active.id,{z:n(e.target.value,1)})}/></label>{active.kind==='RICH_TEXT'&&<div><p className="mb-2 text-xs text-slate-400">Rich text content</p><RichTextEditor content={active.text||''} onChange={html=>patchBlock(active.id,{text:html},false)} onEditStart={()=>{if(!richTextStart.current)richTextStart.current=blocks.map(block=>({...block}));}} onEditEnd={()=>{const previous=richTextStart.current;if(previous){setHistory(h=>[...h,previous]);setFuture([]);richTextStart.current=null;}}}/></div>}{active.kind==='FORMULA'&&<label className="block text-xs text-slate-400">Formula<input className={input} value={active.formula} onChange={e=>patchBlock(active.id,{formula:e.target.value},false)}/></label>}{active.kind==='INTERACTIVE_EXPERIMENT_LINK'&&<label className="block text-xs text-slate-400">Published scenario<select className={input} value={active.scenarioId} onChange={e=>patchBlock(active.id,{scenarioId:e.target.value})}>{scenarios.map(s=><option key={String(s.id)} value={String(s.id)}>{label(s)}</option>)}</select></label>}<div className="grid grid-cols-2 gap-2"><button className={button} onClick={()=>patchBlock(active.id,{z:Math.max(...blocks.map(b=>b.z))+1})}>Bring front</button><button className={button} onClick={()=>patchBlock(active.id,{z:Math.min(...blocks.map(b=>b.z))-1})}>Send back</button></div><button className="w-full rounded-lg border border-rose-500/40 p-2 text-sm text-rose-300" onClick={()=>{commit(blocks.filter(b=>b.id!==active.id));setSelected('');}}>Delete block</button></div>}</div>
      </aside>
    </section>
    {interactiveDraft&&<div className="fixed inset-0 z-[300] bg-slate-950/90 p-4 backdrop-blur" role="dialog" aria-modal="true" aria-label="Interactive Scenario preview"><div className="mx-auto flex h-full max-w-[1500px] flex-col overflow-hidden rounded-2xl border border-violet-400/30 bg-[#080c14]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><p className="font-semibold">Interactive Scenario</p><p className="text-xs text-slate-400">Production Sandbox runtime · changes do not affect learner progress</p></div><button type="button" onClick={()=>setInteractiveDraft(null)} className={button}>Close</button></div><div className="min-h-0 flex-1"><SandboxWorkspace previewDraft={interactiveDraft} embedded/></div></div></div>}
  </main>;
}
