package com.ailab.chemistry.domain.simulationstate;

public enum SimulationStateErrorCode {
    SESSION_ALREADY_CREATED,
    EVENT_SEQUENCE_GAP,
    STALE_STATE_VERSION,
    IDEMPOTENCY_CONFLICT,
    TERMINAL_SESSION_IMMUTABLE,
    SESSION_NOT_RUNNING,
    STEP_DEPENDENCY_INCOMPLETE,
    STEP_NOT_RUNNING,
    MANDATORY_STEP_CANNOT_SKIP,
    EQUIPMENT_ALREADY_ALLOCATED,
    MATERIAL_QUANTITY_NEGATIVE,
    MATERIAL_TRANSFER_EXCEEDS_AVAILABLE,
    VESSEL_OVERFILL,
    CONTAINER_UNSUITABLE,
    EQUIPMENT_UNSUITABLE,
    UNKNOWN_EVENT_TYPE
}
