'use client';
import { Plus, Trash2 } from 'lucide-react';
import type { JsonObject } from '@/shared/api/contracts/platform';
import type { ScenarioConnection, ScenarioResourceSet, ScenarioScene } from '../scenario.types';
import { ScenarioSceneEditor } from './ScenarioSceneEditor';

const control = 'rounded-lg border border-white/10 bg-[#080c14] px-3 py-2 text-sm text-white';
const rows = (value: unknown): JsonObject[] => Array.isArray(value) ? value as JsonObject[] : [];

export function ScenarioScenePanel({ scene, resources, equipment, materials, onChange }: { scene: ScenarioScene; resources: ScenarioResourceSet; equipment: JsonObject[]; materials: JsonObject[]; onChange: (value: ScenarioScene) => void }) {
  const allowed = equipment.filter((item) => resources.equipmentIds.includes(String(item.id ?? item.code)));
  const equipmentForAlias = (alias: string) => { const sceneObject = scene.objects.find((item) => item.alias === alias); return equipment.find((item) => String(item.id ?? item.code) === sceneObject?.equipmentId); };
  const portsFor = (alias: string) => rows(equipmentForAlias(alias)?.ports);
  const patchConnection = (index: number, patch: Partial<ScenarioConnection>) => onChange({ ...scene, connections: scene.connections.map((connection, current) => current === index ? { ...connection, ...patch } : connection) });
  const add = (equipmentItem: JsonObject) => { const equipmentId = String(equipmentItem.id ?? equipmentItem.code); const base = String(equipmentItem.code ?? equipmentItem.rendererKey ?? 'object').toLowerCase().replace(/[^a-z0-9_]+/g, '_') || 'object'; let number = 1; while (scene.objects.some((item) => item.alias === `${base}_${number}`)) number += 1; onChange({ ...scene, objects: [...scene.objects, { id: crypto.randomUUID(), alias: `${base}_${number}`, equipmentId, x: 80 + scene.objects.length * 35, y: 100 + scene.objects.length * 25, width: 140, height: 140, rotation: 0, temperatureC: 24.5, contents: [] }] }); };
  return <div className="space-y-4">
    <section className="flex flex-wrap gap-2 rounded-xl border border-white/10 bg-[#0b101a] p-4"><span className="mr-2 text-sm text-slate-400">Add to initial scene:</span>{allowed.map((item) => <button type="button" key={String(item.id ?? item.code)} onClick={() => add(item)} className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm"><Plus size={13}/>{String(item.name ?? item.code)}</button>)}{!allowed.length && <span className="text-sm text-amber-300">Choose allowed equipment in Resources first.</span>}</section>
    <ScenarioSceneEditor scene={scene} equipment={equipment} materials={materials.filter((item) => resources.materialIds.includes(String(item.id ?? item.code)))} mode="ADMIN_AUTHORING" onChange={onChange}/>
    <section className="rounded-xl border border-white/10 bg-[#0b101a] p-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Initial connections</h3><p className="mt-1 text-xs text-slate-500">Prefer selecting two ports directly on the canvas. This form is an accessible alternative.</p></div><button type="button" aria-label="Add connection" onClick={() => onChange({ ...scene, connections: [...scene.connections, { id: crypto.randomUUID(), fromAlias: '', fromPortId: '', toAlias: '', toPortId: '' }] })} className="rounded bg-violet-600 p-2"><Plus size={14}/></button></div>
      <div className="mt-3 space-y-2">{scene.connections.map((link, index) => { const sourcePort = portsFor(link.fromAlias).find((port) => String(port.id) === link.fromPortId); const targetPort = portsFor(link.toAlias).find((port) => String(port.id) === link.toPortId); const compatible = !sourcePort || !targetPort || String(sourcePort.type ?? sourcePort.medium).toLowerCase() === String(targetPort.type ?? targetPort.medium).toLowerCase(); return <div key={link.id} className="rounded-lg border border-white/5 p-3"><div className="grid gap-2 md:grid-cols-[1fr_1fr_1fr_1fr_36px]"><select aria-label="Source object" className={control} value={link.fromAlias} onChange={(event) => patchConnection(index, { fromAlias: event.target.value, fromPortId: '' })}><option value="">From object</option>{scene.objects.map((item) => <option key={item.id}>{item.alias}</option>)}</select><select aria-label="Source port" className={control} value={link.fromPortId} onChange={(event) => patchConnection(index, { fromPortId: event.target.value })}><option value="">From port</option>{portsFor(link.fromAlias).map((port) => <option key={String(port.id)} value={String(port.id)}>{String(port.name ?? port.id)} · {String(port.type ?? '')}</option>)}</select><select aria-label="Destination object" className={control} value={link.toAlias} onChange={(event) => patchConnection(index, { toAlias: event.target.value, toPortId: '' })}><option value="">To object</option>{scene.objects.map((item) => <option key={item.id}>{item.alias}</option>)}</select><select aria-label="Destination port" className={control} value={link.toPortId} onChange={(event) => patchConnection(index, { toPortId: event.target.value })}><option value="">To port</option>{portsFor(link.toAlias).map((port) => <option key={String(port.id)} value={String(port.id)}>{String(port.name ?? port.id)} · {String(port.type ?? '')}</option>)}</select><button type="button" aria-label="Remove connection" onClick={() => onChange({ ...scene, connections: scene.connections.filter((_, current) => current !== index) })}><Trash2 size={14}/></button></div>{sourcePort && targetPort && <p className={`mt-2 text-xs ${compatible ? 'text-emerald-300' : 'text-rose-300'}`}>{compatible ? 'Compatible port medium.' : 'Cannot connect: port medium mismatch.'}</p>}</div>; })}</div>
    </section>
  </div>;
}
