'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Copy, Focus, Grid3X3, Minus, Plus, Redo2, RotateCcw, Trash2, Undo2 } from 'lucide-react';
import { renderEquipmentCanvas } from '@/entities/equipment/ui/EquipmentRendererRegistry';
import { resolvePortScreenPosition, resolvePortWorldPosition } from '@/entities/equipment/lib/equipmentRenderBounds';
import { convertRuntimeUnit } from '@/widgets/sandbox/runtime/unitConversion';
import type { JsonObject } from '@/shared/api/contracts/platform';
import type { ScenarioCanvasMode, ScenarioConnection, ScenarioScene, ScenarioSceneObject } from '../scenario.types';

const object = (value: unknown): JsonObject => value && typeof value === 'object' && !Array.isArray(value) ? value as JsonObject : {};
const rows = (value: unknown): JsonObject[] => Array.isArray(value) ? value as JsonObject[] : [];
const control = 'w-full rounded-lg border border-white/10 bg-[#080c14] px-3 py-2 text-sm text-white';
export type RecordedPort = { alias: string; portId: string };
type PortSelection = RecordedPort & { type: string };

export function ScenarioSceneEditor({ scene, equipment, materials, mode, onChange, onRecordPort, highlight }: { scene: ScenarioScene; equipment: JsonObject[]; materials: JsonObject[]; mode: ScenarioCanvasMode; onChange?: (value: ScenarioScene) => void; onRecordPort?: (value: RecordedPort) => void; highlight?: RecordedPort | null }) {
  const [selected, setSelected] = useState(''); const [zoom, setZoom] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const [grid, setGrid] = useState(true); const [snap, setSnap] = useState(true); const [connectFrom, setConnectFrom] = useState<PortSelection | null>(null);
  const drag = useRef<{ id: string; x: number; y: number; ox: number; oy: number } | null>(null); const panDrag = useRef<{ x: number; y: number; ox: number; oy: number } | null>(null);
  const past = useRef<ScenarioScene[]>([]); const future = useRef<ScenarioScene[]>([]); const [, setHistoryVersion] = useState(0);
  const editable = mode === 'ADMIN_AUTHORING' && Boolean(onChange); const byAlias = useMemo(() => new Map(scene.objects.map((item) => [item.alias, item])), [scene.objects]);
  const equipmentFor = (id: string) => equipment.find((item) => String(item.id ?? item.code) === id); const portFor = (item: ScenarioSceneObject, portId: string) => rows(equipmentFor(item.equipmentId)?.ports).find((port) => String(port.id) === portId);
  const worldPoint = (item: ScenarioSceneObject, port: JsonObject) => resolvePortWorldPosition({ x: Number(object(port.position).x ?? .5), y: Number(object(port.position).y ?? .5) }, { x: item.x, y: item.y, width: item.width, height: item.height, rotation: item.rotation });
  const connections = scene.connections.map((link) => { const from = byAlias.get(link.fromAlias), to = byAlias.get(link.toAlias), fromPort = from ? portFor(from, link.fromPortId) : undefined, toPort = to ? portFor(to, link.toPortId) : undefined; return from && to && fromPort && toPort ? { link, from: worldPoint(from, fromPort), to: worldPoint(to, toPort) } : null; }).filter(Boolean) as Array<{ link: ScenarioConnection; from: { x: number; y: number }; to: { x: number; y: number } }>;
  const commit = (next: ScenarioScene) => { if (!editable || JSON.stringify(next) === JSON.stringify(scene)) return; past.current.push(scene); if (past.current.length > 100) past.current.shift(); future.current = []; onChange?.(next); setHistoryVersion((value) => value + 1); };
  const undo = () => { const previous = past.current.pop(); if (!previous || !editable) return; future.current.push(scene); onChange?.(previous); setHistoryVersion((value) => value + 1); };
  const redo = () => { const next = future.current.pop(); if (!next || !editable) return; past.current.push(scene); onChange?.(next); setHistoryVersion((value) => value + 1); };
  useEffect(() => { if (!editable) return; const key = (event: KeyboardEvent) => { if (!(event.ctrlKey || event.metaKey) || event.key.toLowerCase() !== 'z') return; event.preventDefault(); if (event.shiftKey) redo(); else undo(); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); });
  const patch = (id: string, next: Partial<ScenarioSceneObject>) => commit({ ...scene, objects: scene.objects.map((item) => item.id === id ? { ...item, ...next } : item) });
  const rename = (item: ScenarioSceneObject, alias: string) => commit({ ...scene, objects: scene.objects.map((candidate) => candidate.id === item.id ? { ...candidate, alias } : candidate), connections: scene.connections.map((link) => ({ ...link, fromAlias: link.fromAlias === item.alias ? alias : link.fromAlias, toAlias: link.toAlias === item.alias ? alias : link.toAlias })) });
  const fit = () => { if (!scene.objects.length) { setZoom(1); setPan({ x: 0, y: 0 }); return; } const minX = Math.min(...scene.objects.map((item) => item.x)), minY = Math.min(...scene.objects.map((item) => item.y)), maxX = Math.max(...scene.objects.map((item) => item.x + item.width)), maxY = Math.max(...scene.objects.map((item) => item.y + item.height)); const nextZoom = Math.max(.5, Math.min(1.5, Math.min(900 / Math.max(1, maxX - minX + 120), 520 / Math.max(1, maxY - minY + 120)))); setZoom(nextZoom); setPan({ x: 60 - minX * nextZoom, y: 40 - minY * nextZoom }); };
  const choosePort = (item: ScenarioSceneObject, port: JsonObject) => { const next = { alias: item.alias, portId: String(port.id), type: String(port.type ?? port.medium ?? '') }; if (onRecordPort) { onRecordPort(next); return; } if (!editable) return; if (!connectFrom) { setConnectFrom(next); return; } const compatible = !connectFrom.type || !next.type || connectFrom.type.toLowerCase() === next.type.toLowerCase(); if (connectFrom.alias !== next.alias && compatible) commit({ ...scene, connections: [...scene.connections, { id: crypto.randomUUID(), fromAlias: connectFrom.alias, fromPortId: connectFrom.portId, toAlias: next.alias, toPortId: next.portId }] }); setConnectFrom(null); };
  const active = scene.objects.find((item) => item.id === selected);
  return <div className="grid gap-4 xl:grid-cols-[1fr_300px]">
    <div className="overflow-hidden rounded-xl border border-white/10 bg-[#080c14]">
      {editable && <div className="flex gap-2 border-b border-white/10 px-2 pt-2"><button type="button" aria-label="Undo scene change" title="Undo · Ctrl+Z" disabled={!past.current.length} onClick={undo} className="rounded border border-white/10 p-1.5 disabled:opacity-30"><Undo2 size={15}/></button><button type="button" aria-label="Redo scene change" title="Redo · Ctrl+Shift+Z" disabled={!future.current.length} onClick={redo} className="rounded border border-white/10 p-1.5 disabled:opacity-30"><Redo2 size={15}/></button><span className="self-center text-[11px] text-slate-500">Scene history · up to 100 changes</span></div>}
      <div className="flex flex-wrap items-center gap-2 border-b border-white/10 p-2"><button type="button" aria-label="Zoom out" onClick={() => setZoom((value) => Math.max(.5, value - .1))}><Minus size={15}/></button><span className="min-w-12 text-center text-xs">{Math.round(zoom * 100)}%</span><button type="button" aria-label="Zoom in" onClick={() => setZoom((value) => Math.min(2, value + .1))}><Plus size={15}/></button><button type="button" onClick={fit} className="flex items-center gap-1 rounded border border-white/10 px-2 py-1 text-xs"><Focus size={14}/>Fit</button><button type="button" onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }} className="flex items-center gap-1 rounded border border-white/10 px-2 py-1 text-xs"><RotateCcw size={14}/>Reset</button><button type="button" aria-pressed={grid} onClick={() => setGrid((value) => !value)} className={`flex items-center gap-1 rounded border px-2 py-1 text-xs ${grid ? 'border-cyan-400/50 text-cyan-200' : 'border-white/10'}`}><Grid3X3 size={14}/>Grid</button><button type="button" aria-pressed={snap} onClick={() => setSnap((value) => !value)} className={`rounded border px-2 py-1 text-xs ${snap ? 'border-violet-400/50 text-violet-200' : 'border-white/10'}`}>Snap</button>{connectFrom && <button type="button" onClick={() => setConnectFrom(null)} className="rounded border border-amber-300/40 px-2 py-1 text-xs text-amber-200">Connecting {connectFrom.alias}.{connectFrom.portId} · Cancel</button>}<span className="ml-auto text-xs text-slate-500">{mode.replace('_', ' ')}</span></div>
      <div className={`relative h-[600px] overflow-hidden ${grid ? 'bg-[radial-gradient(circle,rgba(148,163,184,.22)_1px,transparent_1px)] bg-[size:24px_24px]' : ''}`} onWheel={(event) => { if (event.ctrlKey) { event.preventDefault(); setZoom((value) => Math.max(.5, Math.min(2, value - event.deltaY * .001))); } else setPan((value) => ({ x: value.x - event.deltaX, y: value.y - event.deltaY })); }} onPointerDown={(event) => { if (event.button === 1 || event.altKey) { panDrag.current = { x: event.clientX, y: event.clientY, ox: pan.x, oy: pan.y }; event.currentTarget.setPointerCapture(event.pointerId); } else { setSelected(''); setConnectFrom(null); } }} onPointerMove={(event) => { const moving = drag.current; if (moving && editable) { const rawX = moving.ox + (event.clientX - moving.x) / zoom, rawY = moving.oy + (event.clientY - moving.y) / zoom; patch(moving.id, { x: snap ? Math.round(rawX / 24) * 24 : rawX, y: snap ? Math.round(rawY / 24) * 24 : rawY }); } const viewport = panDrag.current; if (viewport) setPan({ x: viewport.ox + event.clientX - viewport.x, y: viewport.oy + event.clientY - viewport.y }); }} onPointerUp={() => { drag.current = null; panDrag.current = null; }}>
        <div className="absolute inset-0 origin-top-left" style={{ transform: `translate(${pan.x}px,${pan.y}px) scale(${zoom})` }}><svg className="pointer-events-none absolute inset-0 h-full w-full overflow-visible">{connections.map(({ link, from, to }) => <line key={link.id} x1={from.x} y1={from.y} x2={to.x} y2={to.y} stroke="#22d3ee" strokeWidth="3" strokeDasharray="7 4"/>)}</svg>
          {scene.objects.map((item) => { const catalog = equipmentFor(item.equipmentId), ports = rows(catalog?.ports), content = item.contents[0], material = materials.find((entry) => String(entry.id ?? entry.code) === content?.materialId), color = String(object(material?.appearance).color ?? '#22d3ee'), volumeMl = content ? convertRuntimeUnit(content.amount, content.unit, 'mL') ?? 0 : 0; return <div key={item.id} className={`absolute group ${selected === item.id ? 'ring-2 ring-violet-400' : ''}`} style={{ left: item.x, top: item.y, width: item.width, height: item.height, transform: `rotate(${item.rotation}deg)` }} onPointerDown={(event) => { if (!editable) return; event.stopPropagation(); setSelected(item.id); drag.current = { id: item.id, x: event.clientX, y: event.clientY, ox: item.x, oy: item.y }; }}><div className="pointer-events-none absolute inset-0 grid place-items-center">{renderEquipmentCanvas(String(catalog?.rendererKey ?? 'beaker'), { type: String(catalog?.rendererKey ?? 'beaker'), width: item.width, height: item.height, size: Math.min(item.width, item.height), liquidLevel: Math.min(1, volumeMl / 250), liquidColor: color, temperature: item.temperatureC })}</div>{ports.map((port) => { const position = resolvePortScreenPosition({ x: Number(object(port.position).x ?? .5), y: Number(object(port.position).y ?? .5) }), isHighlight = highlight?.alias === item.alias && highlight.portId === String(port.id), isSource = connectFrom?.alias === item.alias && connectFrom.portId === String(port.id); return <button key={String(port.id)} type="button" title={`${item.alias}.${String(port.id)} · ${String(port.type ?? '')}`} onPointerDown={(event) => { event.stopPropagation(); choosePort(item, port); }} className={`absolute z-20 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white bg-cyan-500 ${isHighlight || isSource ? 'animate-pulse ring-4 ring-amber-300/50' : 'opacity-30 group-hover:opacity-100'}`} style={{ left: `${position.x * 100}%`, top: `${position.y * 100}%` }}/>; })}<span className="absolute -bottom-5 left-1/2 -translate-x-1/2 rounded bg-black/70 px-2 text-[10px]">{item.alias}</span></div>; })}
        </div>
      </div>
    </div>
    <aside className="rounded-xl border border-white/10 bg-[#0b101a] p-4">{active && editable ? <div className="space-y-3"><h3 className="font-semibold">Object inspector</h3><label className="block text-xs">Alias<input className={control} value={active.alias} onChange={(event) => rename(active, event.target.value.replace(/\W+/g, '_'))}/></label><label className="block text-xs">Rotation<input className={control} type="number" value={active.rotation} onChange={(event) => patch(active.id, { rotation: Number(event.target.value) })}/></label><label className="block text-xs">Temperature °C<input className={control} type="number" value={active.temperatureC} onChange={(event) => patch(active.id, { temperatureC: Number(event.target.value) })}/></label>
      <div className="space-y-2 border-t border-white/10 pt-3"><div className="flex items-center justify-between"><h4 className="text-xs font-semibold uppercase tracking-wide text-slate-400">Contents</h4><button type="button" onClick={() => patch(active.id, { contents: [...active.contents, { materialId: '', amount: 10, unit: 'mL', phase: 'LIQUID' }] })} className="text-xs text-cyan-300">Add</button></div>{active.contents.map((content, index) => <div key={`${content.materialId}-${index}`} className="grid grid-cols-[minmax(0,1fr)_72px_76px_92px_34px] gap-2"><select aria-label="Content Material" className={control} value={content.materialId} onChange={(event) => patch(active.id, { contents: active.contents.map((entry, itemIndex) => itemIndex === index ? { ...entry, materialId: event.target.value } : entry) })}><option value="">Select material</option>{materials.map((entry) => <option key={String(entry.id ?? entry.code)} value={String(entry.id ?? entry.code)}>{String(entry.name ?? entry.code ?? entry.id)}</option>)}</select><input aria-label="Content amount" className={control} type="number" min="0" value={content.amount} onChange={(event) => patch(active.id, { contents: active.contents.map((entry, itemIndex) => itemIndex === index ? { ...entry, amount: Number(event.target.value) } : entry) })}/><select aria-label="Content unit" className={control} value={content.unit} onChange={(event) => patch(active.id, { contents: active.contents.map((entry, itemIndex) => itemIndex === index ? { ...entry, unit: event.target.value as typeof entry.unit } : entry) })}>{['µL','mL','L','mg','g','kg','mmol','mol'].map((unit) => <option key={unit}>{unit}</option>)}</select><select aria-label="Content phase" className={control} value={content.phase} onChange={(event) => patch(active.id, { contents: active.contents.map((entry, itemIndex) => itemIndex === index ? { ...entry, phase: event.target.value } : entry) })}>{['SOLID','LIQUID','AQUEOUS','GAS'].map((phase) => <option key={phase}>{phase}</option>)}</select><button type="button" aria-label="Remove content" onClick={() => patch(active.id, { contents: active.contents.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={14}/></button></div>)}</div>
      <div className="space-y-2 border-t border-white/10 pt-3"><p className="mb-2 text-xs text-slate-400">Select two compatible ports on the canvas to connect them.</p><button type="button" onClick={() => { let number = 2; const root = active.alias.replace(/_\d+$/, ''); while (scene.objects.some((item) => item.alias === `${root}_${number}`)) number += 1; const duplicate = { ...active, id: crypto.randomUUID(), alias: `${root}_${number}`, x: active.x + 24, y: active.y + 24, contents: active.contents.map((content) => ({ ...content })) }; commit({ ...scene, objects: [...scene.objects, duplicate] }); setSelected(duplicate.id); }} className="flex items-center gap-2 text-sm text-cyan-300"><Copy size={14}/>Duplicate object</button><button type="button" onClick={() => commit({ ...scene, objects: scene.objects.filter((item) => item.id !== active.id), connections: scene.connections.filter((link) => link.fromAlias !== active.alias && link.toAlias !== active.alias) })} className="flex items-center gap-2 text-sm text-rose-300"><Trash2 size={14}/>Remove object and dependencies</button></div></div> : <p className="text-sm text-slate-500">{editable ? 'Select an object to edit its state. Alt-drag or use the middle mouse button to pan.' : 'Preview uses the saved scene, contents, and connections.'}</p>}</aside>
  </div>;
}
