package com.ailab.chemistry.domain.equation.exception;

public enum EquationErrorCode {
    EMPTY_EQUATION,
    MISSING_REACTANT,
    MISSING_PRODUCT,
    INVALID_EQUATION_SEPARATOR,
    UNBALANCEABLE_EQUATION,
    NON_POSITIVE_SOLUTION,
    MULTIPLE_INDEPENDENT_SOLUTIONS,
    CHARGE_NOT_CONSERVED,
    AMBIGUOUS_EQUATION_TOKENIZATION
}
