'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, Loader2, Plus, RefreshCw, Search } from 'lucide-react';
import { useLocale } from 'next-intl';
import { useRouter } from 'next/navigation';
import { adminPlatformApi } from '@/entities/admin/api/platform-admin.api';
import type { JsonObject } from '@/shared/api/contracts/platform';
import { CONTENT_LOCALES, type Locale } from '@/shared/types/catalog';
import { errorMessage } from '@/shared/utils/errorMessage';
import AdminPageHeader from '@/widgets/admin/AdminPageHeader';
import { StatusBadge } from '@/widgets/admin/editor';
import { getLocalizationCompleteness, LocalizationStatusBadge } from '@/widgets/admin/localization';

const object = (value: unknown): JsonObject => value && typeof value === 'object' && !Array.isArray(value) ? value as JsonObject : {};
const name = (row: JsonObject, locale: Locale) => { const legacy=object(row.translations)[locale]; const value=object(legacy); return String(value.name ?? (typeof legacy === 'string' ? legacy : '')).trim() || '—'; };
const translations = (row: JsonObject) => Object.fromEntries(CONTENT_LOCALES.map(locale => { const value=object(row.translations)[locale]; return [locale,typeof value === 'string' ? {name:value} : object(value)]; }));
const select = 'rounded-lg border border-white/10 bg-[#101624] px-3 py-2 text-sm text-slate-200 outline-none focus:border-violet-400';

export default function MaterialList() {
  const locale=useLocale() as Locale;
  const router=useRouter();
  const [rows,setRows]=useState<JsonObject[]>([]);
  const [query,setQuery]=useState(''); const [status,setStatus]=useState(''); const [kind,setKind]=useState(''); const [phase,setPhase]=useState('');
  const [page,setPage]=useState(0); const [total,setTotal]=useState(0); const [totalPages,setTotalPages]=useState(1);
  const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const resetPage=(change:()=>void)=>{setPage(0);change();};
  const load=useCallback(async()=>{setLoading(true);try{const response=await adminPlatformApi.materials.list({q:query||undefined,status:status||undefined,type:kind||undefined,phase:phase||undefined,page,size:25,sort:'updatedAt,desc'});const items=response.items??response.content??[];setRows(items);setTotal(Number(response.totalElements??response.total??items.length));setTotalPages(Math.max(1,Number(response.totalPages??1)));setError('');}catch(reason){setError(errorMessage(reason,'Unable to load materials.'));}finally{setLoading(false);}},[kind,page,phase,query,status]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer);},[load]);
  const visible=useMemo(()=>rows,[rows]);
  return <div className="space-y-6 pb-12">
    <AdminPageHeader title="Materials & samples" description="Structured chemistry records used by the real Sandbox." counters={[{label:'Records',value:total},{label:'Visible on page',value:visible.length}]} actions={<div className="flex gap-2"><Link href={`/${locale}/admin/materials/new`} className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white"><Plus size={15}/>New material</Link><button type="button" aria-label="Refresh" onClick={()=>void load()} className="grid h-10 w-10 place-items-center rounded-lg border border-white/10"><RefreshCw size={15}/></button></div>}/>
    <div className="flex flex-wrap gap-3"><label className="relative min-w-[260px] flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={15}/><input aria-label="Search materials" className="w-full rounded-lg border border-white/10 bg-[#101624] py-2 pl-9 pr-3 text-sm outline-none focus:border-violet-400" value={query} onChange={event=>resetPage(()=>setQuery(event.target.value))} placeholder="Search code, formula, or name"/></label><select aria-label="Status" className={select} value={status} onChange={event=>resetPage(()=>setStatus(event.target.value))}><option value="">All statuses</option>{['DRAFT','PUBLISHED','ARCHIVED'].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Kind" className={select} value={kind} onChange={event=>resetPage(()=>setKind(event.target.value))}><option value="">All kinds</option>{['ELEMENT','COMPOUND','MIXTURE','SOLUTION','SAMPLE','OTHER'].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Phase" className={select} value={phase} onChange={event=>resetPage(()=>setPhase(event.target.value))}><option value="">All phases</option>{['SOLID','LIQUID','GAS','PLASMA','AQUEOUS','UNKNOWN'].map(value=><option key={value}>{value}</option>)}</select></div>
    {error&&<div role="alert" className="flex items-center gap-3 rounded-xl border border-rose-500/20 bg-rose-500/10 p-4 text-sm text-rose-200"><AlertCircle size={17}/><span className="flex-1">{error}</span><button type="button" onClick={()=>void load()} className="underline">Retry</button></div>}
    {loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-violet-400"/></div>:visible.length===0?<div className="rounded-2xl border border-dashed border-white/10 p-14 text-center text-sm text-slate-500">No materials found.</div>:<div className="overflow-hidden rounded-2xl border border-white/[.07] bg-[#0b101a]"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-white/[.07] bg-white/[.02] text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Appearance</th><th className="px-4 py-3">Name</th><th className="px-4 py-3">Formula</th><th className="px-4 py-3">Kind / phase</th><th className="px-4 py-3">Localization</th><th className="px-4 py-3">Safety</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{visible.map(row=>{const id=String(row.id??row.code);const appearance=object(row.appearance);const complete=getLocalizationCompleteness(translations(row),['name']);return <tr key={id} tabIndex={0} onClick={()=>router.push(`/${locale}/admin/materials/${id}`)} onKeyDown={event=>event.key==='Enter'&&router.push(`/${locale}/admin/materials/${id}`)} className="cursor-pointer border-b border-white/[.05] last:border-0 hover:bg-white/[.035]"><td className="px-4 py-3"><span className="block h-10 w-10 rounded-full border border-white/30 shadow-inner" style={{background:String(appearance.color??'#22d3ee'),opacity:Number(appearance.opacity??1)}}/></td><td className="px-4 py-3"><strong className="block text-white">{name(row,locale)}</strong><code className="mt-1 block text-[11px] text-slate-500">{String(row.code??'—')}</code></td><td className="px-4 py-3 font-mono text-cyan-200">{String(row.formula??'—')}</td><td className="px-4 py-3">{String(row.type??row.kind??'—')}<span className="block text-[10px] text-slate-500">{String(row.phase??'—')}</span></td><td className="px-4 py-3"><div className="flex gap-2">{CONTENT_LOCALES.map(value=><LocalizationStatusBadge key={value} locale={value} status={complete[value]}/>)}</div></td><td className="px-4 py-3 text-xs text-amber-200">{String(object(row.safety).hazard??'—')}</td><td className="px-4 py-3"><StatusBadge status={String(row.status??'DRAFT')}/></td></tr>;})}</tbody></table></div></div>}
    {totalPages>1&&<nav aria-label="Material pages" className="flex items-center justify-between rounded-xl border border-white/[.07] bg-[#0b101a] px-4 py-3 text-sm"><span className="text-slate-400">Page {page+1} of {totalPages} · {total} records</span><div className="flex gap-2"><button type="button" disabled={page===0} onClick={()=>setPage(current=>Math.max(0,current-1))} className="rounded-lg border border-white/10 px-3 py-1.5 disabled:opacity-40">Previous</button><button type="button" disabled={page+1>=totalPages} onClick={()=>setPage(current=>current+1)} className="rounded-lg border border-white/10 px-3 py-1.5 disabled:opacity-40">Next</button></div></nav>}
  </div>;
}
