import type { JsonObject } from '@/shared/api/contracts/platform';
import { CONTENT_LOCALES, type Locale } from '@/shared/types/catalog';
import type { MaterialDraft, MaterialSafety, MaterialTranslation, MaterialValidationIssue } from './materialEditor.types';

const protectedKeys = new Set(['id','entityType','status','version','publishedVersion','publishedAt','createdAt','updatedAt']);
const object = (value: unknown): JsonObject => value && typeof value === 'object' && !Array.isArray(value) ? value as JsonObject : {};
const str = (value: unknown, fallback = '') => typeof value === 'string' ? value : fallback;
const num = (value: unknown) => typeof value === 'number' && Number.isFinite(value) ? value : null;
const translation = (value: unknown): MaterialTranslation => { const item = typeof value === 'string' ? { name: value } : object(value); return { name: str(item.name ?? item.title), shortDescription: str(item.shortDescription ?? item.summary), detailedDescription: str(item.detailedDescription ?? item.description), usageDescription: str(item.usageDescription), safetyInformation: str(item.safetyInformation), educationalNotes: str(item.educationalNotes) }; };
const unit = (value: unknown, unitName: string) => { const item = object(value); return { value: num(item.value ?? value), unit: str(item.unit, unitName) }; };
const safety = (value: unknown): MaterialSafety => { const item = object(value); return { hazard: str(item.hazard, 'NONE'), severity: str(item.severity, 'NONE'), signalWord: str(item.signalWord), ppe: Array.isArray(item.ppe) ? item.ppe.map(String) : [], handling: str(item.handling), storage: str(item.storage), firstAid: str(item.firstAid), disposal: str(item.disposal), incompatibilities: Array.isArray(item.incompatibilities) ? item.incompatibilities.map(String) : [] }; };

export function createMaterialDraft(record: JsonObject = {}): MaterialDraft {
  const props = object(record.properties); const appearance = object(record.appearance); const reactions = Array.isArray(record.reactionRelationships) ? record.reactionRelationships : []; const links = object(record.links); const wikipedia = object(links.wikipedia);
  return { id: str(record.id) || undefined, code: str(record.code), internalName: str(record.name), formula: str(record.formula), kind: str(record.type ?? record.kind, 'COMPOUND') as MaterialDraft['kind'], phase: str(record.phase, 'UNKNOWN') as MaterialDraft['phase'], tags: Array.isArray(record.tags) ? record.tags.map(String) : [], status: str(record.status, 'DRAFT'), version: num(record.version) ?? undefined, publishedVersion: num(record.publishedVersion), translations: Object.fromEntries(CONTENT_LOCALES.map(locale => [locale, translation(object(record.translations)[locale])])) as Record<Locale, MaterialTranslation>, appearance: { color: str(appearance.color, '#22d3ee'), opacity: Math.max(0, Math.min(1, num(appearance.opacity) ?? .72)), texture: str(appearance.texture, 'CLEAR'), particleColor: str(appearance.particleColor, str(appearance.color, '#22d3ee')) }, properties: { casNumber: str(props.casNumber), molarMass: unit(props.molarMass, 'g/mol'), density: unit(props.density, 'g/mL'), meltingPoint: unit(props.meltingPoint ?? props.meltingPointC, '°C'), boilingPoint: unit(props.boilingPoint ?? props.boilingPointC, '°C'), solubility: unit(props.solubility, 'g/L'), concentrationM: num(props.concentrationM), ph: num(props.ph) }, safety: safety(record.safety), reactionRelationships: reactions.map(value => { const item = object(value); return { reactionId: str(item.reactionId ?? item.id), role: str(item.role, 'REACTANT') as MaterialDraft['reactionRelationships'][number]['role'], notes: str(item.notes) }; }), links: { bookId: str(links.bookId), chapterId: str(links.chapterId), pageId: str(links.pageId), wikipedia: Object.fromEntries(CONTENT_LOCALES.map(locale => [locale, str(wikipedia[locale])])), references: Array.isArray(links.references) ? links.references.map((value,index) => { const item=object(value); return { id:str(item.id,`reference-${index}`), label:str(item.label), url:str(item.url), locale:str(item.locale) as Locale|'' }; }) : [] }, raw: Object.fromEntries(Object.entries(record).filter(([key]) => !protectedKeys.has(key))) }; }
export function materialPayload(draft: MaterialDraft): JsonObject { return { ...draft.raw, code: draft.code.trim(), name: draft.internalName.trim(), formula: draft.formula.trim(), type: draft.kind, phase: draft.phase, tags: draft.tags, translations: draft.translations, appearance: draft.appearance, properties: { casNumber: draft.properties.casNumber.trim(), molarMass: draft.properties.molarMass, density: draft.properties.density, meltingPoint: draft.properties.meltingPoint, boilingPoint: draft.properties.boilingPoint, solubility: draft.properties.solubility, concentrationM: draft.properties.concentrationM, ph: draft.properties.ph }, safety: draft.safety, reactionRelationships: draft.reactionRelationships.filter(item => item.reactionId.trim()).map(item => ({ ...item, reactionId: item.reactionId.trim() })), links: draft.links }; }
export function validateMaterial(draft: MaterialDraft): MaterialValidationIssue[] { const issues: MaterialValidationIssue[] = []; if (!draft.code.trim()) issues.push({ id: 'material-code', severity: 'error', tab: 'details', message: 'Stable material code is required.' }); if (!draft.formula.trim()) issues.push({ id: 'material-formula', severity: 'warning', tab: 'chemistry', message: 'Chemical formula is missing.' }); CONTENT_LOCALES.forEach(locale => { const value = draft.translations[locale]; if (!value?.name.trim()) issues.push({ id: `translation-${locale}-name`, severity: 'error', tab: 'localization', message: `${locale.toUpperCase()} name is missing.` }); }); if (!/^#[0-9a-f]{6}$/i.test(draft.appearance.color)) issues.push({ id: 'appearance-color', severity: 'error', tab: 'appearance', message: 'Appearance color must be a hex color.' }); if (draft.properties.ph != null && (draft.properties.ph < 0 || draft.properties.ph > 14)) issues.push({ id: 'material-ph', severity: 'error', tab: 'chemistry', message: 'pH must be between 0 and 14.' }); if (draft.safety.hazard !== 'NONE' && !draft.safety.ppe.length) issues.push({ id: 'safety-ppe', severity: 'warning', tab: 'safety', message: 'Hazardous materials should specify PPE.' }); return issues; }
