package com.ailab.chemistry.domain.acidbase;

public enum AcidBaseErrorCode {
    SPECIES_NOT_FOUND,
    CONJUGATE_PAIR_NOT_FOUND,
    INVALID_SPECIES_FORMULA,
    CHARGE_MISMATCH,
    INVALID_PROTON_DIFFERENCE,
    INVALID_EQUILIBRIUM_CONSTANT,
    ORDERED_STEP_MISMATCH,
    MISSING_REFERENCE_CONDITIONS,
    UNSUPPORTED_SOLVENT,
    STRONG_ELECTROLYTE_NO_CONSTANT,
    DATASET_ERROR
}
