package com.ailab.chemistry.domain.acidbase;

public enum ActivityErrorCode {
    NEGATIVE_CONCENTRATION,
    INVALID_SPECIES_CHARGE,
    NON_POSITIVE_PARAMETER,
    UNSUPPORTED_SOLVENT,
    UNSUPPORTED_TEMPERATURE,
    MISSING_PARAMETER_SET,
    OUTSIDE_MODEL_VALIDITY_RANGE,
    NON_FINITE_ACTIVITY_COEFFICIENT,
    UNSUPPORTED_EQUILIBRIUM_SYSTEM,
    SOLVER_CONVERGENCE_FAILED
}
