package com.ailab.chemistry.domain.acidbase;

public enum BufferRegionStatus {
    VALID_BUFFER,
    OUTSIDE_RECOMMENDED_BUFFER_RANGE,
    ACID_COMPONENT_EXHAUSTED,
    BASE_COMPONENT_EXHAUSTED,
    EXACT_EXHAUSTION,
    EXCESS_STRONG_ACID_UNSUPPORTED,
    EXCESS_STRONG_BASE_UNSUPPORTED,
    INSUFFICIENT_REFERENCE_DATA
}
