package com.ailab.chemistry.domain.acidbase;

public enum BufferAssumption {
    AQUEOUS_SOLVENT,
    IDEAL_SOLUTION,
    MONOPROTIC_CONJUGATE_PAIR,
    HENDERSON_HASSELBALCH_APPLICABILITY,
    COMPONENT_MOLE_RATIO_USED,
    TEMPERATURE_SPECIFIC_CONSTANTS,
    NO_ACTIVITY_COEFFICIENT_CORRECTION,
    NO_VOLUME_CHANGE_ON_REACTION
}
