package com.ailab.chemistry.domain.acidbase;

public enum BufferErrorCode {
    INVALID_CONJUGATE_PAIR,
    INVALID_CONJUGATE_PAIR_ORIENTATION,
    INSUFFICIENT_REFERENCE_DATA,
    UNSUPPORTED_SOLVENT,
    MISSING_TEMPERATURE,
    NON_POSITIVE_COMPONENT_AMOUNT,
    NON_POSITIVE_VOLUME,
    INVALID_FINAL_VOLUME,
    NON_POSITIVE_TOTAL_CONCENTRATION,
    NUMERICALLY_UNSAFE_REQUEST,
    POLYPROTIC_BUFFER_UNSUPPORTED,
    ACTIVITY_COEFFICIENT_CORRECTION_UNSUPPORTED
}
