package com.ailab.chemistry.domain.acidbase;

public enum BufferCalculationMethod {
    HENDERSON_HASSELBALCH,
    TARGET_RATIO_HENDERSON_HASSELBALCH,
    IDEAL_PROPORTIONAL_DILUTION,
    STOICHIOMETRIC_NEUTRALIZATION_THEN_HENDERSON_HASSELBALCH,
    EXACT_EXHAUSTION_DELEGATED_TO_PHASE_7D,
    UNSUPPORTED_MIXED_STRONG_WEAK_EQUILIBRIUM
}
