package com.ailab.chemistry.domain.acidbase;

public enum PolyproticAssumption {
    AQUEOUS_SOLVENT,
    IDEAL_SOLUTION,
    TEMPERATURE_SPECIFIC_CONSTANTS,
    WATER_AUTOIONIZATION_INCLUDED,
    MASS_BALANCE_ENFORCED,
    CHARGE_BALANCE_ENFORCED,
    NO_ACTIVITY_COEFFICIENT_CORRECTION,
    FIRST_DISSOCIATION_COMPLETE
}
