package com.ailab.chemistry.domain.acidbase;

public enum PolyproticTitrationErrorCode {
    INSUFFICIENT_REFERENCE_DATA,
    UNSUPPORTED_FAMILY,
    UNSUPPORTED_SOLVENT,
    NON_POSITIVE_CONCENTRATION,
    NON_POSITIVE_VOLUME,
    NEGATIVE_TITRANT_VOLUME,
    DUPLICATE_TITRANT_VOLUME,
    INVALID_SPECTATOR_ION,
    INVALID_SYSTEM_TYPE,
    NUMERICALLY_UNSAFE_REQUEST,
    SOLVER_CONVERGENCE_FAILED
}
