package com.ailab.chemistry.domain.acidbase;

public enum PolyproticErrorCode {
    UNSUPPORTED_SOLVENT,
    MISSING_TEMPERATURE,
    INSUFFICIENT_REFERENCE_DATA,
    NON_POSITIVE_CONCENTRATION,
    INVALID_INITIAL_FORM,
    MISSING_SPECTATOR_ION,
    INVALID_SPECTATOR_STOICHIOMETRY,
    MISSING_KA_STEP,
    NONCONTIGUOUS_DISSOCIATION_STEPS,
    MIXED_REFERENCE_CONDITIONS,
    INVALID_DISTRIBUTION_FRACTION,
    SOLVER_CONVERGENCE_FAILED,
    NUMERICALLY_UNSAFE_REQUEST
}
