package com.ailab.chemistry.domain.acidbase;

public enum PolyproticTitrationSystemType {
    DIPROTIC_ACID_WITH_STRONG_MONOBASIC_BASE,
    FULLY_DEPROTONATED_SALT_WITH_STRONG_MONOPROTIC_ACID,
    AMPHIPROTIC_SALT_WITH_STRONG_MONOPROTIC_ACID,
    AMPHIPROTIC_SALT_WITH_STRONG_MONOBASIC_BASE
}
