package com.ailab.chemistry.domain.acidbase;

public enum TitrationErrorCode {
    UNSUPPORTED_TITRATION_SYSTEM,
    POLYPROTIC_TITRATION_UNSUPPORTED,
    MISMATCHED_SPECIES_ROLES,
    UNSUPPORTED_SOLVENT,
    MISSING_TEMPERATURE,
    INSUFFICIENT_REFERENCE_DATA,
    NON_POSITIVE_CONCENTRATION,
    NON_POSITIVE_VOLUME,
    NEGATIVE_TITRANT_VOLUME,
    DUPLICATE_TITRANT_VOLUME,
    SOLVER_CONVERGENCE_FAILED,
    NUMERICALLY_UNSAFE_REQUEST
}
