package com.ailab.chemistry.domain.acidbase;

public enum TitrationAssumption {
    AQUEOUS_SOLVENT,
    IDEAL_SOLUTION,
    MONOPROTIC_ANALYTE,
    MONOBASIC_TITRANT,
    ADDITIVE_VOLUMES,
    WATER_AUTOIONIZATION_INCLUDED,
    TEMPERATURE_SPECIFIC_CONSTANTS,
    NO_ACTIVITY_COEFFICIENT_CORRECTION
}
