'use client';
import { useMemo, useState } from 'react';
import { Check, Plus, Search, X } from 'lucide-react';
import type { JsonObject } from '@/shared/api/contracts/platform';
import type { ScenarioResourceSet, ScenarioScene } from './scenario.types';

const label = (item: JsonObject) => String(item.name ?? item.formula ?? item.code ?? item.id);
function Picker({ title, rows, value, usedIds, onChange }: { title: string; rows: JsonObject[]; value: string[]; usedIds: Set<string>; onChange: (value: string[]) => void }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [pendingRemoval, setPendingRemoval] = useState('');
  const byId = new Map(rows.map((row) => [String(row.id ?? row.code), row]));
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return rows.filter((row) => !value.includes(String(row.id ?? row.code)) && (!needle || [row.name, row.code, row.formula, row.category].some((field) => String(field ?? '').toLowerCase().includes(needle)))).slice(0, 30); }, [query, rows, value]);
  return <section className="rounded-xl border border-white/10 bg-[#0b101a] p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">Allowed {title}</h2><p className="mt-1 text-xs text-slate-500">Available to learners without forcing an object into the initial scene.</p></div><button type="button" onClick={() => setOpen((current) => !current)} className="flex items-center gap-2 rounded-lg bg-violet-600 px-3 py-2 text-sm"><Plus size={14}/>Add {title}</button></div>
    <div className="mt-4 space-y-2">{value.map((id) => { const row = byId.get(id); const status = row ? String(row.status ?? 'PUBLISHED') : 'MISSING'; const used = usedIds.has(id); return <div key={id} className="rounded-lg border border-white/10 p-3"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-500/10 text-emerald-300"><Check size={14}/></span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{row ? label(row) : id}</b><code className="text-[10px] text-slate-500">{String(row?.code ?? id)}</code></span>{used && <span className="rounded-full bg-amber-500/10 px-2 py-1 text-[10px] text-amber-300">IN USE</span>}<span className={`rounded-full px-2 py-1 text-[10px] ${status === 'PUBLISHED' ? 'bg-emerald-500/10 text-emerald-300' : status === 'MISSING' ? 'bg-rose-500/10 text-rose-300' : 'bg-amber-500/10 text-amber-300'}`}>{status}</span><button type="button" aria-label={`Remove ${label(row ?? { id })}`} onClick={() => used ? setPendingRemoval(id) : onChange(value.filter((item) => item !== id))} className="text-slate-400 hover:text-rose-300"><X size={15}/></button></div>{pendingRemoval === id && <div className="mt-3 rounded-lg border border-amber-400/20 bg-amber-500/10 p-3 text-xs text-amber-100"><p>This resource is used by the Initial Scene. Removing it will create a validation error until those references are cleaned.</p><div className="mt-2 flex gap-2"><button type="button" onClick={() => setPendingRemoval('')} className="rounded border border-white/10 px-2 py-1">Cancel</button><button type="button" onClick={() => { onChange(value.filter((item) => item !== id)); setPendingRemoval(''); }} className="rounded bg-rose-600 px-2 py-1 text-white">Remove anyway</button></div></div>}</div>; })}{!value.length && <p className="rounded-lg border border-dashed border-white/10 p-4 text-center text-sm text-slate-500">No {title} selected.</p>}</div>
    {open && <div className="mt-4 rounded-xl border border-violet-400/20 bg-black/20 p-3"><label className="flex items-center gap-2 rounded-lg border border-white/10 bg-[#080c14] px-3"><Search size={14} className="text-slate-500"/><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent py-2 text-sm outline-none" placeholder={`Search ${title} by name, code, formula, or category`}/></label><div className="mt-2 max-h-72 space-y-1 overflow-auto">{filtered.map((row) => { const id = String(row.id ?? row.code); return <button type="button" key={id} onClick={() => { onChange([...value, id]); setQuery(''); }} className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left hover:bg-white/5"><span className="min-w-0 flex-1"><b className="block truncate text-sm">{label(row)}</b><span className="text-[10px] text-slate-500">{String(row.code ?? id)} {row.formula ? `· ${String(row.formula)}` : ''}</span></span><span className="text-[10px] text-emerald-300">{String(row.status ?? 'PUBLISHED')}</span></button>; })}{!filtered.length && <p className="p-4 text-center text-sm text-slate-500">No matching {title} found in the loaded catalog page.</p>}</div></div>}
  </section>;
}
export function ScenarioResources({ resources, scene, equipment, materials, onChange }: { resources: ScenarioResourceSet; scene: ScenarioScene; equipment: JsonObject[]; materials: JsonObject[]; onChange: (value: ScenarioResourceSet) => void }) { const usedEquipmentIds = new Set(scene.objects.map((item) => item.equipmentId)); const usedMaterialIds = new Set(scene.objects.flatMap((item) => item.contents.map((content) => content.materialId))); return <div className="grid gap-4 xl:grid-cols-2"><Picker title="equipment" rows={equipment} value={resources.equipmentIds} usedIds={usedEquipmentIds} onChange={(equipmentIds) => onChange({ ...resources, equipmentIds })}/><Picker title="materials" rows={materials} value={resources.materialIds} usedIds={usedMaterialIds} onChange={(materialIds) => onChange({ ...resources, materialIds })}/></div>; }
