package com.ailab.chemistry.domain.element.property;

public enum ElementPropertyErrorCode {
    ELEMENT_PROPERTY_PROFILE_NOT_FOUND,
    INVALID_VALENCY,
    DUPLICATE_VALENCY,
    INVALID_OXIDATION_STATE,
    DUPLICATE_OXIDATION_STATE,
    INVALID_ELECTRONEGATIVITY,
    DUPLICATE_ELECTRONEGATIVITY_SCALE,
    INVALID_RADIUS,
    INVALID_IONIC_RADIUS_CONTEXT,
    INVALID_DENSITY,
    INVALID_PHASE_TRANSITION,
    INCOMPATIBLE_REFERENCE_CONDITIONS,
    INVALID_EVIDENCE_STATUS,
    PROPERTY_DATASET_NOT_FOUND,
    PROPERTY_DATASET_INCOMPLETE,
    PROPERTY_DATA_MISMATCH,
    PROPERTY_PROVENANCE_MISSING
}
