package com.ailab.chemistry.domain.compound;

public enum CompoundErrorCode {
    INVALID_COMPOUND_CODE,
    INVALID_COMPOUND_NAME,
    INVALID_COMPOUND_FORMULA,
    COMPOUND_FORMULA_MISMATCH,
    INVALID_COMPOUND_COMPOSITION,
    DUPLICATE_COMPOUND_ALIAS,
    DUPLICATE_EXTERNAL_IDENTIFIER,
    ELEMENT_MASS_NOT_FOUND,
    INVALID_MOLAR_MASS,
    MOLAR_MASS_INTERVAL_INVALID,
    COMPOUND_NOT_FOUND,
    COMPOUND_CATALOG_VERSION_NOT_FOUND,
    COMPOUND_CATALOG_INCOMPLETE,
    COMPOUND_DATA_MISMATCH,
    COMPOUND_PROVENANCE_MISSING
}
