"use client";

import { useMemo, useState } from "react";
import { ArrowDown, ArrowRight, Check, Flame, Gauge, Play, ShieldAlert, Thermometer, Wind, X } from "lucide-react";
import type { CodexSection } from "./CodexSpreads";
import { SubstanceIndex } from "./SubstanceIndex";

export function AdvancedChapterSpread({ section, onOpenLab }: { section: CodexSection; onOpenLab?: (context: string) => void }) {
  if (section === "substances") return <SubstanceIndex />;
  if (section === "contents" || section === "equipment") return <SafetyManual />;
  if (section === "ports") return <ConnectionAtlas />;
  if (section === "experiments") return <ExperimentLibrary onOpenLab={onOpenLab} />;
  if (section === "physics") return <PhysicsReference />;
  return <SafetyManual />;
}

function Plate({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`academy-page-surface rounded-[22px] border border-white/10 p-7 sm:p-10 ${className}`}>{children}</div>; }

function ConnectionAtlas() { const [source, setSource] = useState("Burette · liquid out"); const targets = ["Beaker · liquid in", "Flask · liquid in", "Container opening", "Electrical port", "Coolant jacket"]; const compatible = [0, 1, 2]; return <><Plate><p className="text-xs uppercase tracking-[.28em] text-blue-300">Chapter 03 · Technical atlas</p><h1 className="mt-5 font-serif text-5xl font-bold text-white">Connection Atlas</h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">Trace the interfaces that let matter, energy and signals move through the laboratory.</p><div className="mt-12 space-y-5"><div className="flex items-center gap-4"><span className="w-28 text-xs uppercase tracking-wider text-cyan-300">Liquid out</span><span className="h-px flex-1 bg-gradient-to-r from-cyan-300 via-cyan-300/60 to-transparent"/><span className="text-cyan-200">●</span></div><div className="flex items-center gap-4"><span className="w-28 text-xs uppercase tracking-wider text-slate-400">Vapor / gas</span><span className="h-px flex-1 border-t border-dashed border-slate-500"/><span className="text-slate-300">○</span></div><div className="flex items-center gap-4"><span className="w-28 text-xs uppercase tracking-wider text-orange-300">Heat</span><span className="h-px flex-1 bg-gradient-to-r from-orange-300 via-orange-300/60 to-transparent"/><span className="text-orange-200">↯</span></div></div></Plate><Plate><p className="text-xs uppercase tracking-[.25em] text-slate-500">Compatibility exercise</p><h2 className="mt-3 font-serif text-3xl font-bold text-white">Route a connection</h2><div className="mt-7 rounded-xl border border-cyan-300/20 bg-cyan-300/5 p-4"><p className="text-xs text-slate-500">SOURCE</p><p className="mt-1 font-semibold text-cyan-200">{source}</p></div><div className="mt-5 space-y-2">{targets.map((target, index) => { const ok = compatible.includes(index); return <button key={target} onClick={() => setSource(target)} className={`flex w-full items-center gap-3 border-b p-3 text-left transition ${ok ? "border-emerald-300/30 hover:bg-emerald-300/10" : "border-red-300/20 hover:bg-red-300/10"}`}><span className={ok ? "text-emerald-300" : "text-red-300"}>{ok ? <Check size={16}/> : <X size={16}/>}</span><span className="flex-1 text-sm text-slate-200">{target}</span><span className="text-xs text-slate-500">{ok ? "compatible" : "incompatible"}</span></button>; })}</div></Plate></>; }

function ExperimentLibrary({ onOpenLab }: { onOpenLab?: (context: string) => void }) { const experiments = [{ title: "Heating Water", time: "4 min", level: "Beginner", objective: "Observe the separation of heater, glass and liquid temperature." }, { title: "Simple Distillation", time: "8 min", level: "Intermediate", objective: "Follow vapor through a condenser into a receiver." }, { title: "Acid–Base Titration", time: "8 min", level: "Intermediate", objective: "Deliver precise liquid volumes and read the endpoint." }]; return <><Plate><p className="text-xs uppercase tracking-[.28em] text-orange-300">Chapter 04 · Research library</p><h1 className="mt-5 font-serif text-5xl font-bold text-white">Experiments</h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">Illustrated studies that connect this book to a live laboratory setup.</p><div className="mt-9 space-y-3">{experiments.map((experiment, index) => <article key={experiment.title} className="group border-b border-white/10 py-5 transition hover:border-orange-300/40"><div className="flex items-start gap-4"><span className="font-mono text-orange-300">0{index + 1}</span><div className="flex-1"><h2 className="font-serif text-2xl font-bold text-white">{experiment.title}</h2><p className="mt-1 text-sm text-slate-400">{experiment.objective}</p><p className="mt-3 text-xs uppercase tracking-wider text-slate-500">{experiment.level} · {experiment.time}</p></div><div className="grid h-14 w-14 place-items-center rounded-full border border-orange-300/30 bg-orange-300/10 text-orange-200"><Flame size={22}/></div></div><button onClick={() => onOpenLab?.(experiment.title)} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-orange-300 px-3 py-2 text-xs font-bold text-slate-950 hover:bg-orange-200"><Play size={13}/> Open in Lab</button></article>)}</div></Plate><Plate><p className="text-xs uppercase tracking-[.25em] text-slate-500">Assembly preview</p><div className="mt-8 flex flex-col items-center gap-2 text-sm"><span className="border border-cyan-300/30 px-5 py-3 text-cyan-200">Burette · liquid out</span><ArrowDown className="text-cyan-300"/><span className="border border-cyan-300/30 px-5 py-3 text-cyan-200">Erlenmeyer Flask · liquid in</span><ArrowDown className="text-cyan-300"/><span className="border border-orange-300/30 px-5 py-3 text-orange-200">Thermal observation</span></div></Plate></>; }

function PhysicsReference() { const [heat, setHeat] = useState(180); const [flow, setFlow] = useState(45); const bubbles = Math.round(heat / 35); return <><Plate><p className="text-xs uppercase tracking-[.28em] text-emerald-300">Chapter 05 · Simulation reference</p><h1 className="mt-5 font-serif text-5xl font-bold text-white">Physics Engine</h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">Change one variable and observe how energy and matter respond.</p><div className="mt-10 grid grid-cols-2 gap-3">{["Heat transfer", "Boiling", "Condensation", "Thermal shock", "Fluid flow", "Pressure"].map((topic, i) => <div key={topic} className="border-b border-white/10 p-3 text-sm text-slate-200"><span className="mr-2 font-mono text-emerald-300">0{i + 1}</span>{topic}</div>)}</div></Plate><Plate><div className="flex items-center justify-between"><h2 className="font-serif text-3xl font-bold text-white">Heat transfer</h2><span className="font-mono text-orange-300">{heat}°C</span></div><div className="mt-8 grid grid-cols-3 items-center gap-2 text-center text-xs"><div className="border border-orange-300/30 p-4 text-orange-200"><Flame className="mx-auto mb-2" size={22}/>HOT PLATE</div><ArrowRight className="mx-auto text-orange-300"/><div className="border border-cyan-300/30 p-4 text-cyan-200"><span className="block mb-2 text-2xl">◌</span>BEAKER</div></div><label className="mt-8 block text-xs uppercase tracking-[.18em] text-slate-400"><span className="flex justify-between"><span className="flex gap-2"><Thermometer size={14}/> Heater temperature</span><b className="text-orange-300">{heat}°C</b></span><input aria-label="Heater temperature" type="range" min="24" max="400" value={heat} onChange={event => setHeat(Number(event.target.value))} className="mt-3 w-full accent-orange-300"/></label><div className="mt-7 flex h-20 items-end gap-2 border-b border-l border-white/15 px-3">{Array.from({ length: 18 }).map((_, i) => <span key={i} className="flex-1 rounded-t bg-gradient-to-t from-orange-400/70 to-cyan-300/30" style={{ height: `${Math.max(12, Math.min(100, (i / 17) * (heat / 3)))}%` }}/>)}</div><div className="mt-7 border-t border-white/10 pt-6"><label className="block text-xs uppercase tracking-[.18em] text-slate-400"><span className="flex justify-between"><span className="flex gap-2"><Wind size={14}/> Fluid flow</span><b className="text-cyan-300">{flow}%</b></span><input aria-label="Fluid flow" type="range" min="0" max="100" value={flow} onChange={event => setFlow(Number(event.target.value))} className="mt-3 w-full accent-cyan-300"/></label><p className="mt-4 text-sm text-slate-400">{bubbles} convection bubbles · flow response visualized in real time.</p></div></Plate></>; }

function SafetyManual() { const [active, setActive] = useState("Thermal stress"); const notes = ["Thermal stress", "Pressure", "Open flames", "Chemical compatibility", "Equipment support", "Sensor ranges"]; return <><Plate><p className="text-xs uppercase tracking-[.28em] text-amber-300">Chapter 06 · Engineering manual</p><h1 className="mt-5 font-serif text-5xl font-bold text-white">Safety</h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">Read the limits of the system before asking it to perform.</p><div className="mt-10 space-y-1">{notes.map((note, i) => <button key={note} onClick={() => setActive(note)} className={`flex w-full items-center gap-4 border-b p-4 text-left transition ${active === note ? "border-amber-300/50 bg-amber-300/10" : "border-white/5 hover:bg-white/5"}`}><ShieldAlert size={16} className="text-amber-300"/><span className="flex-1 text-sm text-slate-200">{note}</span><span className="font-mono text-xs text-slate-600">0{i + 1}</span></button>)}</div></Plate><Plate><p className="text-xs uppercase tracking-[.25em] text-amber-300">Field note</p><h2 className="mt-3 font-serif text-3xl font-bold text-white">{active}</h2><div className="mt-8 border-l-2 border-amber-300/50 pl-5"><p className="text-base leading-7 text-slate-300">Inspect gradients, ratings and material compatibility before activating the apparatus. Safety state is an engineering constraint, not an afterthought.</p></div><div className="mt-8 grid grid-cols-2 gap-4 text-sm"><div><p className="text-xs text-slate-500">Status</p><p className="mt-1 text-emerald-300">Within reference range</p></div><div><p className="text-xs text-slate-500">Action</p><p className="mt-1 text-slate-200">Inspect before run</p></div></div></Plate></>; }
