package com.ailab.chemistry.domain.solubility;

public enum SolubilityErrorCode {
    INVALID_EQUILIBRIUM_CODE,
    INVALID_ION_SPECIES,
    UNBALANCED_DISSOLUTION,
    MISSING_KSP,
    NEGATIVE_CONCENTRATION,
    NON_POSITIVE_VOLUME,
    UNSUPPORTED_REFERENCE_CONDITIONS,
    OUTSIDE_ACTIVITY_MODEL_RANGE,
    SOLVER_CONVERGENCE_FAILED
}
