package com.ailab.chemistry.domain.electrochemistry;

public enum ElectrochemicalErrorCode {
    MISSING_HALF_REACTION,
    INVALID_HALF_REACTION,
    UNBALANCED_HALF_REACTION,
    DUPLICATE_RECORD,
    MISSING_ACTIVITY,
    INVALID_ACTIVITY,
    ACTIVITY_MODEL_OUT_OF_RANGE,
    INVALID_TEMPERATURE,
    INVALID_CURRENT_EFFICIENCY,
    INVALID_ELECTROLYSIS_REQUEST,
    UNSUPPORTED_HALF_REACTION,
    MISSING_MOLAR_MASS
}
