package com.ailab.chemistry.domain.simulationengine;

public enum SimulationExecutionErrorCode {
    INVALID_COMMAND,
    EXPLICIT_OPERATION_REQUIRED,
    SESSION_NOT_RUNNING,
    STEP_NOT_RUNNING,
    OPERATION_NOT_ALLOWED_FOR_STEP,
    UNSUPPORTED_MODEL_SELECTION,
    SUITABILITY_REJECTED,
    STATE_DELTA_INVARIANT_FAILED,
    IDEMPOTENCY_CONFLICT,
    STALE_STATE_VERSION,
    AUDIT_NOT_FOUND
}
