export { api, setAccessToken, getAccessToken } from '@/shared/api/client';
export { authApi } from '@/entities/auth/api/auth.api';
export { userApi } from '@/entities/user/api/user.api';
export { chemistryApi } from '@/entities/element/api/chemistry.api';
export { experimentApi } from '@/entities/experiment/api/experiment.api';
export { catalogApi } from '@/entities/equipment/api/catalog.api';
export { adminApi } from '@/entities/user/api/admin.api';
export { workspacesApi } from '@/entities/workspace/api/workspace.api';
export { workspaceCollaborationApi } from '@/entities/workspace/api/collaboration.api';
export { learningApi, adminLearningApi } from '@/entities/learning/api/learning.api';
export { bookApi, adminBookApi } from '@/entities/book/api/book.api';
export { adminPlatformApi } from '@/entities/admin/api/platform-admin.api';
