package com.ailab.chemistry.domain.element.exception;

public enum ElementCatalogErrorCode {
    INVALID_ATOMIC_NUMBER,
    ELEMENT_NOT_FOUND,
    DUPLICATE_ATOMIC_NUMBER,
    DUPLICATE_ELEMENT_SYMBOL,
    DUPLICATE_ELEMENT_NAME,
    INVALID_ATOMIC_MASS,
    INVALID_PERIOD,
    INVALID_GROUP,
    INVALID_ELEMENT_CATEGORY,
    CATALOG_VERSION_NOT_FOUND,
    CATALOG_DATA_MISMATCH,
    CATALOG_INCOMPLETE
}
