package com.ailab.chemistry.infrastructure.persistence.element;

import com.ailab.chemistry.domain.element.*;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.*;

@Component
@Profile({"test", "standalone-engine"})
public class InMemoryElementRepository implements ElementRepository {

    private static final String[] ELEMENT_DATA = {
        "1|H|Hydrogen||1.008|INTERVAL_STANDARD_ATOMIC_WEIGHT|1.00784|1.00811|1|1|S|REACTIVE_NONMETAL|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|1s1|EVALUATED",
        "2|He|Helium||4.0026|STANDARD_ATOMIC_WEIGHT|||1|18|S|NOBLE_GAS|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|1s2|EVALUATED",
        "3|Li|Lithium||6.94|INTERVAL_STANDARD_ATOMIC_WEIGHT|6.938|6.997|2|1|S|ALKALI_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[He] 2s1|EVALUATED",
        "4|Be|Beryllium||9.0122|STANDARD_ATOMIC_WEIGHT|||2|2|S|ALKALINE_EARTH_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[He] 2s2|EVALUATED",
        "5|B|Boron||10.81|INTERVAL_STANDARD_ATOMIC_WEIGHT|10.806|10.821|2|13|P|METALLOID|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[He] 2s2 2p1|EVALUATED",
        "6|C|Carbon||12.011|INTERVAL_STANDARD_ATOMIC_WEIGHT|12.0096|12.0116|2|14|P|REACTIVE_NONMETAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[He] 2s2 2p2|EVALUATED",
        "7|N|Nitrogen||14.007|INTERVAL_STANDARD_ATOMIC_WEIGHT|14.00643|14.00728|2|15|P|REACTIVE_NONMETAL|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|[He] 2s2 2p3|EVALUATED",
        "8|O|Oxygen||15.999|INTERVAL_STANDARD_ATOMIC_WEIGHT|15.99491|15.99977|2|16|P|REACTIVE_NONMETAL|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|[He] 2s2 2p4|EVALUATED",
        "9|F|Fluorine||18.998|STANDARD_ATOMIC_WEIGHT|||2|17|P|REACTIVE_NONMETAL|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|[He] 2s2 2p5|EVALUATED",
        "10|Ne|Neon||20.180|STANDARD_ATOMIC_WEIGHT|||2|18|P|NOBLE_GAS|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|[He] 2s2 2p6|EVALUATED",
        "11|Na|Sodium|Natrium|22.990|STANDARD_ATOMIC_WEIGHT|||3|1|S|ALKALI_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ne] 3s1|EVALUATED",
        "12|Mg|Magnesium||24.305|INTERVAL_STANDARD_ATOMIC_WEIGHT|24.304|24.307|3|2|S|ALKALINE_EARTH_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ne] 3s2|EVALUATED",
        "13|Al|Aluminium||26.982|STANDARD_ATOMIC_WEIGHT|||3|13|P|POST_TRANSITION_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ne] 3s2 3p1|EVALUATED",
        "14|Si|Silicon||28.085|INTERVAL_STANDARD_ATOMIC_WEIGHT|28.084|28.086|3|14|P|METALLOID|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ne] 3s2 3p2|EVALUATED",
        "15|P|Phosphorus||30.974|STANDARD_ATOMIC_WEIGHT|||3|15|P|REACTIVE_NONMETAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ne] 3s2 3p3|EVALUATED",
        "16|S|Sulfur||32.06|INTERVAL_STANDARD_ATOMIC_WEIGHT|32.059|32.076|3|16|P|REACTIVE_NONMETAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ne] 3s2 3p4|EVALUATED",
        "17|Cl|Chlorine||35.45|INTERVAL_STANDARD_ATOMIC_WEIGHT|35.446|35.457|3|17|P|REACTIVE_NONMETAL|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|[Ne] 3s2 3p5|EVALUATED",
        "18|Ar|Argon||39.948|INTERVAL_STANDARD_ATOMIC_WEIGHT|39.792|39.963|3|18|P|NOBLE_GAS|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|[Ne] 3s2 3p6|EVALUATED",
        "19|K|Potassium|Kalium|39.098|STANDARD_ATOMIC_WEIGHT|||4|1|S|ALKALI_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ar] 4s1|EVALUATED",
        "20|Ca|Calcium||40.078|STANDARD_ATOMIC_WEIGHT|||4|2|S|ALKALINE_EARTH_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ar] 4s2|EVALUATED",
        "21|Sc|Scandium||44.956|STANDARD_ATOMIC_WEIGHT|||4|3|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d1 4s2|EVALUATED",
        "22|Ti|Titanium||47.867|STANDARD_ATOMIC_WEIGHT|||4|4|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d2 4s2|EVALUATED",
        "23|V|Vanadium||50.942|STANDARD_ATOMIC_WEIGHT|||4|5|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d3 4s2|EVALUATED",
        "24|Cr|Chromium||51.996|STANDARD_ATOMIC_WEIGHT|||4|6|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d5 4s1|EVALUATED",
        "25|Mn|Manganese||54.938|STANDARD_ATOMIC_WEIGHT|||4|7|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d5 4s2|EVALUATED",
        "26|Fe|Iron|Ferrum|55.845|STANDARD_ATOMIC_WEIGHT|||4|8|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d6 4s2|EVALUATED",
        "27|Co|Cobalt||58.933|STANDARD_ATOMIC_WEIGHT|||4|9|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d7 4s2|EVALUATED",
        "28|Ni|Nickel||58.693|STANDARD_ATOMIC_WEIGHT|||4|10|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d8 4s2|EVALUATED",
        "29|Cu|Copper|Cuprum|63.546|STANDARD_ATOMIC_WEIGHT|||4|11|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d10 4s1|EVALUATED",
        "30|Zn|Zinc||65.38|STANDARD_ATOMIC_WEIGHT|||4|12|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d10 4s2|EVALUATED",
        "31|Ga|Gallium||69.723|STANDARD_ATOMIC_WEIGHT|||4|13|P|POST_TRANSITION_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d10 4s2 4p1|EVALUATED",
        "32|Ge|Germanium||72.630|STANDARD_ATOMIC_WEIGHT|||4|14|P|METALLOID|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d10 4s2 4p2|EVALUATED",
        "33|As|Arsenic||74.922|STANDARD_ATOMIC_WEIGHT|||4|15|P|METALLOID|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d10 4s2 4p3|EVALUATED",
        "34|Se|Selenium||78.971|STANDARD_ATOMIC_WEIGHT|||4|16|P|REACTIVE_NONMETAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Ar] 3d10 4s2 4p4|EVALUATED",
        "35|Br|Bromine||79.904|INTERVAL_STANDARD_ATOMIC_WEIGHT|79.901|79.907|4|17|P|REACTIVE_NONMETAL|MAIN_GROUP|LIQUID|HAS_STABLE_ISOTOPES|[Ar] 3d10 4s2 4p5|EVALUATED",
        "36|Kr|Krypton||83.798|STANDARD_ATOMIC_WEIGHT|||4|18|P|NOBLE_GAS|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|[Ar] 3d10 4s2 4p6|EVALUATED",
        "37|Rb|Rubidium||85.468|STANDARD_ATOMIC_WEIGHT|||5|1|S|ALKALI_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Kr] 5s1|EVALUATED",
        "38|Sr|Strontium||87.62|STANDARD_ATOMIC_WEIGHT|||5|2|S|ALKALINE_EARTH_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Kr] 5s2|EVALUATED",
        "39|Y|Yttrium||88.906|STANDARD_ATOMIC_WEIGHT|||5|3|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d1 5s2|EVALUATED",
        "40|Zr|Zirconium||91.224|STANDARD_ATOMIC_WEIGHT|||5|4|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d2 5s2|EVALUATED",
        "41|Nb|Niobium||92.906|STANDARD_ATOMIC_WEIGHT|||5|5|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d4 5s1|EVALUATED",
        "42|Mo|Molybdenum||95.95|STANDARD_ATOMIC_WEIGHT|||5|6|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d5 5s1|EVALUATED",
        "43|Tc|Technetium||98|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||5|7|D|TRANSITION_METAL|TRANSITION|SOLID|SYNTHETIC_RADIOACTIVE|[Kr] 4d5 5s2|EVALUATED",
        "44|Ru|Ruthenium||101.07|STANDARD_ATOMIC_WEIGHT|||5|8|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d7 5s1|EVALUATED",
        "45|Rh|Rhodium||102.91|STANDARD_ATOMIC_WEIGHT|||5|9|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d8 5s1|EVALUATED",
        "46|Pd|Palladium||106.42|STANDARD_ATOMIC_WEIGHT|||5|10|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d10|EVALUATED",
        "47|Ag|Silver|Argentum|107.87|STANDARD_ATOMIC_WEIGHT|||5|11|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d10 5s1|EVALUATED",
        "48|Cd|Cadmium||112.41|STANDARD_ATOMIC_WEIGHT|||5|12|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d10 5s2|EVALUATED",
        "49|In|Indium||114.82|STANDARD_ATOMIC_WEIGHT|||5|13|P|POST_TRANSITION_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d10 5s2 5p1|EVALUATED",
        "50|Sn|Tin|Stannum|118.71|STANDARD_ATOMIC_WEIGHT|||5|14|P|POST_TRANSITION_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d10 5s2 5p2|EVALUATED",
        "51|Sb|Antimony|Stibium|121.76|STANDARD_ATOMIC_WEIGHT|||5|15|P|METALLOID|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d10 5s2 5p3|EVALUATED",
        "52|Te|Tellurium||127.60|STANDARD_ATOMIC_WEIGHT|||5|16|P|METALLOID|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d10 5s2 5p4|EVALUATED",
        "53|I|Iodine||126.90|STANDARD_ATOMIC_WEIGHT|||5|17|P|REACTIVE_NONMETAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Kr] 4d10 5s2 5p5|EVALUATED",
        "54|Xe|Xenon||131.29|STANDARD_ATOMIC_WEIGHT|||5|18|P|NOBLE_GAS|MAIN_GROUP|GAS|HAS_STABLE_ISOTOPES|[Kr] 4d10 5s2 5p6|EVALUATED",
        "55|Cs|Caesium||132.91|STANDARD_ATOMIC_WEIGHT|||6|1|S|ALKALI_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Xe] 6s1|EVALUATED",
        "56|Ba|Barium||137.33|STANDARD_ATOMIC_WEIGHT|||6|2|S|ALKALINE_EARTH_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Xe] 6s2|EVALUATED",
        "57|La|Lanthanum||138.91|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 5d1 6s2|EVALUATED",
        "58|Ce|Cerium||140.12|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f1 5d1 6s2|EVALUATED",
        "59|Pr|Praseodymium||140.91|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f3 6s2|EVALUATED",
        "60|Nd|Neodymium||144.24|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f4 6s2|EVALUATED",
        "61|Pm|Promethium||145|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||6||F|LANTHANIDE|LANTHANIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Xe] 4f5 6s2|EVALUATED",
        "62|Sm|Samarium||150.36|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f6 6s2|EVALUATED",
        "63|Eu|Europium||151.96|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f7 6s2|EVALUATED",
        "64|Gd|Gadolinium||157.25|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f7 5d1 6s2|EVALUATED",
        "65|Tb|Terbium||158.93|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f9 6s2|EVALUATED",
        "66|Dy|Dysprosium||162.50|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f10 6s2|EVALUATED",
        "67|Ho|Holmium||164.93|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f11 6s2|EVALUATED",
        "68|Er|Erbium||167.26|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f12 6s2|EVALUATED",
        "69|Tm|Thulium||168.93|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f13 6s2|EVALUATED",
        "70|Yb|Ytterbium||173.05|STANDARD_ATOMIC_WEIGHT|||6||F|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 6s2|EVALUATED",
        "71|Lu|Lutetium||174.97|STANDARD_ATOMIC_WEIGHT|||6|3|D|LANTHANIDE|LANTHANIDE|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d1 6s2|EVALUATED",
        "72|Hf|Hafnium||178.49|STANDARD_ATOMIC_WEIGHT|||6|4|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d2 6s2|EVALUATED",
        "73|Ta|Tantalum||180.95|STANDARD_ATOMIC_WEIGHT|||6|5|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d3 6s2|EVALUATED",
        "74|W|Tungsten|Wolfram|183.84|STANDARD_ATOMIC_WEIGHT|||6|6|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d4 6s2|EVALUATED",
        "75|Re|Rhenium||186.21|STANDARD_ATOMIC_WEIGHT|||6|7|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d5 6s2|EVALUATED",
        "76|Os|Osmium||190.23|STANDARD_ATOMIC_WEIGHT|||6|8|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d6 6s2|EVALUATED",
        "77|Ir|Iridium||192.22|STANDARD_ATOMIC_WEIGHT|||6|9|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d7 6s2|EVALUATED",
        "78|Pt|Platinum||195.08|STANDARD_ATOMIC_WEIGHT|||6|10|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d9 6s1|EVALUATED",
        "79|Au|Gold|Aurum|196.97|STANDARD_ATOMIC_WEIGHT|||6|11|D|TRANSITION_METAL|TRANSITION|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d10 6s1|EVALUATED",
        "80|Hg|Mercury|Hydrargyrum|200.59|STANDARD_ATOMIC_WEIGHT|||6|12|D|TRANSITION_METAL|TRANSITION|LIQUID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d10 6s2|EVALUATED",
        "81|Tl|Thallium||204.38|INTERVAL_STANDARD_ATOMIC_WEIGHT|204.382|204.385|6|13|P|POST_TRANSITION_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d10 6s2 6p1|EVALUATED",
        "82|Pb|Lead|Plumbum|207.2|INTERVAL_STANDARD_ATOMIC_WEIGHT|206.14|207.94|6|14|P|POST_TRANSITION_METAL|MAIN_GROUP|SOLID|HAS_STABLE_ISOTOPES|[Xe] 4f14 5d10 6s2 6p2|EVALUATED",
        "83|Bi|Bismuth||208.98|STANDARD_ATOMIC_WEIGHT|||6|15|P|POST_TRANSITION_METAL|MAIN_GROUP|SOLID|PRIMORDIAL_RADIOACTIVE|[Xe] 4f14 5d10 6s2 6p3|EVALUATED",
        "84|Po|Polonium||209|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||6|16|P|METALLOID|MAIN_GROUP|SOLID|PRIMORDIAL_RADIOACTIVE|[Xe] 4f14 5d10 6s2 6p4|EVALUATED",
        "85|At|Astatine||210|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||6|17|P|METALLOID|MAIN_GROUP|SOLID|PRIMORDIAL_RADIOACTIVE|[Xe] 4f14 5d10 6s2 6p5|EVALUATED",
        "86|Rn|Radon||222|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||6|18|P|NOBLE_GAS|MAIN_GROUP|GAS|PRIMORDIAL_RADIOACTIVE|[Xe] 4f14 5d10 6s2 6p6|EVALUATED",
        "87|Fr|Francium||223|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7|1|S|ALKALI_METAL|MAIN_GROUP|SOLID|PRIMORDIAL_RADIOACTIVE|[Rn] 7s1|EVALUATED",
        "88|Ra|Radium||226|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7|2|S|ALKALINE_EARTH_METAL|MAIN_GROUP|SOLID|PRIMORDIAL_RADIOACTIVE|[Rn] 7s2|EVALUATED",
        "89|Ac|Actinium||227|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|PRIMORDIAL_RADIOACTIVE|[Rn] 6d1 7s2|EVALUATED",
        "90|Th|Thorium||232.04|STANDARD_ATOMIC_WEIGHT|||7||F|ACTINIDE|ACTINIDE|SOLID|PRIMORDIAL_RADIOACTIVE|[Rn] 6d2 7s2|EVALUATED",
        "91|Pa|Protactinium||231.04|STANDARD_ATOMIC_WEIGHT|||7||F|ACTINIDE|ACTINIDE|SOLID|PRIMORDIAL_RADIOACTIVE|[Rn] 5f2 6d1 7s2|EVALUATED",
        "92|U|Uranium||238.03|STANDARD_ATOMIC_WEIGHT|||7||F|ACTINIDE|ACTINIDE|SOLID|PRIMORDIAL_RADIOACTIVE|[Rn] 5f3 6d1 7s2|EVALUATED",
        "93|Np|Neptunium||237|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f4 6d1 7s2|PREDICTED",
        "94|Pu|Plutonium||244|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f6 7s2|PREDICTED",
        "95|Am|Americium||243|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f7 7s2|PREDICTED",
        "96|Cm|Curium||247|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f7 6d1 7s2|PREDICTED",
        "97|Bk|Berkelium||247|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f9 7s2|PREDICTED",
        "98|Cf|Californium||251|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f10 7s2|PREDICTED",
        "99|Es|Einsteinium||252|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f11 7s2|PREDICTED",
        "100|Fm|Fermium||257|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f12 7s2|PREDICTED",
        "101|Md|Mendelevium||258|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f13 7s2|PREDICTED",
        "102|No|Nobelium||259|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 7s2|PREDICTED",
        "103|Lr|Lawrencium||262|RADIOACTIVE_ISOTOPE_MASS_NUMBER|||7||F|ACTINIDE|ACTINIDE|SOLID|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 7s2 7p1|PREDICTED",
        "104|Rf|Rutherfordium||267|PREDICTED_OR_PROVISIONAL|||7|4|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d2 7s2|PROVISIONAL",
        "105|Db|Dubnium||268|PREDICTED_OR_PROVISIONAL|||7|5|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d3 7s2|PROVISIONAL",
        "106|Sg|Seaborgium||271|PREDICTED_OR_PROVISIONAL|||7|6|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d4 7s2|PROVISIONAL",
        "107|Bh|Bohrium||270|PREDICTED_OR_PROVISIONAL|||7|7|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d5 7s2|PROVISIONAL",
        "108|Hs|Hassium||277|PREDICTED_OR_PROVISIONAL|||7|8|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d6 7s2|PROVISIONAL",
        "109|Mt|Meitnerium||278|PREDICTED_OR_PROVISIONAL|||7|9|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d7 7s2|PROVISIONAL",
        "110|Ds|Darmstadtium||281|PREDICTED_OR_PROVISIONAL|||7|10|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d9 7s1|PROVISIONAL",
        "111|Rg|Roentgenium||282|PREDICTED_OR_PROVISIONAL|||7|11|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d10 7s1|PROVISIONAL",
        "112|Cn|Copernicium||285|PREDICTED_OR_PROVISIONAL|||7|12|D|TRANSITION_METAL|TRANSITION|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d10 7s2|PROVISIONAL",
        "113|Nh|Nihonium||286|PREDICTED_OR_PROVISIONAL|||7|13|P|POST_TRANSITION_METAL|MAIN_GROUP|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d10 7s2 7p1|PROVISIONAL",
        "114|Fl|Flerovium||289|PREDICTED_OR_PROVISIONAL|||7|14|P|POST_TRANSITION_METAL|MAIN_GROUP|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d10 7s2 7p2|PROVISIONAL",
        "115|Mc|Moscovium||290|PREDICTED_OR_PROVISIONAL|||7|15|P|POST_TRANSITION_METAL|MAIN_GROUP|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d10 7s2 7p3|PROVISIONAL",
        "116|Lv|Livermorium||293|PREDICTED_OR_PROVISIONAL|||7|16|P|POST_TRANSITION_METAL|MAIN_GROUP|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d10 7s2 7p4|PROVISIONAL",
        "117|Ts|Tennessine||294|PREDICTED_OR_PROVISIONAL|||7|17|P|METALLOID|MAIN_GROUP|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d10 7s2 7p5|PROVISIONAL",
        "118|Og|Oganesson||294|PREDICTED_OR_PROVISIONAL|||7|18|P|NOBLE_GAS|MAIN_GROUP|UNKNOWN|SYNTHETIC_RADIOACTIVE|[Rn] 5f14 6d10 7s2 7p6|PROVISIONAL"
    };

    private final List<Element> elements = new ArrayList<>();

    public InMemoryElementRepository() {
        for (String row : ELEMENT_DATA) {
            String[] parts = row.split("\\|", -1);
            int atomicNumber = Integer.parseInt(parts[0]);
            String symbol = parts[1];
            String name = parts[2];
            String latinName = parts[3].isEmpty() ? null : parts[3];
            BigDecimal massVal = new BigDecimal(parts[4]);
            AtomicMassKind kind = AtomicMassKind.valueOf(parts[5]);
            BigDecimal lowerBound = parts[6].isEmpty() ? null : new BigDecimal(parts[6]);
            BigDecimal upperBound = parts[7].isEmpty() ? null : new BigDecimal(parts[7]);
            int period = Integer.parseInt(parts[8]);
            Integer group = parts[9].isEmpty() ? null : Integer.parseInt(parts[9]);
            ElementBlock block = ElementBlock.valueOf(parts[10]);
            ElementCategory category = ElementCategory.valueOf(parts[11]);
            ElementSeries series = ElementSeries.valueOf(parts[12]);
            StandardState state = StandardState.valueOf(parts[13]);
            RadioactivityStatus radStatus = RadioactivityStatus.valueOf(parts[14]);
            String config = parts[15];
            ElectronConfigurationStatus configStatus = ElectronConfigurationStatus.valueOf(parts[16].trim());

            AtomicMass mass = new AtomicMass(massVal, kind, lowerBound, upperBound);
            UUID elementId = UUID.nameUUIDFromBytes((symbol + "_" + atomicNumber).getBytes());

            elements.add(new Element(
                    new ElementId(elementId),
                    atomicNumber,
                    symbol,
                    name,
                    latinName,
                    mass,
                    period,
                    group,
                    block,
                    config,
                    configStatus,
                    state,
                    radStatus,
                    category,
                    series,
                    "v1.1.0",
                    "CIAAW Standard Atomic Weights 2021; NIST Atomic Weights; IUPAC Periodic Table 2024"
            ));
        }
    }

    @Override
    public Optional<Element> findByAtomicNumber(int atomicNumber) {
        return elements.stream().filter(e -> e.getAtomicNumber() == atomicNumber).findFirst();
    }

    @Override
    public Optional<Element> findBySymbol(String symbol) {
        return elements.stream().filter(e -> e.getSymbol().equalsIgnoreCase(symbol)).findFirst();
    }

    @Override
    public List<Element> findAll() {
        return new ArrayList<>(elements);
    }

    @Override
    public void save(Element element) {
        elements.removeIf(e -> e.getAtomicNumber() == element.getAtomicNumber());
        elements.add(element);
    }

    @Override
    public void saveAll(List<Element> newElements) {
        newElements.forEach(this::save);
    }
}
