package com.ailab.chemistry.domain.hazard;

public enum HazardErrorCode {
    HAZARD_PROFILE_NOT_FOUND,
    HAZARD_DATASET_NOT_FOUND,
    HAZARD_DATASET_INCOMPLETE,
    HAZARD_DATA_MISMATCH,
    HAZARD_SOURCE_DOCUMENT_NOT_FOUND,
    HAZARD_PROVENANCE_MISSING,
    INVALID_HAZARD_SCOPE,
    INVALID_CONCENTRATION_SCOPE,
    INVALID_HAZARD_CLASS,
    INVALID_HAZARD_CATEGORY,
    INVALID_PICTOGRAM_CODE,
    INVALID_SIGNAL_WORD,
    INVALID_HAZARD_STATEMENT_CODE,
    INVALID_PRECAUTIONARY_STATEMENT_CODE,
    HAZARD_CLASSIFICATION_SYSTEM_MISMATCH,
    HAZARD_REVISION_MISMATCH,
    DUPLICATE_HAZARD_CLASSIFICATION,
    DUPLICATE_HAZARD_STATEMENT,
    DUPLICATE_PRECAUTIONARY_STATEMENT,
    HAZARD_AVAILABILITY_CONFLICT,
    SUMMARY_FLAG_MISMATCH,
    INVALID_SUPPLEMENTAL_HAZARD,
    INVALID_SAFETY_INSTRUCTION,
    INVALID_PPE_RECOMMENDATION
}
