package com.ailab.chemistry.domain.reaction;

public enum ReactionErrorCode {
    REACTION_NOT_FOUND,
    REACTION_CATALOG_VERSION_NOT_FOUND,
    INVALID_REACTION_CODE,
    INVALID_REACTION_NAME,
    INVALID_REACTION_TERM,
    REACTION_COMPOUND_NOT_FOUND,
    REACTION_FORMULA_MISMATCH,
    REACTION_UNBALANCED,
    REACTION_COEFFICIENT_INVALID,
    REACTION_COEFFICIENTS_NOT_MINIMAL,
    REACTION_CHARGE_NOT_CONSERVED,
    REACTION_DUPLICATE_TERM,
    REACTION_SIGNATURE_DUPLICATE,
    INVALID_REACTION_DIRECTIONALITY,
    INVALID_REACTION_STATE,
    INVALID_REACTION_CONDITIONS,
    INVALID_REACTION_CATALYST,
    REACTION_CATALYST_NOT_FOUND,
    INVALID_REACTION_TYPE,
    DUPLICATE_REACTION_TYPE,
    REACTION_PROVENANCE_MISSING,
    REACTION_DATASET_INCOMPLETE,
    REACTION_DATA_MISMATCH
}
