package com.ailab.chemistry.domain.kinetics;

public enum KineticErrorCode {
    INVALID_CONCENTRATION,
    INVALID_RATE_CONSTANT,
    INVALID_ORDER,
    INVALID_TEMPERATURE,
    INVALID_ACTIVATION_ENERGY,
    DIMENSIONAL_MISMATCH,
    REACTION_NOT_FOUND,
    PROFILE_NOT_FOUND,
    PARTICIPANT_MISMATCH,
    DUPLICATE_PROFILE,
    OUT_OF_TEMPERATURE_RANGE,
    SOLVER_NON_CONVERGENCE
}
