package com.ailab.chemistry.domain.solution;

public enum SolutionErrorCode {
    INVALID_QUANTITY,
    INVALID_CONCENTRATION,
    INVALID_FRACTION,
    INVALID_PERCENTAGE,
    SOLUTE_EQUALS_SOLVENT,
    INCOMPATIBLE_SOLUTES,
    INCOMPATIBLE_SOLVENTS,
    MISSING_DENSITY,
    NON_ADDITIVE_VOLUME_DENSITY_REQUIRED,
    COMPOUND_NOT_FOUND,
    DILUTION_PARAM_MISSING,
    INVALID_DILUTION_TARGET,
    CALCULATION_ERROR
}
