package com.ailab.chemistry.domain.gas;

public enum GasLawErrorCode {
    INVALID_TEMPERATURE,
    INVALID_PRESSURE,
    INVALID_VOLUME,
    INVALID_AMOUNT,
    INVALID_COMPRESSIBILITY_FACTOR,
    MISSING_COMPRESSIBILITY_FACTOR,
    INVALID_UNKNOWN_COUNT,
    MISSING_PROCESS_CONSTRAINT,
    INCONSISTENT_PROCESS_CONSTRAINT,
    INVALID_MIXTURE
}
