package com.ailab.chemistry.domain.formula.exception;

public enum FormulaErrorCode {
    EMPTY_FORMULA,
    INVALID_ELEMENT_SYMBOL,
    UNKNOWN_ELEMENT_SYMBOL,
    INVALID_SUBSCRIPT,
    ZERO_ELEMENT_COUNT,
    UNMATCHED_GROUP,
    EMPTY_GROUP,
    UNEXPECTED_TOKEN,
    INVALID_HYDRATE,
    INVALID_CHARGE,
    FORMULA_TOO_COMPLEX,
    INTEGER_OVERFLOW,
    AMBIGUOUS_CHARGE_NOTATION
}
