package com.ailab.chemistry.domain.labenvironment;

public enum EnvironmentErrorCode {
    INVALID_HUMIDITY,
    INVALID_REQUIREMENT,
    TEMPERATURE_OUTSIDE_RANGE,
    PRESSURE_OUTSIDE_RANGE,
    HUMIDITY_OUTSIDE_RANGE,
    VENTILATION_MODE_MISMATCH,
    FUME_HOOD_NOT_OPERATING,
    ISOLATED_ENCLOSURE_REQUIRED,
    PROHIBITED_ENVIRONMENTAL_STATE,
    MISSING_REQUIRED_ENVIRONMENT_VALUE
}
