-- Flyway Migration V28: Seed Thermodynamic Reference Foundation
-- Dataset Version: thermodynamic-reference-v1.0.0

INSERT INTO chemistry.thermodynamic_dataset_versions (version, description, publication_date)
VALUES (
    'thermodynamic-reference-v1.0.0',
    'Minimal educational thermodynamic reference subset at 298.15 K and 1 bar for existing compound catalogue records',
    '2026-08-06'
)
ON CONFLICT (version) DO NOTHING;

INSERT INTO chemistry.thermodynamic_source_documents (source_identifier, citation, publisher, reuse_limitations)
VALUES (
    'NIST-WEBBOOK',
    'NIST Chemistry WebBook thermochemistry tables and CODATA reference-state conventions',
    'National Institute of Standards and Technology',
    'NIST WebBook values are cited as a minimal educational subset; verify licensing before redistributing as a data table.'
)
ON CONFLICT (source_identifier) DO NOTHING;

INSERT INTO chemistry.thermodynamic_reference_conditions (
    temperature_kelvin,
    pressure_pascal,
    physical_state,
    standard_state_convention
)
VALUES
    (298.1500, 100000.0000, 'GAS', 'IDEAL_GAS_STANDARD_STATE'),
    (298.1500, 100000.0000, 'LIQUID', 'PURE_SUBSTANCE_STANDARD_STATE'),
    (298.1500, 100000.0000, 'SOLID', 'SOLID_REFERENCE_STATE')
ON CONFLICT (temperature_kelvin, pressure_pascal, physical_state, standard_state_convention) DO NOTHING;

WITH profile_values(compound_code) AS (
    VALUES
        ('COMP-H2'),
        ('COMP-O2'),
        ('COMP-H2O'),
        ('COMP-CO2'),
        ('COMP-CO'),
        ('COMP-CH4'),
        ('COMP-HCL'),
        ('COMP-NH3'),
        ('COMP-H2O2'),
        ('COMP-ETHANOL'),
        ('COMP-CH3COOH'),
        ('COMP-NAOH'),
        ('COMP-NACL'),
        ('COMP-CACO3'),
        ('COMP-NAHCO3'),
        ('COMP-NA2CO3')
)
INSERT INTO chemistry.thermodynamic_profiles (compound_code, dataset_version)
SELECT compound_code, 'thermodynamic-reference-v1.0.0'
FROM profile_values
ON CONFLICT (compound_code, dataset_version) DO NOTHING;

WITH source AS (
    SELECT source_identifier, citation, reuse_limitations
    FROM chemistry.thermodynamic_source_documents
    WHERE source_identifier = 'NIST-WEBBOOK'
),
values_table(compound_code, state, convention, property_type, numeric_value, unit_symbol, evidence_status) AS (
    VALUES
        ('COMP-H2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',0.000000,'kJ/mol','REFERENCE_STATE_DEFINED'),
        ('COMP-H2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',0.000000,'kJ/mol','REFERENCE_STATE_DEFINED'),
        ('COMP-H2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',130.680000,'J/(mol*K)','EVALUATED'),
        ('COMP-H2','GAS','IDEAL_GAS_STANDARD_STATE','MOLAR_HEAT_CAPACITY',28.840000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-O2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',0.000000,'kJ/mol','REFERENCE_STATE_DEFINED'),
        ('COMP-O2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',0.000000,'kJ/mol','REFERENCE_STATE_DEFINED'),
        ('COMP-O2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',205.150000,'J/(mol*K)','EVALUATED'),
        ('COMP-O2','GAS','IDEAL_GAS_STANDARD_STATE','MOLAR_HEAT_CAPACITY',29.360000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-H2O','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-285.830000,'kJ/mol','EVALUATED'),
        ('COMP-H2O','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-237.129000,'kJ/mol','EVALUATED'),
        ('COMP-H2O','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',69.910000,'J/(mol*K)','EVALUATED'),
        ('COMP-H2O','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','MOLAR_HEAT_CAPACITY',75.380000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-H2O','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-241.826000,'kJ/mol','EVALUATED'),
        ('COMP-H2O','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-228.572000,'kJ/mol','EVALUATED'),
        ('COMP-H2O','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',188.830000,'J/(mol*K)','EVALUATED'),
        ('COMP-H2O','GAS','IDEAL_GAS_STANDARD_STATE','MOLAR_HEAT_CAPACITY',33.580000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-CO2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-393.509000,'kJ/mol','EVALUATED'),
        ('COMP-CO2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-394.359000,'kJ/mol','EVALUATED'),
        ('COMP-CO2','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',213.790000,'J/(mol*K)','EVALUATED'),
        ('COMP-CO2','GAS','IDEAL_GAS_STANDARD_STATE','MOLAR_HEAT_CAPACITY',37.135000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-CO','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-110.525000,'kJ/mol','EVALUATED'),
        ('COMP-CO','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-137.168000,'kJ/mol','EVALUATED'),
        ('COMP-CO','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',197.660000,'J/(mol*K)','EVALUATED'),
        ('COMP-CO','GAS','IDEAL_GAS_STANDARD_STATE','MOLAR_HEAT_CAPACITY',29.140000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-CH4','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-74.873000,'kJ/mol','EVALUATED'),
        ('COMP-CH4','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-50.800000,'kJ/mol','EVALUATED'),
        ('COMP-CH4','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',186.250000,'J/(mol*K)','EVALUATED'),
        ('COMP-CH4','GAS','IDEAL_GAS_STANDARD_STATE','MOLAR_HEAT_CAPACITY',35.690000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-HCL','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-92.307000,'kJ/mol','EVALUATED'),
        ('COMP-HCL','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-95.300000,'kJ/mol','EVALUATED'),
        ('COMP-HCL','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',186.690000,'J/(mol*K)','EVALUATED'),
        ('COMP-HCL','GAS','IDEAL_GAS_STANDARD_STATE','MOLAR_HEAT_CAPACITY',29.100000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-NH3','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-46.110000,'kJ/mol','EVALUATED'),
        ('COMP-NH3','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-16.450000,'kJ/mol','EVALUATED'),
        ('COMP-NH3','GAS','IDEAL_GAS_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',192.770000,'J/(mol*K)','EVALUATED'),
        ('COMP-NH3','GAS','IDEAL_GAS_STANDARD_STATE','MOLAR_HEAT_CAPACITY',35.060000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-H2O2','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-187.780000,'kJ/mol','EVALUATED'),
        ('COMP-H2O2','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-120.350000,'kJ/mol','EVALUATED'),
        ('COMP-H2O2','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',109.600000,'J/(mol*K)','EVALUATED'),
        ('COMP-H2O2','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','MOLAR_HEAT_CAPACITY',89.100000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-ETHANOL','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-277.690000,'kJ/mol','EVALUATED'),
        ('COMP-ETHANOL','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-174.780000,'kJ/mol','EVALUATED'),
        ('COMP-ETHANOL','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',160.700000,'J/(mol*K)','EVALUATED'),
        ('COMP-ETHANOL','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','MOLAR_HEAT_CAPACITY',112.400000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-CH3COOH','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_ENTHALPY_OF_FORMATION',-484.500000,'kJ/mol','EVALUATED'),
        ('COMP-CH3COOH','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-389.900000,'kJ/mol','EVALUATED'),
        ('COMP-CH3COOH','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','STANDARD_MOLAR_ENTROPY',159.800000,'J/(mol*K)','EVALUATED'),
        ('COMP-CH3COOH','LIQUID','PURE_SUBSTANCE_STANDARD_STATE','MOLAR_HEAT_CAPACITY',123.100000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-NAOH','SOLID','SOLID_REFERENCE_STATE','STANDARD_ENTHALPY_OF_FORMATION',-425.600000,'kJ/mol','EVALUATED'),
        ('COMP-NAOH','SOLID','SOLID_REFERENCE_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-379.500000,'kJ/mol','EVALUATED'),
        ('COMP-NAOH','SOLID','SOLID_REFERENCE_STATE','STANDARD_MOLAR_ENTROPY',64.500000,'J/(mol*K)','EVALUATED'),
        ('COMP-NAOH','SOLID','SOLID_REFERENCE_STATE','MOLAR_HEAT_CAPACITY',59.500000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-NACL','SOLID','SOLID_REFERENCE_STATE','STANDARD_ENTHALPY_OF_FORMATION',-411.120000,'kJ/mol','EVALUATED'),
        ('COMP-NACL','SOLID','SOLID_REFERENCE_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-384.140000,'kJ/mol','EVALUATED'),
        ('COMP-NACL','SOLID','SOLID_REFERENCE_STATE','STANDARD_MOLAR_ENTROPY',72.110000,'J/(mol*K)','EVALUATED'),
        ('COMP-NACL','SOLID','SOLID_REFERENCE_STATE','MOLAR_HEAT_CAPACITY',50.500000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-CACO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_ENTHALPY_OF_FORMATION',-1206.900000,'kJ/mol','EVALUATED'),
        ('COMP-CACO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-1128.800000,'kJ/mol','EVALUATED'),
        ('COMP-CACO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_MOLAR_ENTROPY',92.900000,'J/(mol*K)','EVALUATED'),
        ('COMP-CACO3','SOLID','SOLID_REFERENCE_STATE','MOLAR_HEAT_CAPACITY',81.900000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-NAHCO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_ENTHALPY_OF_FORMATION',-947.700000,'kJ/mol','EVALUATED'),
        ('COMP-NAHCO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-851.000000,'kJ/mol','EVALUATED'),
        ('COMP-NAHCO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_MOLAR_ENTROPY',102.100000,'J/(mol*K)','EVALUATED'),
        ('COMP-NAHCO3','SOLID','SOLID_REFERENCE_STATE','MOLAR_HEAT_CAPACITY',87.600000,'J/(mol*K)-Cp','EVALUATED'),
        ('COMP-NA2CO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_ENTHALPY_OF_FORMATION',-1130.700000,'kJ/mol','EVALUATED'),
        ('COMP-NA2CO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_GIBBS_ENERGY_OF_FORMATION',-1044.400000,'kJ/mol','EVALUATED'),
        ('COMP-NA2CO3','SOLID','SOLID_REFERENCE_STATE','STANDARD_MOLAR_ENTROPY',135.000000,'J/(mol*K)','EVALUATED'),
        ('COMP-NA2CO3','SOLID','SOLID_REFERENCE_STATE','MOLAR_HEAT_CAPACITY',112.300000,'J/(mol*K)-Cp','EVALUATED')
)
INSERT INTO chemistry.thermodynamic_property_records (
    profile_id,
    property_type,
    numeric_value,
    unit_symbol,
    reference_condition_id,
    evidence_status,
    source_identifier,
    citation,
    reuse_limitations
)
SELECT
    p.id,
    v.property_type,
    v.numeric_value,
    v.unit_symbol,
    c.id,
    v.evidence_status,
    s.source_identifier,
    s.citation,
    s.reuse_limitations
FROM values_table v
JOIN chemistry.thermodynamic_profiles p
    ON p.compound_code = v.compound_code
    AND p.dataset_version = 'thermodynamic-reference-v1.0.0'
JOIN chemistry.thermodynamic_reference_conditions c
    ON c.temperature_kelvin = 298.1500
    AND c.pressure_pascal = 100000.0000
    AND c.physical_state = v.state
    AND c.standard_state_convention = v.convention
CROSS JOIN source s
ON CONFLICT (profile_id, property_type, reference_condition_id, source_identifier) DO NOTHING;
