CREATE TABLE IF NOT EXISTS chemistry.simulation_scientific_event_schemas (
    event_type TEXT PRIMARY KEY,
    operation_type TEXT NOT NULL,
    event_schema_version INTEGER NOT NULL,
    engine_calculation_schema_version INTEGER NOT NULL,
    replay_policy TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO chemistry.simulation_scientific_event_schemas
    (event_type, operation_type, event_schema_version, engine_calculation_schema_version, replay_policy)
VALUES
    ('STOICHIOMETRIC_REACTION_APPLIED', 'STOICHIOMETRIC_REACTION', 1, 1, 'APPLY_RECORDED_STATE_DELTA'),
    ('EQUILIBRIUM_REACTION_APPLIED', 'EQUILIBRIUM_REACTION', 1, 1, 'APPLY_RECORDED_STATE_DELTA'),
    ('KINETIC_PROGRESS_APPLIED', 'KINETIC_PROGRESS', 1, 1, 'APPLY_RECORDED_STATE_DELTA'),
    ('THERMAL_OPERATION_APPLIED', 'THERMAL_OPERATION', 1, 1, 'APPLY_RECORDED_STATE_DELTA'),
    ('GAS_STATE_CHANGED', 'GAS_STATE_CHANGE', 1, 1, 'APPLY_RECORDED_STATE_DELTA'),
    ('PHASE_TRANSITION_APPLIED', 'PHASE_TRANSITION', 1, 1, 'APPLY_RECORDED_STATE_DELTA'),
    ('ELECTROLYSIS_APPLIED', 'ELECTROLYSIS', 1, 1, 'APPLY_RECORDED_STATE_DELTA'),
    ('BOOKKEEPING_MIX_APPLIED', 'BOOKKEEPING_MIX', 1, 1, 'APPLY_RECORDED_STATE_DELTA')
ON CONFLICT (event_type) DO NOTHING;
