package com.ailab.chemistry.domain.container;

public enum ContainerErrorCode {
    INVALID_PROFILE,
    CONTENT_VOLUME_EXCEEDS_WORKING_LIMIT,
    INSUFFICIENT_HEADSPACE,
    OPEN_CONTAINER_NOT_PRESSURE_RATED,
    MISSING_PRESSURE_LIMIT,
    PRESSURE_LIMIT_EXCEEDED,
    MISSING_TEMPERATURE_LIMIT,
    TEMPERATURE_LIMIT_EXCEEDED,
    INCOMPATIBLE_MATERIAL,
    UNKNOWN_COMPATIBILITY,
    COMPATIBILITY_LIMIT_VIOLATED,
    PROFILE_UNAVAILABLE
}
