export type EquipmentOperation = 'idle' | 'heating' | 'cooling' | 'stirring' | 'mixing' | 'active' | 'measuring';
import { Beaker } from 'lucide-react';

export type EquipmentType = 'testtube' | 'beaker' | 'beaker50' | 'beaker100' | 'beaker250' | 'beaker500' | 'erlenmeyer' | 'roundflask' | 'volumetric_flask' | 'graduated_cylinder' | 'separatory_funnel' | 'petridish' | 'watchglass' | 'burner' | 'hotplate' | 'mantle' | 'icebath' | 'coolingbath' | 'refrigerator' | 'thermometer' | 'phmeter' | 'scales' | 'digitalbalance' | 'pipette' | 'burette' | 'condenser' | 'funnel' | 'buchner' | 'filterpaper' | 'clamp' | 'stand' | 'ringstand' | 'magnetic_stirrer' | 'distillation_flask' | 'clampstand' | 'crucible' | 'unsupported';
export type MaterialState = 'liquid' | 'gas' | 'solid' | 'aqueous';
export type Material = { 
  id: string; 
  name: string; 
  formula: string; 
  color: string; 
  state: MaterialState; 
  molarMass?: number; 
  meltingPointC?: number; 
  boilingPointC?: number;
  density?: number;
  safetyFlags?: string[];
  description?: string;
  compatibleOperations?: string[];
  reactionMetadata?: Record<string, any>;
};
export type ContentComponent = {
  materialId: string;
  name: string;
  formula: string;
  amount: number;
  molarAmount?: number;
  unit: 'mL' | 'g' | 'mol';
  phase: MaterialState;
  color: string;
};
export type ItemPort = { id: string; name: string; type: string; x: number; y: number; direction?: string };
export type Item = { 
  id: string; 
  type: EquipmentType; 
  name: string; 
  x: number; 
  y: number; 
  w: number; 
  h: number; 
  scale: number; 
  scaleX?: number;
  scaleY?: number;
  visualScaleX?: number;
  visualScaleY?: number;
  hidden?: boolean;
  rotation: number; 
  material?: Material; 
  contents: ContentComponent[];
  volumeMl: number; 
  capacityMl?: number; 
  liquidLevel: number; 
  temperature: number; 
  pressureBar: number;
  massG: number;
  moles: number;
  targetTemperature?: number; 
  operation: EquipmentOperation; 
  attachedTo?: string; 
  broken?: boolean;
  sealed?: boolean;
  systemType?: 'open' | 'vented' | 'closed';
  valveOpening?: number;
  integrity?: 'intact' | 'stressed' | 'microcracked' | 'cracked' | 'leaking' | 'shattered';
  unsafeConfiguration?: boolean;
  overflowing?: boolean;
  lastOverflowAt?: number;
  measuredTemperatureC?: number;
  measurementStatus?: 'valid' | 'OVER RANGE';
  measurementTarget?: 'liquid' | 'gas' | 'equipment' | 'environment';
  measuredValue?: number;
  capabilities?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  minScale: number;
  maxScale: number;
  portTypes: string[];
  ports: ItemPort[];
  history?: string[];
};
export type Port = 'Glass' | 'Liquid' | 'Gas' | 'Thermal' | 'Electrical' | 'Vacuum';
export type ConnectionMedium = 'liquid' | 'gas' | 'thermal' | 'electrical' | 'mechanical' | 'sensor';
export type Connection = { id: string; from: string; to: string; fromPort?: string; toPort?: string; fromName?: string; toName?: string; fromPortName?: string; toPortName?: string; routePoints?: Array<{ x: number; y: number }>; port: Port; medium: ConnectionMedium; connector: 'glass-tube' | 'rubber-hose' | 'wire' | 'direct' | 'adapter'; direction: 'source-to-target' | 'target-to-source' };
export type LibraryItem = { id: EquipmentType; name: string; w: number; h: number; icon: typeof Beaker };
export type LibraryTab = 'equipment' | 'materials' | 'elements' | 'ai' | 'scenarios';
export type QuickActionState = { action: 'pour' | 'heat' | 'measure' | 'tube' | 'material' | null; step: 'idle' | 'select-target' | 'select-port'; sourceId?: string; targetId?: string; targetPort?: string; };
export type ExperimentResult = {
  scenarioId: string;
  title: string;
  description: string;
  temperatureC?: number;
  volumeMl?: number;
};

export const isVessel = (item: Item) => !!item.capabilities?.container;
export const isLiquidConduit = (item: Pick<Item, 'type'>) => item.type === 'funnel';
