package com.ailab.chemistry.domain.classification;

public enum ClassificationErrorCode {
    INVALID_CLASSIFICATION_CODE,
    CLASSIFICATION_DEFINITION_NOT_FOUND,
    CLASSIFICATION_PROFILE_NOT_FOUND,
    CLASSIFICATION_TAXONOMY_NOT_FOUND,
    DUPLICATE_CLASSIFICATION_ASSIGNMENT,
    INVALID_CLASSIFICATION_PARENT,
    CLASSIFICATION_HIERARCHY_CYCLE,
    CLASSIFICATION_CARDINALITY_VIOLATION,
    CLASSIFICATION_PREREQUISITE_MISSING,
    CLASSIFICATION_DOMAIN_CONFLICT,
    CLASSIFICATION_PROVENANCE_MISSING,
    CLASSIFICATION_RULE_NOT_FOUND,
    UNSAFE_CLASSIFICATION_DERIVATION,
    CLASSIFICATION_DATA_MISMATCH,
    CLASSIFICATION_DATASET_INCOMPLETE
}
