"use client";

import { ArrowDown, Flame, Play } from "lucide-react";
import { useLocale, useTranslations } from "next-intl";

const copy = {
  ru: { title: "Эксперименты", lead: "Иллюстрированные исследования, которые соединяют книгу с живой лабораторией.", open: "Открыть в лаборатории", assembly: "Схема сборки", items: [{ id: "heating-water", name: "Нагревание воды", time: "4 мин", level: "Начальный", text: "Наблюдайте, как нагреватель, стекло и температура жидкости работают вместе." }, { id: "simple-distillation", name: "Простая дистилляция", time: "8 мин", level: "Средний", text: "Проследите путь пара через холодильник в приёмник." }, { id: "acid-base-titration", name: "Кислотно-основное титрование", time: "8 мин", level: "Средний", text: "Точно дозируйте жидкость и определите точку эквивалентности." }] },
  en: { title: "Experiments", lead: "Illustrated studies that connect this book to a live laboratory.", open: "Open in Lab", assembly: "Assembly preview", items: [{ id: "heating-water", name: "Heating Water", time: "4 min", level: "Beginner", text: "Observe how heater, glass and liquid temperature work together." }, { id: "simple-distillation", name: "Simple Distillation", time: "8 min", level: "Intermediate", text: "Follow vapor through a condenser into a receiver." }, { id: "acid-base-titration", name: "Acid–Base Titration", time: "8 min", level: "Intermediate", text: "Deliver precise liquid volumes and identify the endpoint." }] },
  uz: { title: "Tajribalar", lead: "Kitobdagi bilimlarni haqiqiy laboratoriya bilan bog‘laydigan tasvirlangan tadqiqotlar.", open: "Laboratoriyada ochish", assembly: "Yig‘ish ko‘rinishi", items: [{ id: "heating-water", name: "Suvni qizdirish", time: "4 daq", level: "Boshlang‘ich", text: "Qizdirgich, shisha va suyuqlik harorati qanday ishlashini kuzating." }, { id: "simple-distillation", name: "Oddiy distillash", time: "8 daq", level: "O‘rta", text: "Bug‘ning sovutgich orqali qabul qilgichga o‘tishini kuzating." }, { id: "acid-base-titration", name: "Kislota-asos titrlash", time: "8 daq", level: "O‘rta", text: "Suyuqlik hajmini aniq bering va ekvivalentlik nuqtasini toping." }] },
} as const;

export function LocalizedExperimentLibrary({ onOpenLab }: { onOpenLab?: (id: string) => void }) {
  const locale = useLocale() as keyof typeof copy;
  const t = useTranslations("adventure");
  const c = copy[locale] ?? copy.en;
  return <><div className="academy-page-surface rounded-[22px] border border-white/10 p-7 sm:p-10"><p className="text-xs uppercase tracking-[.28em] text-orange-300">{t("chapter")}</p><h1 className="mt-5 font-serif text-5xl font-bold text-white">{c.title}</h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">{c.lead}</p><div className="mt-9 space-y-3">{c.items.map((item, index) => <article key={item.id} className="group border-b border-white/10 py-5 transition hover:border-orange-300/40"><div className="flex items-start gap-4"><span className="font-mono text-orange-300">0{index + 1}</span><div className="flex-1"><h2 className="font-serif text-2xl font-bold text-white">{item.name}</h2><p className="mt-1 text-sm text-slate-400">{item.text}</p><p className="mt-3 text-xs uppercase tracking-wider text-slate-500">{item.level} · {item.time}</p></div><div className="grid h-14 w-14 place-items-center rounded-full border border-orange-300/30 bg-orange-300/10 text-orange-200"><Flame size={22}/></div></div><button onClick={() => onOpenLab?.(item.id)} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-orange-300 px-3 py-2 text-xs font-bold text-slate-950 hover:bg-orange-200"><Play size={13}/>{c.open}</button></article>)}</div></div><div className="academy-page-surface rounded-[22px] border border-white/10 p-7 sm:p-10"><p className="text-xs uppercase tracking-[.25em] text-slate-500">{c.assembly}</p><div className="mt-8 flex flex-col items-center gap-2 text-sm"><span className="border border-cyan-300/30 px-5 py-3 text-cyan-200">Burette · liquid out</span><ArrowDown className="text-cyan-300"/><span className="border border-cyan-300/30 px-5 py-3 text-cyan-200">Erlenmeyer Flask · liquid in</span><ArrowDown className="text-cyan-300"/><span className="border border-orange-300/30 px-5 py-3 text-orange-200">Thermal observation</span></div></div></>;
}
