'use client';

import { Braces, Plus, Trash2 } from 'lucide-react';
import type { JsonObject } from '@/shared/api/contracts/platform';
import { areRuntimeUnitsCompatible } from '@/widgets/sandbox/runtime/unitConversion';
import { isScenarioRuleGroup, type ScenarioCompletionRule, type ScenarioCondition, type ScenarioRuleGroup, type ScenarioRuleNode, type ScenarioSceneObject } from '../scenario.types';

const control = 'rounded-lg border border-white/10 bg-[#080c14] px-3 py-2 text-sm text-white';
const newCondition = (): ScenarioCondition => ({ id: crypto.randomUUID(), type: 'OBJECT_EXISTS', targetAlias: '', materialId: '', portId: '', fromAlias: '', fromPortId: '', toAlias: '', toPortId: '', operator: 'GTE', value: null, maxValue: null, unit: 'mL' });
const newGroup = (): ScenarioRuleGroup => ({ id: crypto.randomUUID(), operator: 'ALL', conditions: [newCondition()] });
const rows = (value: unknown): JsonObject[] => Array.isArray(value) ? value as JsonObject[] : [];
const itemLabel = (item: JsonObject) => String(item.name ?? item.formula ?? item.code ?? item.id);
const rangeTypes = ['TEMPERATURE_IN_RANGE', 'PH_IN_RANGE'];
const targetTypes = ['OBJECT_EXISTS', 'MATERIAL_PRESENT', 'MATERIAL_AMOUNT', 'MATERIAL_PHASE_IS', 'VALUE_COMPARE', 'TEMPERATURE_IN_RANGE', 'PH_IN_RANGE', 'HEATING_STARTED', 'COOLING_STARTED', 'MIXING_STARTED'];
const materialTypes = ['MATERIAL_PRESENT', 'MATERIAL_AMOUNT', 'MATERIAL_PHASE_IS', 'PRODUCT_FORMED'];
type Context = { objects: ScenarioSceneObject[]; materials: JsonObject[]; equipment: JsonObject[]; reactions: JsonObject[] };

function FactOptions() {
  return <><optgroup label="Equipment"><option value="OBJECT_EXISTS">Equipment is present</option></optgroup><optgroup label="Material"><option value="MATERIAL_PRESENT">Material is present</option><option value="MATERIAL_AMOUNT">Material amount</option><option value="MATERIAL_PHASE_IS">Material phase</option></optgroup><optgroup label="Connection"><option value="CONNECTION_EXISTS">Exact ports are connected</option></optgroup><optgroup label="Thermal"><option value="HEATING_STARTED">Heating started</option><option value="COOLING_STARTED">Cooling started</option><option value="TEMPERATURE_IN_RANGE">Temperature range</option></optgroup><optgroup label="Process"><option value="MIXING_STARTED">Mixing started</option><option value="TRANSFER_COMPLETED">Transfer completed</option></optgroup><optgroup label="Measurement"><option value="PH_IN_RANGE">pH range</option><option value="VALUE_COMPARE">Measured value (advanced)</option></optgroup><optgroup label="Reaction"><option value="REACTION_OBSERVED">Reaction occurred</option><option value="PRODUCT_FORMED">Product formed</option></optgroup></>;
}

function ConditionEditor({ condition, context, onChange, onRemove }: { condition: ScenarioCondition; context: Context; onChange: (next: ScenarioCondition) => void; onRemove: () => void }) {
  const sceneObject = (alias: string) => context.objects.find((item) => item.alias === alias);
  const portsFor = (alias: string) => rows(context.equipment.find((item) => String(item.id ?? item.code) === sceneObject(alias)?.equipmentId)?.ports);
  const patch = (next: Partial<ScenarioCondition>) => onChange({ ...condition, ...next });
  const needsTarget = targetTypes.includes(condition.type);
  const isRange = rangeTypes.includes(condition.type);
  let error = '';
  if (needsTarget && !condition.targetAlias) error = 'Select a scene object.';
  else if (condition.targetAlias && !sceneObject(condition.targetAlias)) error = 'The selected alias no longer exists.';
  else if (materialTypes.includes(condition.type) && !condition.materialId) error = 'Select a Material.';
  else if (condition.type === 'MATERIAL_PHASE_IS' && !condition.portId) error = 'Select an expected phase.';
  else if (condition.type === 'CONNECTION_EXISTS' && (!condition.fromAlias || !condition.fromPortId || !condition.toAlias || !condition.toPortId)) error = 'Select both objects and exact ports.';
  else if (condition.type === 'CONNECTION_EXISTS' && condition.fromAlias === condition.toAlias) error = 'A connection requires two different objects.';
  else if (condition.type === 'TRANSFER_COMPLETED' && (!condition.fromAlias || !condition.toAlias)) error = 'Select transfer source and target.';
  else if (isRange && (condition.value === null || condition.maxValue === null)) error = 'Enter both range limits.';
  else if (isRange && Number(condition.maxValue) < Number(condition.value)) error = 'Maximum must be greater than or equal to minimum.';
  else if (['MATERIAL_AMOUNT', 'VALUE_COMPARE'].includes(condition.type) && condition.value === null) error = 'Enter a comparison value.';
  else if (condition.type === 'REACTION_OBSERVED' && !condition.materialId) error = 'Select a Reaction.';
  else if (condition.type === 'VALUE_COMPARE') { const expected = condition.portId === 'temperatureC' ? '°C' : condition.portId === 'pressureBar' ? 'bar' : condition.portId === 'massG' ? 'g' : 'mL'; if (!areRuntimeUnitsCompatible(expected, condition.unit)) error = `${condition.unit || 'The selected unit'} is incompatible with this measurement.`; }
  const objectSelect = (caption: string, selected: string, change: (alias: string) => void) => <label className="text-xs text-slate-400">{caption}<select className={`mt-1 w-full ${control}`} value={selected} onChange={(event) => change(event.target.value)}><option value="">Select object</option>{context.objects.map((item) => <option key={item.id} value={item.alias}>{item.alias}</option>)}</select></label>;
  const portSelect = (caption: string, alias: string, selected: string, change: (id: string) => void) => <label className="text-xs text-slate-400">{caption}<select className={`mt-1 w-full ${control}`} value={selected} disabled={!alias} onChange={(event) => change(event.target.value)}><option value="">Select port</option>{portsFor(alias).map((port) => <option key={String(port.id)} value={String(port.id)}>{String(port.name ?? port.id)} · {String(port.type ?? port.medium ?? '')}</option>)}</select></label>;
  const catalogSelect = (caption: string, source: JsonObject[], selected: string, change: (id: string) => void) => <label className="text-xs text-slate-400">{caption}<select className={`mt-1 w-full ${control}`} value={selected} onChange={(event) => change(event.target.value)}><option value="">Select {caption}</option>{source.map((item) => <option key={String(item.id ?? item.code)} value={String(item.id ?? item.code)}>{itemLabel(item)}</option>)}</select></label>;
  const units = condition.type === 'MATERIAL_AMOUNT' ? ['µL', 'mL', 'L', 'mg', 'g', 'kg', 'mmol', 'mol'] : condition.type === 'PH_IN_RANGE' ? ['pH'] : condition.type === 'TEMPERATURE_IN_RANGE' || condition.portId === 'temperatureC' ? ['°C', 'K'] : condition.portId === 'pressureBar' ? ['bar', 'kPa', 'Pa'] : condition.portId === 'massG' ? ['mg', 'g', 'kg'] : ['µL', 'mL', 'L'];
  return <article className="rounded-xl border border-white/10 bg-[#0b101a] p-3"><div className="flex items-center gap-2"><select aria-label="Condition type" className={`${control} flex-1`} value={condition.type} onChange={(event) => patch({ type: event.target.value as ScenarioCondition['type'], targetAlias: '', materialId: '', portId: '', fromAlias: '', fromPortId: '', toAlias: '', toPortId: '', value: null, maxValue: null, unit: 'mL' })}><FactOptions /></select><button type="button" aria-label="Remove condition" onClick={onRemove} className="grid h-9 w-9 place-items-center rounded-lg text-rose-300 hover:bg-rose-500/10"><Trash2 size={14} /></button></div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4">
    {needsTarget && objectSelect('Target object', condition.targetAlias, (targetAlias) => patch({ targetAlias }))}
    {materialTypes.includes(condition.type) && catalogSelect('Material', context.materials, condition.materialId, (materialId) => patch({ materialId }))}
    {condition.type === 'REACTION_OBSERVED' && catalogSelect('Reaction', context.reactions, condition.materialId, (materialId) => patch({ materialId }))}
    {condition.type === 'MATERIAL_PHASE_IS' && <label className="text-xs text-slate-400">Expected phase<select className={`mt-1 w-full ${control}`} value={condition.portId} onChange={(event) => patch({ portId: event.target.value })}><option value="">Select phase</option>{['SOLID', 'LIQUID', 'GAS', 'AQUEOUS'].map((phase) => <option key={phase}>{phase}</option>)}</select></label>}
    {condition.type === 'CONNECTION_EXISTS' && <>{objectSelect('From object', condition.fromAlias, (fromAlias) => patch({ fromAlias, fromPortId: '' }))}{portSelect('From port', condition.fromAlias, condition.fromPortId, (fromPortId) => patch({ fromPortId }))}{objectSelect('To object', condition.toAlias, (toAlias) => patch({ toAlias, toPortId: '' }))}{portSelect('To port', condition.toAlias, condition.toPortId, (toPortId) => patch({ toPortId }))}</>}
    {condition.type === 'TRANSFER_COMPLETED' && <>{objectSelect('From object', condition.fromAlias, (fromAlias) => patch({ fromAlias }))}{objectSelect('To object', condition.toAlias, (toAlias) => patch({ toAlias }))}{catalogSelect('Material (optional)', context.materials, condition.materialId, (materialId) => patch({ materialId }))}</>}
    {condition.type === 'VALUE_COMPARE' && <label className="text-xs text-slate-400">Measurement<select className={`mt-1 w-full ${control}`} value={condition.portId || 'temperatureC'} onChange={(event) => { const portId = event.target.value; patch({ portId, unit: portId === 'temperatureC' ? '°C' : portId === 'pressureBar' ? 'bar' : portId === 'massG' ? 'g' : 'mL' }); }}><option value="temperatureC">Temperature</option><option value="volumeMl">Volume</option><option value="massG">Mass</option><option value="pressureBar">Pressure</option></select></label>}
    {isRange && <><label className="text-xs text-slate-400">Minimum<input className={`mt-1 w-full ${control}`} type="number" value={condition.value ?? ''} onChange={(event) => patch({ value: event.target.value === '' ? null : Number(event.target.value) })} /></label><label className="text-xs text-slate-400">Maximum<input className={`mt-1 w-full ${control}`} type="number" value={condition.maxValue ?? ''} onChange={(event) => patch({ maxValue: event.target.value === '' ? null : Number(event.target.value) })} /></label></>}
    {['MATERIAL_AMOUNT', 'VALUE_COMPARE'].includes(condition.type) && <><label className="text-xs text-slate-400">Comparator<select className={`mt-1 w-full ${control}`} value={condition.operator} onChange={(event) => patch({ operator: event.target.value as ScenarioCondition['operator'] })}><option value="GTE">At least</option><option value="LTE">At most</option><option value="EQ">Exactly</option></select></label><label className="text-xs text-slate-400">Value<input className={`mt-1 w-full ${control}`} type="number" min="0" value={condition.value ?? ''} onChange={(event) => patch({ value: event.target.value === '' ? null : Number(event.target.value) })} /></label></>}
    {(isRange || ['MATERIAL_AMOUNT', 'VALUE_COMPARE'].includes(condition.type)) && <label className="text-xs text-slate-400">Unit<select className={`mt-1 w-full ${control}`} value={condition.unit} onChange={(event) => patch({ unit: event.target.value })}>{units.map((unit) => <option key={unit}>{unit}</option>)}</select></label>}
  </div>{error && <p role="alert" className="mt-2 text-xs text-amber-300">{error}</p>}</article>;
}

function RuleGroupEditor({ group, context, depth, root, onChange, onRemove }: { group: ScenarioRuleGroup; context: Context; depth: number; root?: boolean; onChange: (next: ScenarioRuleGroup) => void; onRemove?: () => void }) {
  const replace = (id: string, next: ScenarioRuleNode) => onChange({ ...group, conditions: group.conditions.map((node) => node.id === id ? next : node) });
  return <section className={`rounded-xl border p-3 ${root ? 'border-white/10 bg-black/15' : 'border-violet-400/25 bg-violet-500/[.04]'}`}><div className="flex flex-wrap items-center gap-2"><Braces size={15} className="text-violet-300" /><span className="text-xs font-semibold uppercase tracking-wide text-slate-400">{root ? 'Completion rule' : `Nested group ${depth}`}</span><select aria-label="Completion group operator" className={`${control} ml-auto`} value={group.operator} onChange={(event) => onChange({ ...group, operator: event.target.value as ScenarioCompletionRule['operator'] })}><option value="ALL">All match</option><option value="ANY">Any match</option><option value="NOT">None match</option></select>{onRemove && <button type="button" aria-label="Remove group" onClick={onRemove} className="text-rose-300"><Trash2 size={15} /></button>}</div>{!group.conditions.length && <p className="mt-3 rounded-lg border border-amber-400/20 bg-amber-500/10 p-3 text-xs text-amber-200">Add a condition or nested group.</p>}<div className="mt-3 space-y-3">{group.conditions.map((node) => isScenarioRuleGroup(node) ? <RuleGroupEditor key={node.id} group={node} context={context} depth={depth + 1} onChange={(next) => replace(node.id, next)} onRemove={() => onChange({ ...group, conditions: group.conditions.filter((item) => item.id !== node.id) })} /> : <ConditionEditor key={node.id} condition={node} context={context} onChange={(next) => replace(node.id, next)} onRemove={() => onChange({ ...group, conditions: group.conditions.filter((item) => item.id !== node.id) })} />)}</div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => onChange({ ...group, conditions: [...group.conditions, newCondition()] })} className="flex items-center gap-2 rounded-lg border border-violet-400/30 px-3 py-2 text-sm text-violet-200"><Plus size={14} />Add condition</button>{depth < 4 && <button type="button" onClick={() => onChange({ ...group, conditions: [...group.conditions, newGroup()] })} className="flex items-center gap-2 rounded-lg border border-cyan-400/30 px-3 py-2 text-sm text-cyan-200"><Braces size={14} />Add nested group</button>}</div></section>;
}

export function CompletionRuleBuilder({ value, objects, materials, equipment = [], reactions = [], onChange }: { value: ScenarioCompletionRule; objects: ScenarioSceneObject[]; materials: JsonObject[]; equipment?: JsonObject[]; reactions?: JsonObject[]; onChange: (value: ScenarioCompletionRule) => void }) {
  return <RuleGroupEditor root group={value} depth={0} context={{ objects, materials, equipment, reactions }} onChange={onChange} />;
}
