package com.ailab.chemistry.domain.thermodynamics;

public enum EquilibriumCompositionErrorCode {
    INVALID_INITIAL_AMOUNTS,
    INVALID_TEMPERATURE,
    INVALID_PRESSURE,
    INVALID_VOLUME,
    MISSING_PARTICIPANT_AMOUNT,
    UNKNOWN_REACTION,
    UNSUPPORTED_TEMPERATURE,
    PHASE_MISMATCH,
    UNSUPPORTED_MODEL,
    NO_VALID_ROOT,
    SOLVER_FAILURE,
    INCOMPLETE_THERMODYNAMIC_COVERAGE,
    DAVIES_VALIDITY_EXCEEDED
}
