package com.ailab.chemistry.domain.thermodynamics;

public enum ThermodynamicErrorCode {
    INVALID_REFERENCE_CONDITIONS,
    INVALID_PROPERTY_RECORD,
    INCOMPLETE_PROVENANCE,
    DUPLICATE_PROPERTY_RECORD,
    MISSING_PROFILE,
    INVALID_REACTION_THERMODYNAMICS_REQUEST,
    CONFLICTING_STANDARD_STATE_CONVENTION,
    HESS_TARGET_MISMATCH,
    HESS_STATE_INCOMPATIBLE_CANCELLATION
}
