'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, Ban, Eye, Loader2, RefreshCw, Search, ShieldCheck, Trash2, UserRound, X } from 'lucide-react';
import AdminPageHeader from '@/widgets/admin/AdminPageHeader';
import { adminApi, type AdminUserListItem } from '@/entities/user/api/admin.api';
import { errorMessage } from '@/shared/utils/errorMessage';

export default function AdminUsersPage() {
  const [users, setUsers] = useState<AdminUserListItem[]>([]);
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('');
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [busy, setBusy] = useState<string | null>(null); const [selected, setSelected] = useState<AdminUserListItem | null>(null);
  const load = useCallback(async () => {
    setLoading(true); setError('');
    try { setUsers((await adminApi.getUsers({ q: query || undefined, status: status || undefined, size: 100 })).items); }
    catch (reason) { setError(errorMessage(reason, 'Unable to load users')); } finally { setLoading(false); }
  }, [query, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (!selected) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setSelected(null); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [selected]);
  const counts = useMemo(() => ({ active: users.filter(u => u.status === 'ACTIVE').length, blocked: users.filter(u => u.status === 'BLOCKED').length, admins: users.filter(u => u.role.includes('ADMIN')).length }), [users]);
  const toggleBlock = async (user: AdminUserListItem) => { setBusy(user.id); try { if (user.status === 'BLOCKED') await adminApi.unblockUser(user.id); else await adminApi.blockUser(user.id, 'Blocked from the admin interface'); await load(); } catch (reason) { setError(errorMessage(reason, 'User status could not be updated')); } finally { setBusy(null); } };
  const remove = async (user: AdminUserListItem) => { if (!window.confirm(`Delete ${user.displayName}?`)) return; setBusy(user.id); try { await adminApi.deleteUser(user.id); await load(); } catch (reason) { setError(errorMessage(reason, 'User could not be deleted')); } finally { setBusy(null); } };
  const details: Array<[string, unknown]> = selected ? [['User ID', selected.id], ['Role', selected.role], ['Status', selected.status], ['Level', selected.level], ['XP', selected.xp], ['Version', selected.version], ['Created', new Date(selected.createdAt).toLocaleString('en-GB')], ['Last active', selected.lastActiveAt ? new Date(selected.lastActiveAt).toLocaleString('en-GB') : '—']] : [];

  return <div className="space-y-6 pb-12">
    <AdminPageHeader title="Users" description="Accounts, roles, access restrictions and activity from the identity backend." counters={[{ label: 'Total', value: users.length }, { label: 'Active', value: counts.active }, { label: 'Administrators', value: counts.admins }, { label: 'Blocked', value: counts.blocked }]} actions={<button onClick={() => void load()} className="grid h-10 w-10 place-items-center rounded-lg border border-white/10 bg-[#141b2a] text-white" aria-label="Refresh"><RefreshCw size={16} /></button>} />
    <div className="flex flex-wrap gap-3"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8490a3]" size={15} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Name or email…" className="w-full rounded-xl border border-white/10 bg-[#0b101a] py-3 pl-10 pr-4 text-sm text-white outline-none focus:border-violet-500" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-[#0b101a] px-4 text-sm text-white [&>option]:bg-[#0b101a]"><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="BLOCKED">Blocked</option><option value="DEACTIVATED">Deactivated</option></select></div>
    {error && <div className="flex items-center gap-2 rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300"><AlertCircle size={17} />{error}<button className="ml-auto underline" onClick={() => void load()}>Retry</button></div>}
    {loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-violet-400" /></div> : <div className="overflow-x-auto rounded-2xl border border-white/[.07] bg-[#0b101a]"><table className="w-full text-left text-sm"><thead className="border-b border-white/[.07] text-xs uppercase text-[#8490a3]"><tr><th className="px-5 py-4">User</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Level</th><th className="px-5 py-4">Last activity</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{users.map(user => <tr key={user.id} className="border-b border-white/[.05] last:border-0"><td className="px-5 py-4"><div className="flex items-center gap-3"><UserRound className="text-violet-300" size={20} /><div><strong className="block text-white">{user.displayName}</strong><span className="text-xs text-[#8490a3]">{user.email}</span></div></div></td><td className="px-5 py-4 text-cyan-300">{user.role}</td><td className="px-5 py-4 text-white">{user.status}</td><td className="px-5 py-4 text-white">{user.level}</td><td className="px-5 py-4 text-xs text-[#8490a3]">{user.lastActiveAt ? new Date(user.lastActiveAt).toLocaleString('en-GB') : '—'}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={() => setSelected(user)} className="grid h-9 w-9 place-items-center rounded-lg border border-violet-500/20 text-violet-300" aria-label={`Show details for ${user.displayName}`}><Eye size={15} /></button><button disabled={busy === user.id} onClick={() => void toggleBlock(user)} className="grid h-9 w-9 place-items-center rounded-lg border border-amber-500/20 text-amber-300" aria-label="Toggle block">{user.status === 'BLOCKED' ? <ShieldCheck size={15} /> : <Ban size={15} />}</button><button disabled={busy === user.id} onClick={() => void remove(user)} className="grid h-9 w-9 place-items-center rounded-lg border border-red-500/20 text-red-300" aria-label="Delete user"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>}
    {selected && <div className="fixed inset-0 z-[200] grid place-items-center bg-black/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="user-detail-title" onClick={e => { if (e.target === e.currentTarget) setSelected(null); }}><section className="w-full max-w-xl rounded-2xl border border-white/10 bg-[#0b101a] p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-violet-300">User details</p><h2 id="user-detail-title" className="mt-1 text-xl font-bold text-white">{selected.displayName}</h2><p className="text-sm text-[#8490a3]">{selected.email}</p></div><button autoFocus onClick={() => setSelected(null)} className="grid h-9 w-9 place-items-center rounded-lg border border-white/10 text-white" aria-label="Close user details"><X size={16} /></button></div><dl className="mt-6 grid gap-3 sm:grid-cols-2">{details.map(([key, value]) => <div key={key} className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><dt className="text-[11px] uppercase text-[#8490a3]">{key}</dt><dd className="mt-1 break-all text-sm text-white">{String(value)}</dd></div>)}</dl></section></div>}
  </div>;
}
