package com.ailab.chemistry.domain.laboratorysafety;

public enum LaboratorySafetyRuleType {
    CONTAINER_COMPATIBILITY,
    CONTAINER_TEMPERATURE_LIMIT,
    CONTAINER_PRESSURE_LIMIT,
    HEADSPACE_REQUIREMENT,
    EQUIPMENT_OPERATING_LIMIT,
    CALIBRATION_REQUIREMENT,
    VENTILATION_REQUIREMENT,
    FUME_HOOD_REQUIREMENT,
    MATERIAL_COMBINATION_RESTRICTION,
    CONCENTRATION_LIMIT,
    QUANTITY_LIMIT,
    PHASE_RESTRICTION,
    ENVIRONMENT_REQUIREMENT
}
