package com.ailab.chemistry.domain.physicalproperty;

public enum CompoundPhysicalPropertyErrorCode {
    PHYSICAL_PROPERTY_PROFILE_NOT_FOUND,
    PHYSICAL_PROPERTY_DATASET_NOT_FOUND,
    PHYSICAL_PROPERTY_DATASET_INCOMPLETE,
    PHYSICAL_PROPERTY_DATA_MISMATCH,
    PROPERTY_AVAILABILITY_CONFLICT,
    PROPERTY_PROVENANCE_MISSING,
    INVALID_REFERENCE_CONDITIONS,
    INVALID_DENSITY_DATUM,
    INVALID_PHASE_TRANSITION_DATUM,
    INVALID_SOLUBILITY_DATUM,
    INVALID_HEAT_CAPACITY_DATUM,
    INVALID_THERMAL_CONDUCTIVITY_DATUM,
    INVALID_ELECTRICAL_CONDUCTIVITY_DATUM,
    INVALID_VISCOSITY_DATUM,
    INVALID_REFRACTIVE_INDEX_DATUM,
    INVALID_SURFACE_TENSION_DATUM,
    INVALID_VAPOR_PRESSURE_DATUM,
    INVALID_APPEARANCE_DATUM,
    INVALID_ODOR_DATUM,
    INVALID_POLARITY_DATUM,
    INVALID_PH_OBSERVATION,
    DUPLICATE_PROPERTY_DATUM,
    SOLVENT_NOT_FOUND
}
