package com.ailab.chemistry.domain.phasebehavior;

public enum PhaseBehaviorErrorCode {
    MISSING_TRANSITION_RECORD,
    PHASE_MISMATCH,
    UNSUPPORTED_PRESSURE,
    CORRELATION_OUT_OF_RANGE,
    ABOVE_CRITICAL_POINT,
    BELOW_TRIPLE_POINT_PRESSURE,
    MISSING_HEAT_CAPACITY,
    SKIPPED_KNOWN_TRANSITION,
    NONCONTINUOUS_PATH,
    UNSUPPORTED_PHASE_BOUNDARY
}
